### ISSUE TITLE
Segmentation fault under centos 6.6

### ISSUE THREAD

**Issue by yiyunalu** [SuperElastix/elastix#106]
Error:
"./elastix: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./elastix)
./elastix: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./elastix)
./elastix: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./elastix)
./elastix: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./elastix)
./elastix: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./elastix)
./elastix: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./elastix)
./elastix: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/elastix-4.9/lib/libANNlib-4.9.so.1)
./elastix: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/elastix-4.9/lib/libANNlib-4.9.so.1)"?

Fix:
export "LD_LIBRARY_PATH=/usr/local/elastix-4.9/lib/:/usr/local/gcc-6.4.0/lib64/:/usr/local/gcc-6.4.0/lib:/usr/local/glibc-2.15/lib/:$LD_LIBRARY_PATH"

 
Result:
Segmentation fault (core dumped)

Any sugguestions?

**Comment by zheng-broad** [comment]
I'm also getting the error, how do I fix this?
