### ISSUE TITLE
Why my C++ project which uses ITK_Elastix, Opencv library with .net frame work does not in window7 but works fine on window10.

### ISSUE THREAD

**Issue by kyadav78** [SuperElastix/elastix#1065]
I have one C++ project which uses ITK(5.3.0)-Elastix(5.1.0), Opencv(4.7.0) libraies. it works fine on window10 system. the application has managed and unmanaged code. but when same application i am trying on window7, it is not starting.
the error event suggest " The process was terminated due to an internal error in the .NET runtime as IP() with exit code 80131506.

Please someone help me in resolving this issue.
Regards
Kunal

**Comment by N-Dekker** [comment]
Thanks for your report @kyadav78 but I'm sorry, Window 7 just isn't supported anymore. [Microsoft - Windows 7 support ended on January 14, 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962 )  I don't think I can help you with this specific problem  🤷

**Comment by kyadav78** [comment]
but still if i am using the code, it should work i think.

**Comment by N-Dekker** [comment]
Well, it is not _forbidden_ to try to use Elastix on Windows 7. But if the binaries (lib files) are built on a newer version of Windows, it might not work. Also, we never test Elastix on Windows 7 anymore. So it might not be compatible anymore.

**Comment by kyadav78** [comment]
Hi @N-Dekker ,
 i have taken a different approach to solve the issue but i had encountered a different issue which i think you will be able to help me.
i have separated out the ITK-Elastix wrapper code into a different dll and using it in my C++ applications. now my application is successfully starting in Window7.
But while testing in debug mode i am getting Access violation Exceptions at below line of code, can you please help me in resolving this issue.
**code is failing at  while doing dynamic_Casting of param object.**
file Name: itkMacro.h   line num:1387

template <typename TTarget, typename TSource>
TTarget
itkDynamicCastInDebugMode(TSource x)
{
#ifndef NDEBUG
  if (x == nullptr)
  {
    return nullptr;
  }
  **TTarget rval = dynamic_cast<TTarget>(x);**
  if (rval == nullptr)
  {
    itkGenericExceptionMacro(<< "Failed dynamic cast to " << typeid(TTarget).name()
                             << " object type = " << x->GetNameOfClass());
  }
  return rval;
#else
  return static_cast<TTarget>(x);
#endif
}


call stack:
>	DCEElastixITK.dll!itkDynamicCastInDebugMode<elastix::ParameterObject *,itk::DataObject *>(itk::DataObject * x=0x395827f0) Line 1387	C++
 	DCEElastixITK.dll!itk::ElastixRegistrationMethod<itk::Image<float,2>,itk::Image<float,2> >::GenerateData() Line 132	C++
 	DCEElastixITK.dll!itk::ProcessObject::UpdateOutputData(itk::DataObject * __formal=0x3d72f020) Line 1708	C++
 	DCEElastixITK.dll!itk::DataObject::UpdateOutputData() Line 388	C++
 	DCEElastixITK.dll!itk::ImageBase<2>::UpdateOutputData() Line 267	C++
 	DCEElastixITK.dll!itk::DataObject::Update() Line 319	C++

Regards
Kunal

**Comment by kyadav78** [comment]
it worked well when i have done clean build.
