### ISSUE TITLE
How to create c++ dll files of ITK- elastix libraries because static one making executable high size?

### ISSUE THREAD

**Issue by kyadav78** [SuperElastix/elastix#1066]
Hi,
 I have compiled  ITK and Elastix source code and to created static libraries. when using it in my C++ code the executable size is going huge. 
I have used the shared sample code elastix-5.1.0\dox\externalproject\ ElastixTranslationExample.cxx , it is using lot of static libraries.
I am looking for shared libraries, if some one guide me , it will help ful

Regards
Kunal

**Comment by kyadav78** [comment]
@N-Dekker ,
 could you please help here. i will really appreciate it.

**Comment by kyadav78** [comment]
Hi @N-Dekker ,
  Thank you for your response,
 i have two system window 10 and window 7.
 in Window 10, the Elastix code  which does the registration using "filter->UpdateLargestPossibleRegion();" works well. 
but in Window7 , the same process is failing to start and throwing "The process was terminated due to an internal error in the .NET Runtime at IP 74745973 (74470000) with exit code 80131506." error.
i have used same libraries used in window10.
i know you said in Window 7 you guys are not supporting. but can you guide me what would be possible cause , i would customize the elastix code and make it work. as our application runs on both.
Regards
Kunal

**Comment by kyadav78** [comment]
Also one question, below code require all the static libraries to be add in the application?
const auto filter = itk::ElastixRegistrationMethod<ImageType, ImageType>::New();
 "filter->UpdateLargestPossibleRegion();"

**Comment by N-Dekker** [comment]
When you build your application (exe) using static libraries, you can just "ship" the exe file without the lib files. On another computer, the exe file should just run fine without the lib files. You might still need to install Visual C++ redistributables on the other computer, though. https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
