### ISSUE TITLE
Windows build fails due to long name of ReducedDimensionBSplineResampleInterpolator component

### ISSUE THREAD

**Issue by lassoan** [SuperElastix/elastix#11]
For Visual Studio builds, length of file paths, solution name, and project name are limited. It's not a simple number: for example, for VS2005 this sum must be less than 260:
Path length + 1 (separator) +
Solution name length + 1 (separator) +
Project name length + 1 (separator) +
Project name length +
80 (Reserved space)
(https://social.msdn.microsoft.com/Forums/en-US/d614d0ba-eea2-444b-9be8-7fe4fb85a226/problem-re-path-length-allowed-for-new-project-in-vs2005?forum=csharpide - there are similar limits for newer versions, too, but I could not find the exact formula).

ReducedDimensionBSplineResampleInterpolator component has both an extremely long project name, directory path, and file names, which causes build failure on Windows (except if the base path is very short). 

**Would it be possible to rename this component and file names to something shorter?**

For example renaming ReducedDimensionBSplineResampleInterpolator directory to RDBSplineResampleInterpolator  fixes the build error on our nightly build machine (where Elastix is made available as a Slicer extension). Now we apply this patch locally, but it would be nice to have a solution in the official repository (it would make our build system simpler and would reduce the chance that other Elastix users run into the same issue).

**Comment by mstaring** [comment]
i could reproduce

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/639f9a7a39eb4d590fbc4c47b0fbb04fd2ddf36b
https://github.com/SuperElastix/elastix/commit/19a9e40edd596a00d4936838897462774a1bb1a6
should address this

**Comment by lassoan** [comment]
Perfect, thank you!
