### ISSUE TITLE
Elastix Registration Parameters

### ISSUE THREAD

**Issue by stevenagl12** [SuperElastix/elastix#111]
I am working with registering CT images, but the parameters for the generic (all) SlicerElastix registration method does not have any information on the parameters that are within the code. I'm especially looking at the number of iterations that the registration function uses by default in the SlicerElastix module, and if there are any elastic parameters to prevent the program from deforming the image too much, etc.

**Comment by YuchuanQiao** [comment]
I am not familiar with SlicerElastix, however, from the info you provided, it looks like your registration is not properly set. Not only the number of iterations, but also maybe the cost function, transformation model, optimizer et al. It is better you can just use command line to run elastix with parameter files and then you can tune these parameters handly. There is a database of parameters for different applications. Maybe it will help. http://elastix.bigr.nl/wiki/index.php/Parameter_file_database

**Comment by stevenagl12** [comment]
My registrations are fine. I am just trying to find out what the default
parameters are as registration is an iterative process,  so I want to know
if there is a threshold for the optimization that triggers the end of the
registration, or if there is a hard-coded number of iterations it runs
through. I also do not want to run it through the command line as there is
absolutely no benefit to doing so for my research. I've already shown that
the registrations fail with my given sample population as I work with
non-contrast, cadaveric CT's that have different fixation techniques and
pathologies.

**Comment by YuchuanQiao** [comment]
From the SlicerElastix: https://github.com/lassoan/SlicerElastix, I got the following information:
    # Read database from XML file
    elastixParameterSetDatabasePath = os.path.join(self.scriptPath, 'Resources', 'RegistrationParameters', 'ElastixParameterSetDatabase.xml')
    if not os.path.isfile(elastixParameterSetDatabasePath):
      raise ValueError("Failed to open parameter set database: "+elastixParameterSetDatabasePath)
    elastixParameterSetDatabaseXml = vtk.vtkXMLUtilities.ReadElementFromFile(elastixParameterSetDatabasePath)
    elastixParameterSetDatabaseXml.UnRegister(None)
	(from https://github.com/lassoan/SlicerElastix/blob/master/Elastix/Elastix.py)
Here it said you can select the parameter file from list or button in slicer.

And from https://github.com/lassoan/SlicerElastix/blob/master/Elastix/Resources/RegistrationParameters/ElastixParameterSetDatabase.xml, 
I got the parameter MAYBE you selected is 
	<ParameterSet id="par0008"
    modality="3D CT, monomodal"
    content="lung"
    description="intrapatient; B-spline transformation; mutual information"
    publications="Murphy (2008) - Semi-Automatic Reference Standard Construction for Quantitative Evaluation of Lung CT Registration">
    <ParameterFiles>
      <File Name="Parameters.Par0008.affine.txt" />
      <File Name="Parameters.Par0008.elastic.txt" />
    </ParameterFiles>
  </ParameterSet>

And if you keep tracking the registration results, you can select "<p>Registration troubleshooting: check _"Keep temporary files"_ option before starting registration and click on "Show temp folder" to open the folder that contains detailed logs.
" From there you could find the log file, and the parameter settings are also there.

Hope this can help you.

**Comment by mstaring** [comment]
We use a fixed number of iterations in elastix, due to the stochasticity of the optimizers that we use.

Please contact the Slicer mailing list for information on the default setting of the number of iterations, or how to modify that.

**Comment by Borda** [comment]
Hello, I would be interested in what are the best parameters for registering [ANHIR dataset](https://anhir.grand-challenge.org/)? So far I was using the following [parameters](https://github.com/Borda/BIRL/blob/master/configs/elastix_bspline.txt), any advice about what to change/improve? Thx
