### ISSUE TITLE
Website http://elastix.lumc.nl/ is down

### ISSUE THREAD

**Issue by Pieter-VB** [SuperElastix/elastix#1110]
### Discussed in https://github.com/SuperElastix/elastix/discussions/1109

It would be great to make the doxygen available and published in a zip file so we can run it locally, if getting the website up and running again is too much trouble. Just like the manual that is published with every release.

Thanks in advance!

**Comment by mstaring** [comment]
A zip file with the doxygen documentation can be found via the readme: https://github.com/SuperElastix/elastix/blob/main/README.md
