### ISSUE TITLE
Server Not Found Error with broken links

### ISSUE THREAD

**Issue by MariaKarats** [SuperElastix/elastix#1124]
Hello to everyone! I have a quick question. I am trying to access the links at the page 1 (list of all available parameters) and page 2 (parameter file database) of the manual document. Please, could you provide to me the correct link or an alternative way to have access to this kind of information?

Thank you very much for your time and help!

**Comment by gimj1** [comment]
I have been experiencing the same issue with these links. It seems they have been down for several weeks now.

**Comment by gimj1** [comment]
Hi Maria,
For now, the only solution that I've found to view the list of parameters and their descriptions is to build the elastix documentation on your local system using these steps: 
https://github.com/SuperElastix/elastix/wiki/How-to-build-Doxygen-documentation-from-elastix-source-code
(I got this from the wiki)

I hope it helps.

**Comment by mstaring** [comment]
Yes, indeed the website it down. We are working on a solution, but it will take some time.

**Comment by mstaring** [comment]
A zip file with the doxygen documentation can be found via the readme: https://github.com/SuperElastix/elastix/blob/main/README.md

**Comment by MariaKarats** [comment]
Thank you all for your comments and your help!
