### ISSUE TITLE
Exception occurs when using mask

### ISSUE THREAD

**Issue by AndyWangGo** [SuperElastix/elastix#114]
When i try to registrate CT and MR using mask, i pass "fixedMask" image and "movingMask" image to RegisterImages() method in elastixlib.cxx file, the mask images are binary segmented images which are the same size with fixed image and moving image respectively. Exception occurs when registration process is running, the exception is descripted as "Requested region is (at least partially) outside the largest possible region." and it occurs in file "itkImageSamplerBase.hxx" ,line218,void __cdecl itk::ImageSamplerBase<class itk::Image<float,3> >::GenerateInputRequestedRegion(void).
I wonder what causes this problem and what is the right step if i wanna use mask in registration?
Thanks!

**Comment by mstaring** [comment]
I suspect that at least one of your masks does not overlap with the images.
It is good practice to make sure that the physical regions of the fixed image and mask are the same, and also for the moving ones.

**Comment by AndyWangGo** [comment]
> 
> 
> I suspect that at least one of your masks does not overlap with the images.
> It is good practice to make sure that the physical regions of the fixed image and mask are the same, and also for the moving ones.

Thank you for your reply! I confirmed again that the physical regions of the fixed image and mask are the same, and also for the moving ones. Is there any special step to do if i wanna use mask?

**Comment by mstaring** [comment]
In my mind this specific error message is 1-1 related to the domains of the image and masks.
Can you check with the command line version of elastix if this error occurs?

**Comment by AndyWangGo** [comment]
> 
> 
> > I suspect that at least one of your masks does not overlap with the images.
> > It is good practice to make sure that the physical regions of the fixed image and mask are the same, and also for the moving ones.
> 
> Thank you for your reply! I confirmed again that the physical regions of the fixed image and mask are the same, and also for the moving ones. Is there any special step to do if i wanna use mask?

This problem is fixed! It's really due to size unmatch! Another little bug hides in my code, so when i change the size it still doesn't work. It works after the little bug is found, thank you very much!

**Comment by mstaring** [comment]
Great, thanks for letting us know.
