### ISSUE TITLE
Exception throwed when "ErodeMask" parameter is set as "true"

### ISSUE THREAD

**Issue by AndyWangGo** [SuperElastix/elastix#115]
I try to use segmented images as masks to registrate two images. When i set "ErodeMask" parameter as "false", it works, but when i set "ErodeMask" parameter as "true", exception is throwed which is described as "Requested region is (at least partially) outside the largest possible region". What may cause this exception?
Thanks!

**Comment by mstaring** [comment]
Perhaps the erosion reduces the mask to zero? Is your mask quite small?

**Comment by DimaKuli** [comment]
Hello, everyone)

I try use mask to fixed image for apply registration. But after start code, i have mistake in logs: 'the bounding box of the mask lies entirely out of the InputImageRegion!'. After studying chats with a similar error, I want to try using install ErodeMask to false. How i can do it?

My code now:

  parameter_object = itk.ParameterObject.New()

  parameter_map_translation = parameter_object.GetDefaultParameterMap('translation')
  parameter_map_translation['MaximumNumberOfSamplingAttempts'] = ('4', )

  parameter_object.AddParameterMap(parameter_map_translation)
  
  parameter_map_affine = parameter_object.GetDefaultParameterMap('affine')
  parameter_object.AddParameterMap(parameter_map_affine)


  resolutions = 5
  Grid_Spacing_PhysicalUnits = 15.
  parameter_map_bspline = parameter_object.GetDefaultParameterMap('bspline', resolutions, 
                                                                  Grid_Spacing_PhysicalUnits)
      
  parameter_object.AddParameterMap(parameter_map_bspline)

  print(parameter_object)
  elastix_object = itk.ElastixRegistrationMethod.New(img_1, img_2)
  elastix_object.SetFixedImage(img_1)
  elastix_object.SetMovingImage(img_2)
  
  elastix_object.SetFixedMask(fixPosM)
  #elastix_object.SetMovingMask(movDoM)
  #parameter_object['ErodeFixedMask'] = 'false'  I want apply something like this

  elastix_object.SetParameterObject(parameter_object)
  elastix_object.SetLogToConsole(True)

  elastix_object.UpdateLargestPossibleRegion()
  
  result_image = elastix_object.GetOutput()
