### ISSUE TITLE
elastix doxygen output missing modules.html

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#1203]
When running doxygen (as described at https://github.com/SuperElastix/elastix/wiki/How-to-build-Doxygen-documentation-from-elastix-source-code), the file "modules.html" is no longer generated, accidentally. Even though [Modules.dox](https://github.com/SuperElastix/elastix/blob/ebb429a33bdf3248c2137fc4adb4259a2ec7db24/dox/doxygen/Modules.dox) does get processed, when running doxygen.

- Possibly related to pull request #1197

As a workaround, Michèle (@mwjhhuijberts) just restored the previous version of the file at https://elastix.dev/doxygen/modules.html, after having removed [the obsolete "defgroup xout"](https://github.com/SuperElastix/elastix/commit/ebb429a33bdf3248c2137fc4adb4259a2ec7db24)

**Comment by mwjhhuijberts** [comment]
After copying the modules.html from the previous Doxygen version, commented out the line for "group__xout.html", since that is no longer needed.

**Comment by mwjhhuijberts** [comment]
Deleted the Doxygen maintenance message on the Home Page.
