### ISSUE TITLE
Atlas generation using elastix fails

### ISSUE THREAD

**Issue by vzickus** [SuperElastix/elastix#121]
I suspect this is not Elastix related (I guess there is some issue with the script), but since it's on the  [wiki](https://github.com/SuperElastix/elastix/wiki), might be worth mentioning. I wonder if someone can reproduce this?

Running the atlas_register-population-spheres-demo.py script with python 2.7 I get the following:

```
> Create average transformations...

>> transform centers> reference: 001 - failed

> Compute the inverse average transformation...

>> registration inv > reference: 001 - success in x
>> registration inv > reference: 002 - failed
>> transformation   > reference: 001 - failed
>> transformation   > reference: 002 - failed
>> transformation   > reference: 003 - failed
>> transformation   > reference: 004 - failed
>> transformation   > reference: 005 - failed
>> transformation   > reference: 006 - failed

> Compute reference subject...

```
```
Traceback (most recent call last):
  File "atlas_register-population-spheres-demo.py", line 603, in <module>
    volume     = reader.Execute()
  File "/home/vzickus/anaconda3/envs/Python27/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 8654, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "/home/vzickus/0_Temp_processing/elastix_atlas_generation/elastix.wiki/images/atlas/output/sphere_pop_avg/002/result.mhd" does not exist.

```

**Comment by kaspermarstal** [comment]
It looks like SimpleITK fails to read some images. Check that the images are indeed where the script expects them to be.

Note that this script calls the command line version of elastix. These days we have a native Python wrapper https://github.com/SuperElastix/SimpleElastix that you might find interesting for these sort of tasks.

**Comment by vzickus** [comment]
For some reason the TransformParameters.avg.... files were not being generated properly. Commenting out lines 424-456 in  `atlas_register-population-spheres-demo.py` allowed a temporary bodge for the parameter files to be created (no idea if the transforms are correct though.

@kaspermarstal do the examples in the wiki work for you?

**Comment by kaspermarstal** [comment]
I have not run this example on the wiki. It should probably be removed or fixed up if indeed they don't work @mstaring.

Th behavior you are seeing is not a registration issue, it is a missing file in "/home/vzickus/0_Temp_processing/elastix_atlas_generation/elastix.wiki/images/atlas/output/sphere_pop_avg/002/result.mhd". Check to see that the files are indeed where the script expects them to be. If not, place files in the right location, or perhaps you can fix up the script and let us know the solution so we can update the example on the wiki.

My comment about SimpleElastix was made because juggling with files becomes easier in SimpleElastix where you don't need to manage files at all. You can just use regular python variables for your images and keep all intermediary images in memory. Of course it requires changes to the example code but my guess is this would be easier for you in the long run.

**Comment by vzickus** [comment]
@kaspermarstal sorry, I was not very clear in my previous posts. The .mhd files should have been created if the "TransformParameters.avg002.txt, TransformParameters.avg003.txt" etc. were created. However, for some reason they were not created. Commenting out lines 424-456 allowed the creation of these transformation files. Then rerunning the scrip with the lines uncommented, I could get the result.mhd files were they were supposed to be.

I do not get the error any more, but the transforms supposedly fail:

```
> Create average transformations...

>> transform centers> reference: 001 - failed

> Compute the inverse average transformation...

>> registration inv > reference: 001 - success in x
>> registration inv > reference: 002 - success in x
>> registration inv > reference: 003 - success in x
>> registration inv > reference: 004 - success in x
>> registration inv > reference: 005 - success in x
>> registration inv > reference: 006 - success in x
>> transformation   > reference: 001 - failed
>> transformation   > reference: 002 - failed
>> transformation   > reference: 003 - failed
>> transformation   > reference: 004 - failed
>> transformation   > reference: 005 - failed
>> transformation   > reference: 006 - failed

> Compute reference subject...

>> voxel average    > success
```

**Comment by kaspermarstal** [comment]
Can you post the error message from one of the transformations that fail?

**Comment by vzickus** [comment]
That's the problem(?), transformix.logs do not report any errors.

I believe the problem was in Lines 572-577
```

  for line in out:
    if("Elapsed time" in line):
      seconds = line.replace("Elapsed time: ", "")
      seconds = seconds.replace(" Seconds.", "")
      transformAverageInverseSeconds = int(seconds)
      success = True
```

As `Elapsed time` never appears in the output of transformix as far as I can tell (maybe it was different in version 4.6 when this was written?).

I would create a PR, but I can't figure out where these scripts live?

**Comment by kaspermarstal** [comment]
They only live on the wiki i believe. I am not familiar with them.

**Comment by mstaring** [comment]
These were contributed by a user. I am not aware if they are on version control somewhere. You could request an account on the wiki and replace these files?

**Comment by vzickus** [comment]
@mstaring thanks for your reply. I haven't had time to play with this further, but I guess as @kaspermarstal said SimpleElastix could be a better way to do this as described here https://simpleelastix.readthedocs.io/GroupwiseRegistration.html

**Comment by mstaring** [comment]
OK, I'll close this issue for now. Feel free to reopen when needed.
