### ISSUE TITLE
What’s the usage of spacing and origin? Are they really needed?

### ISSUE THREAD

**Issue by yaoli** [SuperElastix/elastix#126]
UseDirectionCosines: Controls whether to use or ignore the direction cosines (world matrix, transform matrix) set in the images. Voxel spacing and image origin are always taken into account, regardless the setting of this parameter.

I’m not sure how spacing and origin are used in producing the correct transformation, could you elaborate?

**Comment by mstaring** [comment]
Please check the manual for information on this
