### ISSUE TITLE
Request to share parameter files 

### ISSUE THREAD

**Issue by jeffu3667** [SuperElastix/elastix#127]
I would like to post the parameter file in the database for publication, so I requested an Elastix account in the wiki. However, still no response yet. I'm wondering who I should talk with for faster access?

**Comment by mstaring** [comment]
I just approved your account request.

**Comment by jeffu3667** [comment]
Thank you Marius. However, I did not receive a password. I tried to reset my password online. But no email was received. Would you mind helping me with this? Or is there any other convenient way to share parameter files?

**Comment by jeffu3667** [comment]
Thank you Marius. However, I did not receive a password. I tried to reset my password online. But no email was received. Would you mind helping me with this? Or is there any other convenient way to share parameter files? @mstaring

**Comment by congyang1996** [comment]
Hi mstaring, could you please help me about the accout request? My email comfirmed a request, but I didn't receive a password. Thank you a lot. @mstaring

**Comment by mstaring** [comment]
I approved it

**Comment by congyang1996** [comment]
> I approved it

Thank you, mstaring. ^_^
