### ISSUE TITLE
elastix OpenCL components not installed

### ISSUE THREAD

**Issue by sxl1174** [SuperElastix/elastix#129]
Hi, I'm trying to build elastix (with OpenCl ) on Linux by myself. I first git cloned, compiled and installed the ITK. Then compiled and installed elastix using the following commands:

cmake -DELASTIX_USE_OPENCL=ON -DUSE_OpenCLFixedGenericPyramid=ON -DUSE_OpenCLMovingGenericPyramid=ON -DUSE_OpenCLResampler=ON -DOPENCL_OPTIMIZATION_MAD_ENABLE=ON -DOPENCL_USENVIDIA_SDK=ON -DOPENCL_C_VERSION_1_2=ON -DOPENCL_INCLUDE_DIRS=/usr/local/cuda-9.0/include -DOPENCL_LIBRARIES=/usr/local/cuda-9.0/lib64/libOpenCL.so.1 -DCMAKE_INSTALL_PREFIX=/home/sxl1174/software/elastix1/install -DITK_DIR=/home/sxl1174/software/ITK/bin -Hsrc -Bbin
make
make install

Both compiling and installation went well. I successfully got the elastix and transformix release files. However, when I tried to use elastix, it showed that all openCL components were not installed. Did anyone ever successfully run openCL-elastix on GPU? Could anyone help me out with this issue? I'd really appreciate it.

<img width="827" alt="error_elastix" src="https://user-images.githubusercontent.com/48453791/54874770-26b98080-4dc8-11e9-8ca5-464acc7b32f3.png">

**Comment by mstaring** [comment]
I think you made a mistake in the parameter file. The pyramid name should not end with UseOpenCL. It should be:

OpenCLFixedGenericImagePyramid
