### ISSUE TITLE
Thin_plate_spline 

### ISSUE THREAD

**Issue by Wafamah** [SuperElastix/elastix#134]
Dear all, 

I'm using CMake, and the registration task is specified as follows:

C:\"Program FIles"\Elastix\elastix^
-f C:\Users\W\Documents\Elastix_IN\Fixed256.nii ^
-m C:\Users\W\Documents\Elastix_IN\movingresize.nii ^
-out C:\Users\W\Documents\Elastix_OUT ^
-p C:\Users\W\Documents\Elastix_PARS\parameters_TPS.txt

I don't know how to specify fp and mp to run Thin plate spline. 

If I don't have specific corresponding  points and I would to run Thin plate spline based on overall similarities between fixed and moving images. If there is a way, how can I do it? 

What are the key parameters I should change in the parameter file to enable thin plate spline?

I'm not expert user, and aI would appreciate any detailed answer.

Thanks,
wafa

**Comment by mstaring** [comment]
Dear Wafa,
Please post your question on the mailing list:
https://groups.google.com/forum/#!categories/elastix-imageregistration/elastix
