### ISSUE TITLE
4.9 release: Linux binary download link broken

### ISSUE THREAD

**Issue by quakberto** [SuperElastix/elastix#139]
Hi,

in the release summary (https://github.com/SuperElastix/elastix/releases), the download link for elastix 4.9 for linux seems to be broken: https://github.com/SuperElastix/elastix/releases/download/4.9.0/elastix-4.9.0-linux64.zip

Just wanted to report.
Thanks!

EDIT: After having a look at the download statistics I found the binary at https://github.com/SuperElastix/elastix/releases/download/4.9.0/elastix-4.9.0-linux.tar.bz2

**Comment by mstaring** [comment]
thanks!
I fixed the link
