### ISSUE TITLE
How can I avoid getting unexpected Decimal data type in segmentation when I do the registration using only one Atlas?

### ISSUE THREAD

**Issue by TiancongHua** [SuperElastix/elastix#152]
I'm tring to acquire a segentation of  LGE  MR image by registration using normal MR image with label(only one). But I got a decimal data type in segmentation, I have tried using 
`resultLabel=sitk.Round(resultLabel)`
or
`resultLabel=sitk.Cast(resultLabel,sitk.sitkInt8)`

I got a better result using sitk.Round rather than `sitk.sitkInt8`, but it's not god enough beacause there are noise in the multi-label segmentation.
How can  I get an good result using simpleElastx? Really confused.

**Comment by TiancongHua** [comment]
my code is here:
```
parameterMap = sitk.GetDefaultParameterMap('translation')
elastixImageFilter = SimpleITK.ElastixImageFilter()
elastixImageFilter.SetFixedImage(fixedImage)
elastixImageFilter.SetMovingImage(movingImage)
elastixImageFilter.SetParameterMap(parameterMap)
elastixImageFilter.Execute()
resultImage = elastixImageFilter.GetResultImage()
sitk.WriteImage(resultImage,'movedimage.nii.gz')
transformParameterMap = elastixImageFilter.GetTransformParameterMap()
resultLabel=sitk.Transformix(atlasLabel,transformParameterMap)
```

**Comment by mstaring** [comment]
In normal elastix you would add the lines
(ResampleInterpolator "FinalBSplineInterpolator")
(FinalBSplineInterpolationOrder 0)
or the line
(ResampleInterpolator "FinalNearestNeighborInterpolator")
to the parameter file.

I think you can do that also with SimpleElastix.
