### ISSUE TITLE
point format in VTK coordinate system

### ISSUE THREAD

**Issue by Borda** [SuperElastix/elastix#156]
Hello, I am experimenting with image registration and later on transforming/warping some points (see [manual, sec 4.2](https://blog.yuwu.me/wp-content/uploads/2017/10/elastix_manual_v4.8.pdf)). It says that the points are from VTK, but so far I was not able to warp my points properly probably due to a different coordinate system. Mine has origin [0, 0] in the top left corner of the image and increasing in direction to the bottom right corner... What is the VTK coordinate frame? Thx
@stefanklein @N-Dekker @FBerendsen @kaspermarstal ^^

**Comment by YuchuanQiao** [comment]
The points to be transformed should be with the same origin from the image.
You could use the following format:
"point
1
-40.940000 -47.022000 -1169.500000"

**Comment by Borda** [comment]
the format is clear, it is written in the manual but, where are the origin and orientation?
```
<index, point>
<number of points>
point1 x point1 y [point1 z]
point2 x point2 y [point2 z]
. . .
```

**Comment by Borda** [comment]
@kaspermarstal it may be good to add such information also here - https://github.com/SuperElastix/SimpleElastix/pull/305

**Comment by YuchuanQiao** [comment]
As I say "The points to be transformed should be with the same origin from the image."
This information is in the output file "TransformParameters.0.txt" after you perform the image registration.
"(Origin 0.0000000000 0.0000000000)
(Direction 1.0000000000 0.0000000000 0.0000000000 1.0000000000)"
Not explicitly shown in the point.txt. The landmarks in your csv file look like in image space, maybe you should convert them to physical space. All points here are in physical space.

**Comment by Borda** [comment]
Sorry, but still I don't know what is the coordinates points in image, for example, four image corners (top-left, top-right, bottom-right, bottom-left) for an image with height 600px and width 800px... 
```
(Transform "AffineTransform")
(NumberOfParameters 6)
(TransformParameters 0.999892 0.000142 0.000006 0.999862 91.981900 19.050974)
(InitialTransformParametersFileName "NoInitialTransform")
(HowToCombineTransforms "Compose")
// Image specific
(FixedImageDimension 2)
(MovingImageDimension 2)
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(Size 800 600)
(Index 0 0)
(Spacing 1.0000000000 1.0000000000)
(Origin 0.0000000000 0.0000000000)
(Direction 1.0000000000 0.0000000000 0.0000000000 1.0000000000)
(UseDirectionCosines "true")
// AdvancedAffineTransform specific
(CenterOfRotationPoint 399.5000000000 299.5000000000)
// ResampleInterpolator specific
...
// Resampler specific
...
```
Yes, there is a position of origin, but where is it in the image plane, where is the (0, 0) in centre, corner, which corner? and direction... is positive up, down is fist vertical o horizontal direction...?

In my case the pixel and physical space should be the same, using the same units since I am using PNG images and there is no other information about the conversion...

**Comment by Borda** [comment]
any idea? @stefanklein @N-Dekker @FBerendsen @kaspermarstal

**Comment by mstaring** [comment]
We use the ITK coordinate system, so the origin is in the lower left. Please see the manual, where we copied some information from the ITK guide on this matter. Does this help?

**Comment by Borda** [comment]
@mstaring thank you, I think that I found it now and I will check it if it works for me...
![image](https://user-images.githubusercontent.com/6035284/61277026-8f7e9b80-a7b1-11e9-98d4-527a688c8a6f.png)
anyway, may I recommend to refer this figure also in [manual, sec 4.2](https://blog.yuwu.me/wp-content/uploads/2017/10/elastix_manual_v4.8.pdf) as it is focusing on point warping...

**Comment by Borda** [comment]
@mstaring it is strange because implementing this change does not help... Then I use the very same coordinate system as I have from the beginning and it gives expected transformed location... any idea why? (I used [row, column] and origin in the top left corner)

**Comment by mstaring** [comment]
Did you recreate the affine transformation model precisely the same? including center of rotation. The precise mechanism can be found in the source code

**Comment by Borda** [comment]
I used the generated transformation produced by the `elastix` image registration. See e.g.
[TransformParameters.0.txt](https://github.com/SuperElastix/elastix/files/3405662/TransformParameters.0.txt)

**Comment by mstaring** [comment]
Yes but if you do not use transformix for creating and executing the affine transformation, you have to be sure you are doing the exact same thing. (just looking for potential sources of bugs)

**Comment by Borda** [comment]
I was running following two commands, for registration
```bash
/home/jb/Applications/elastix/bin/elastix \
    -f /home/jb/Dropbox/Workspace/BIRL/data_images/images/artificial_reference.jpg \
    -m /home/jb/Dropbox/Workspace/BIRL/data_images/images/artificial_moving-affine.jpg \
    -out /home/jb/Desktop/BmElastix_20190717-135929/1 \
    -p /home/jb/Desktop/BmElastix_20190717-135929/elastix_affine.txt
```
and transformation
```bash
/home/jb/Applications/elastix/bin/transformix \
    -tp /home/jb/Desktop/BmElastix_20190717-135929/1/TransformParameters.0.txt \
    -out /home/jb/Desktop/BmElastix_20190717-135929/1 \
    -in /home/jb/Dropbox/Workspace/BIRL/data_images/images/artificial_moving-affine.jpg \
    -def /home/jb/Desktop/BmElastix_20190717-135929/1/artificial_reference.pts
```

**Comment by mstaring** [comment]
ok so you do use transformix, but the problem is how to define the pts file?

**Comment by mstaring** [comment]
reading above, you seem to know how to define the pts. Then I assume the problem is how to view the result. can you confirm?

**Comment by mstaring** [comment]
the origin etc are the same as that of the fixed image

**Comment by Borda** [comment]
yes, my main concern was about used a coordinate system which was referred to VTK but until you pointed the figure in manual it was hard to find it anywhere else... What puzzles me no that when use the coordinate system defined in Fig.2.3 I got following transformation
![registration_visual_landmarks](https://user-images.githubusercontent.com/6035284/61449297-e5d80f80-a954-11e9-87c7-9ca67763ce92.jpg)
and with the one I use elsewhere (`numpy` indexing) I got what I expected
![registration_visual_landmarks](https://user-images.githubusercontent.com/6035284/61449358-0b651900-a955-11e9-9b23-2dd46f9d04b3.jpg)
The expected transformation was just translation in both axes. and you can see that image registration would be almost perfect but the points did not match...

**Comment by mstaring** [comment]
Ok, this is hard for me to debug from here. You are sure the registration went well?

**Comment by Borda** [comment]
yes, here is overlap between reference and warped moving image...
![image_refence-warped](https://user-images.githubusercontent.com/6035284/61497041-87e01200-a9be-11e9-85cf-ee2037cae3bf.jpg)

**Comment by Borda** [comment]
@mstaring you may run this script with default parameters to get the images/results I am showing here https://github.com/Borda/BIRL/blob/master/bm_experiments/bm_elastix.py
