### ISSUE TITLE
Registering two binary images

### ISSUE THREAD

**Issue by dogadogan** [SuperElastix/elastix#158]
I am trying to register two binary blobs using the SuperElastix library.
The fixed image is the shape I'd like to get, the moving image comes from a camera image (with a perspective).

My aim was to apply an affine transformation to align the moving image according to the fixed target image. The computer transformation will then be applied to a grayscale image for further processing.

I did a test with these simple shapes:
![Screen Shot 2019-06-28 at 17 20 43](https://user-images.githubusercontent.com/11411924/60372423-98f2c000-99ca-11e9-9ce1-7d6205a821c9.png)

I was expecting to see a more perfectly rectified rectangle, but the shearing of affine transformation seems to be not sufficient in the final result.

I use the following parameters for the transformation:

```
parameterMap = sitk.GetDefaultParameterMap("affine")
parameterMap['MaximumNumberOfIterations'] = ['1024']
parameterMap['Metric'] = ['AdvancedMeanSquares']
```
I also tried using the default AdvancedMattesMutualInformation, NormalizedMutualInformation as the metric, but AdvancedMeanSquares performed better. I have read that AdvancedKappaStatistic works well for binary images but when I try to use it, it gives an error and the code doesn't execute at all. (_AdvancedKappaStatisticMetric(0x7fd8216fab40): Too many samples map outside moving image buffer: 0 / 2048_)

Is there possibly a way to make the final result better?

Thank you very much for your help and interest!

**Comment by dogadogan** [comment]
Ok, thinking about it again, it looks like the affine transformation will never work: any lines that are parallel before an affine transformation will stay parallel afterwards, because it only does rotation, scale, shear, and translation.
What I need is a projective transformation that will take into account the perspective distortion. Is there a way to apply projective transformations in Elastix? (kind of like a homography I guess).

**Comment by mstaring** [comment]
We do not have this implemented.

perhaps there is something in the itk that fits your need?
https://itk.org/Insight/Doxygen/html/group__ITKTransform.html
for example
https://itk.org/Insight/Doxygen/html/classitk_1_1Rigid3DPerspectiveTransform.html

If so, it is quite easy to generate an elastix jacket around it, so that it gets supported by elastix.

**Comment by mstaring** [comment]
feel free to reopen when needed

**Comment by MarHHM** [comment]
> I am trying to register two binary blobs using the SuperElastix library.
> The fixed image is the shape I'd like to get, the moving image comes from a camera image (with a perspective).
> 
> My aim was to apply an affine transformation to align the moving image according to the fixed target image. The computer transformation will then be applied to a grayscale image for further processing.
> 
> I did a test with these simple shapes:
> ![Screen Shot 2019-06-28 at 17 20 43](https://user-images.githubusercontent.com/11411924/60372423-98f2c000-99ca-11e9-9ce1-7d6205a821c9.png)
> 
> I was expecting to see a more perfectly rectified rectangle, but the shearing of affine transformation seems to be not sufficient in the final result.
> 
> I use the following parameters for the transformation:
> 
> ```
> parameterMap = sitk.GetDefaultParameterMap("affine")
> parameterMap['MaximumNumberOfIterations'] = ['1024']
> parameterMap['Metric'] = ['AdvancedMeanSquares']
> ```
> 
> I also tried using the default AdvancedMattesMutualInformation, NormalizedMutualInformation as the metric, but _AdvancedMeanSquares performed better_. I have read that AdvancedKappaStatistic works well for binary images but when I try to use it, it gives an error and the code doesn't execute at all. (_AdvancedKappaStatisticMetric(0x7fd8216fab40): Too many samples map outside moving image buffer: 0 / 2048_)
> 
> Is there possibly a way to make the final result better?
> 
> Thank you very much for your help and interest!

i actually also want to report that "AdvancedMeanSquares" worked for me much better than "AdvancedMattesMutualInformation" for registering binary masks (even with irregular shapes).. 

regarding "AdvancedKappaStatistic " : although the documentation says that it should be good for registering masks, it gave me very weird deformed results.. I tried to see if someone else used it in such scenario (e.g. on the elastix param file database) but couldn't find anything..

@mstaring    do u have any inputs regarding the "AdvancedKappaStatistic" strange performance with binary masks??  would be grateful  :)
