### ISSUE TITLE
AffineLogStackTransform: uninitialized local variable 'rdorigin' used

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#162]
`AffineLogStackTransform::ReadCenterOfRotationIndex(ReducedDimensionInputPointType&)` has a suspicious compilation warning from VS2017:

> elastix\components\transforms\affinelogstacktransform\elxaffinelogstacktransform.hxx(574): warning C4700: uninitialized local variable 'rdorigin' used

    dummyImage->SetOrigin( rdorigin );

https://github.com/SuperElastix/elastix/blob/32a1b346956cf3c250ce357249cbc16bf30310f0/Components/Transforms/AffineLogStackTransform/elxAffineLogStackTransform.hxx#L574

How shall we fix it? Is this function still in use?

**Comment by N-Dekker** [comment]
I think the `dummyImage->SetOrigin( rdorigin )` call can just be removed. But I need to figure out how to test it!

**Comment by mstaring** [comment]
fixed by the above commits
