### ISSUE TITLE
Assistance on installing on CentOS 7

### ISSUE THREAD

**Issue by Seth-Karlo** [SuperElastix/elastix#164]
Hi there,

Have you (or anyone reading) successfully managed to install elastix on CentOS 7? I've been unable to find an up to date enough library that provides GLIBCXX_3.4.21 and I'm trying to avoid doing a full gcc upgrade and compile of elastix if possible.

**Comment by mstaring** [comment]
We have not done so ourselves.
Where you able to do a compilation yourself in the meantime?

**Comment by Seth-Karlo** [comment]
Hey! Sorry for the delay in responding. Yes, I compiled it myself. If you'd like the rpm I'm happy to provide it if it would help anyone.
