### ISSUE TITLE
Format of the output deformable vector field (DVF)

### ISSUE THREAD

**Issue by ubersexualShupeng** [SuperElastix/elastix#17]
Dear all, 

I run the deformable image registration toolbox and have the file. (result.0.raw, result.0.mhd & TransformParameters.0.txt)
I wonder if there is any document that described the format of the output DVF. 
Thank you.

Shupeng

**Comment by mstaring** [comment]
Hi Shupeng,
The manual, chapter 4, may give you the required information.
Kindly also note that we have a mailing list for requests for information, while this issue list is more for bug reports and feature requests.
Best, Marius

manual: http://elastix.isi.uu.nl/download.php
mailing list subscription: http://lists.bigr.nl/mailman/listinfo/elastix
