### ISSUE TITLE
Is there a plan for new version?

### ISSUE THREAD

**Issue by Nekto89** [SuperElastix/elastix#172]
Are you planning to make new elastix release with ITK5 support?

**Comment by GouZi2019** [comment]
This version can build with ITK5.0.0, but cant build with ITK4.13.0 in my PC

**Comment by Nekto89** [comment]
> 
> 
> This version can build with ITK5.0.0, but cant build with ITK4.13.0 in my PC

I'm asking about official release. Last one (4.9.0) was on Mar 20, 2018.

**Comment by mstaring** [comment]
We are working on it :-)

**Comment by N-Dekker** [comment]
Here it is: https://github.com/SuperElastix/elastix/releases/tag/5.0.0
