### ISSUE TITLE
UseDirectionCosines default value

### ISSUE THREAD

**Issue by soupault** [SuperElastix/elastix#176]
Hello,

https://github.com/SuperElastix/elastix/blob/0ce6c24a2b74c0132f1a53848321f1c7a92162ea/Core/Kernel/elxElastixBase.cxx#L68-L70

but in http://elastix.isi.uu.nl/doxygen/transformparameter.html:

![image](https://user-images.githubusercontent.com/1315589/63510947-930bed80-c4e8-11e9-8b74-ded489a9b652.png)

**Comment by soupault** [comment]
Hmm, it seems to be redefined several times:
https://github.com/SuperElastix/elastix/blob/0ce6c24a2b74c0132f1a53848321f1c7a92162ea/Core/Kernel/elxElastixBase.cxx#L224-L227
and
https://github.com/SuperElastix/elastix/blob/0ce6c24a2b74c0132f1a53848321f1c7a92162ea/Core/Kernel/elxElastixBase.cxx#L321-L324

Sorry, if I am mistaken, but that looks somewhat confusing.

**Comment by soupault** [comment]
As a side note, I think it would be beneficial to have couple of words in the documentation on how the image metainfo (orientation, spacing, origin) is used. I have not been able to find anything before I started looking at the code.

**Comment by mstaring** [comment]
See also chapter 2.2 of the manual on the definition of an image coordinate system.

**Comment by soupault** [comment]
@mstaring thanks for the prompt fix and the reference!
