### ISSUE TITLE
Error when using fixed mask in MultiMetricMultiResolutionRegistration

### ISSUE THREAD

**Issue by pcarnah** [SuperElastix/elastix#179]
Elastix fails with an error when using MultiMetricMultiResolutionRegistration both with a single fixed image and with multiple. It appears that the mask is causing the entire image to be treated as invalid. This is the error message that appears with all tested inputs:

`itk::ExceptionObject (0000003967EFF598)
Location: "ElastixTemplate - Run()"
File: c:\d\forks\elastix\common\itkComputeJacobianTerms.hxx
Line: 550
Description: itk::ERROR: ComputeJacobianTerms(0000020098EAA5E0): No valid voxels (0/1000) found to estimate the AdaptiveStochasticGradientDescent parameters.   
Error occurred during actual registration.`

I have tested this with multiple images and parameter combinations that previously worked as of commit d506b227560307c85122f2711894bebffb149f6b.

**Comment by N-Dekker** [comment]
Fixed by pull request #186 commit https://github.com/SuperElastix/elastix/commit/2cba368150f66d20a5146b4053a2e579614b4796 A big thank you to Patrick Carnahan (@pcarnah) for reporting this major issue.
