### ISSUE TITLE
Replace ANN library?

### ISSUE THREAD

**Issue by thewtex** [SuperElastix/elastix#182]
It would be nice to have something that is not LGPL. Also, there may be faster alternatives now, per:

  http://ann-benchmarks.com/
  https://github.com/erikbern/ann-benchmarks

**Comment by N-Dekker** [comment]
Thanks for the suggestions, Matt! However, I'm sorry to say, we have no plans to fix this issue. Elastix has an option to disable the only component that uses the ANN library, by CMake `USE_KNNGraphAlphaMutualInformationMetric = OFF`.

I hope that that's a sufficient solution to you.

**Comment by thewtex** [comment]
@N-Dekker thanks for the information! Yes, that works for me :+1:
