### ISSUE TITLE
elastix 4.9 libs : more threads, more slow

### ISSUE THREAD

**Issue by GouZi2019** [SuperElastix/elastix#185]
I build Elastix 4.9 libs for registration in C++, using 1 thread takes 0.6s while using 12 threads takes 4s!
And I try this registration in Elastix 4.9 exe (elastix.exe), using 1 thread takes 0.9s while using 12 threads takes 0.4s.
What is the reason for it?
Thank you!

**Comment by N-Dekker** [comment]
@GouZi2019 Thank you for sharing this issue! Can you give us some more details? Did you do "Debug" or "Release" build? What kind of registration did you do?

**Comment by GouZi2019** [comment]
@N-Dekker Thank you for responding!
I built the Elastix in "Debug" and "Release" versions with:
"ELASTIX_BUILD_EXECUTABLE"  OFF
"BUILD_SHARED_LIBS"  OFF
"ITK_DIR" ITK-4.13.0 (also try 4.13.1 and 4.13.2)
"CMAKE_DEBUG_POSTFIX"  d

My part of the code is as follows (2D-2D registration):
`
	std::vector<std::string> BSplineInterpolationOrder;
	BSplineInterpolationOrder.push_back("1");
	parameter.insert_or_assign("BSplineInterpolationOrder", BSplineInterpolationOrder);

	std::vector<std::string> DefaultPixelValue;
	DefaultPixelValue.push_back("1616");
	parameter.insert_or_assign("DefaultPixelValue", DefaultPixelValue);

	std::vector<std::string> FinalBSplineInterpolationOrder;
	FinalBSplineInterpolationOrder.push_back("3");
	parameter.insert_or_assign("FinalBSplineInterpolationOrder", FinalBSplineInterpolationOrder);

	std::vector<std::string> FinalGridSpacingInPhysicalUnits;
	FinalGridSpacingInPhysicalUnits.push_back("8");
	parameter.insert_or_assign("FinalGridSpacingInPhysicalUnits", FinalGridSpacingInPhysicalUnits);

	std::vector<std::string> FixedImageDimension;
	FixedImageDimension.push_back("2");
	parameter.insert_or_assign("FixedImageDimension", FixedImageDimension);

	std::vector<std::string> FixedImagePyramid;
	FixedImagePyramid.push_back("FixedRecursiveImagePyramid");
	parameter.insert_or_assign("FixedImagePyramid", FixedImagePyramid);

	std::vector<std::string> FixedInternalImagePixelType;
	FixedInternalImagePixelType.push_back("float");
	parameter.insert_or_assign("FixedInternalImagePixelType", FixedInternalImagePixelType);

	std::vector<std::string> HowToCombineTransforms;
	HowToCombineTransforms.push_back("Compose");
	parameter.insert_or_assign("HowToCombineTransforms", HowToCombineTransforms);

	std::vector<std::string> ImageSampler;
	ImageSampler.push_back("Random");
	parameter.insert_or_assign("ImageSampler", ImageSampler);

	std::vector<std::string> Interpolator;
	Interpolator.push_back("BSplineInterpolator");
	parameter.insert_or_assign("Interpolator", Interpolator);

	std::vector<std::string> MaximumNumberOfIterations;
	MaximumNumberOfIterations.push_back("50");
	parameter.insert_or_assign("MaximumNumberOfIterations", MaximumNumberOfIterations);

	std::vector<std::string> Metric;
	Metric.push_back("AdvancedMattesMutualInformation");
	parameter.insert_or_assign("Metric", Metric);

	std::vector<std::string> MovingImageDimension;
	MovingImageDimension.push_back("2");
	parameter.insert_or_assign("MovingImageDimension", MovingImageDimension);

	std::vector<std::string> MovingImagePyramid;
	MovingImagePyramid.push_back("MovingRecursiveImagePyramid");
	parameter.insert_or_assign("MovingImagePyramid", MovingImagePyramid);

	std::vector<std::string> MovingInternalImagePixelType;
	MovingInternalImagePixelType.push_back("float");
	parameter.insert_or_assign("MovingInternalImagePixelType", MovingInternalImagePixelType);

	std::vector<std::string> NewSamplesEveryIteration;
	NewSamplesEveryIteration.push_back("true");
	parameter.insert_or_assign("NewSamplesEveryIteration", NewSamplesEveryIteration);

	std::vector<std::string> NumberOfHistogramBins;
	NumberOfHistogramBins.push_back("32");
	parameter.insert_or_assign("NumberOfHistogramBins", NumberOfHistogramBins);

	std::vector<std::string> NumberOfResolutions;
	NumberOfResolutions.push_back("2");
	parameter.insert_or_assign("NumberOfResolutions", NumberOfResolutions);

	std::vector<std::string> NumberOfSpatialSamples;
	NumberOfSpatialSamples.push_back("2000");
	parameter.insert_or_assign("NumberOfSpatialSamples", NumberOfSpatialSamples);

	std::vector<std::string> Optimizer;
	Optimizer.push_back("AdaptiveStochasticGradientDescent");
	parameter.insert_or_assign("Optimizer", Optimizer);

	std::vector<std::string> Registration;
	Registration.push_back("MultiResolutionRegistration");
	parameter.insert_or_assign("Registration", Registration);

	std::vector<std::string> ResampleInterpolator;
	ResampleInterpolator.push_back("FinalBSplineInterpolator");
	parameter.insert_or_assign("ResampleInterpolator", ResampleInterpolator);

	std::vector<std::string> Resampler;
	Resampler.push_back("DefaultResampler");
	parameter.insert_or_assign("Resampler", Resampler);

	std::vector<std::string> Transform;
	Transform.push_back("BSplineTransform");
	parameter.insert_or_assign("Transform", Transform);

	std::vector<std::string> UseDirectionCosines;
	UseDirectionCosines.push_back("true");
	parameter.insert_or_assign("UseDirectionCosines", UseDirectionCosines);

	std::vector<std::string> WriteResultImage;
	WriteResultImage.push_back("false");
	parameter.insert_or_assign("WriteResultImage", WriteResultImage);

	m_ParameterObject->SetParameterMap(parameter);

	ElastixFilterType::Pointer registration = ElastixFilterType::New();
	registration->SetFixedImage(m_FixedItkImage); // 2D size: 64x64
	registration->SetMovingImage(m_MovingItkImage); // 2D size: 64x64
	registration->SetParameterObject(m_ParameterObject);
	registration->SetNumberOfThreads(1); // also try 12
	registration->SetLogToConsole(false);
	registration->SetLogToFile(false);
	registration->Update();
`
Run in the "Release" version, found that using 1 thread takes 0.6s while using 12 threads takes 4s when using elastix executable "using 1 thread takes 0.9s while using 12 threads takes 0.4s".

I also try the newest elastix4.9 with itk5.0.0, the performance of Elastix libraries and executable are same, very fast.

**Comment by mstaring** [comment]
I understand from your last remark that the issue was not apparent in later versions, so i am closing the issue.
