### ISSUE TITLE
transformix does not transform points

### ISSUE THREAD

**Issue by kyle-pena-nlp** [SuperElastix/elastix#19]
Take a look at the included content.  The points are read as "0 0 0" in all cases, thus we have the same transformed point for every point in Output.

Points File:
[points.txt](https://github.com/SuperElastix/elastix/files/1187622/points.txt)

Output:
[outputpoints.txt](https://github.com/SuperElastix/elastix/files/1187624/outputpoints.txt)

Transform Parameters:
[reg_3DT1_to_FLAIR.txt](https://github.com/SuperElastix/elastix/files/1187627/reg_3DT1_to_FLAIR.txt)

Command:
transformix -out transformix -tp "reg_3DT1_to_FLAIR.txt" -def "transformix/points.txt"

**Comment by kyle-pena-nlp** [comment]
I was being dumb.  My points file was formatted incorrectly.

**Comment by Borda** [comment]
may I ask what is the proper formatting? :)

**Comment by kyle-pena-nlp** [comment]
Dude I have no idea this was 2 years ago
