### ISSUE TITLE
Nonlinear registration stuck forever computing the Jacobian

### ISSUE THREAD

**Issue by alecrimi** [SuperElastix/elastix#199]
Hi all,

I am running a 3-step registration where I generate my own atlas averaging my data. I am using mice brain data acquired sagittally.
Practically, initially I do a rigid registration to the reference Allen atlas, once they are all registered, I campute the average volume, which is then used to register again everything by using first affine and then bspline registration. It s a way of working you can find in several works where not well established brain atlas exists.

Now, everything goes smooth until I register nonlinearly the data. The issue is that the registration for whatever sample gets stuck (days) at "computing the Jacobian". This has happened in two different Linux machines: a Laptop with iCore 7 intel, and a node on a CloudCluster using 32cpu-128ram-hpc (I doubt the issue is related to power).

And it doesn't matter if I do it using the previous steps of registration or I do that directly.
Any idea?

I attach here my param files
[elastix.log](https://github.com/SuperElastix/elastix/files/3767879/elastix.log)
[rigid.txt](https://github.com/SuperElastix/elastix/files/3767880/rigid.txt)
[bspline.txt](https://github.com/SuperElastix/elastix/files/3767881/bspline.txt)
[affine.txt](https://github.com/SuperElastix/elastix/files/3767883/affine.txt)

**Comment by patsch007** [comment]
Hi, 

i run into the same problem.
It seems the "AdaptiveStochasticGradientDescent" uses a Jacobian which is not multi threaded.

As workaround I used another optimizer (Optimizer "StandardGradientDescent").

**Comment by YuchuanQiao** [comment]
@alecrimi  @patsch007  This is because 1) the image is too big, or 2) the number of samples is big for the original ASGD method to calculate Jacobian. You may try my method to accelerate this procedure.
(ASGDParameterEstimationMethod "DisplacementDistribution")
If you want to dig more details, you can find the paper "Qiao, Yuchuan, et al. "Fast automatic step size estimation for gradient descent optimization of image registration." IEEE transactions on medical imaging 35.2 (2015): 391-403."

**Comment by fieres** [comment]
I also observed that, when using the AdaptiveStochasticGradientDescent with default settings and larger images, the vast majority of the total computation time goes into the (single-threaded) parameter estimation ("computing the Jacobian").

Thanks @alecrimi, for your suggestion to use DisplacementDistribution, I'll try it.
