### ISSUE TITLE
Setup continuous integration for Linux and Mac with travis-ci.org

### ISSUE THREAD

**Issue by kaspermarstal** [SuperElastix/elastix#2]

**Comment by mstaring** [comment]
Hi Kasper, it seems to work!
Does travis follow develop or master or both?

**Comment by kaspermarstal** [comment]
It follows both, and whatever new branch or PR you make :)

**Comment by mstaring** [comment]
Great thanks!
Is it ready to be closed?

**Comment by kaspermarstal** [comment]
Yep!
