### ISSUE TITLE
ViolaWellsMutualInformation metric is not working 

### ISSUE THREAD

**Issue by idhamari** [SuperElastix/elastix#200]
Discussion is already [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elastix-imageregistration/ieHG5fNjti0/v_QUbmjgAQAJ)

Elastix version: 5.0.0
Error message:

     Location: "unknown" 
     Components/Registrations/MultiResolutionRegistration/elxMultiResolutionRegistration.hxx
     Line: 137
     Description: itk::ERROR: MultiResolutionRegistration(0x5565d7e91cd0): ERROR: MultiResolutionRegistration expects the metric to be of type AdvancedImageToImageMetric!
itk::ExceptionObject (0x5565d7eacfb0) 
     Errors occurred!

Parameter file is contents:

    (FixedInternalImagePixelType  "short")
    (MovingInternalImagePixelType "short")
    (Registration "MultiResolutionRegistration")
    (NumberOfResolutions 1)
    (UseDirectionCosines "true")
    (ResampleInterpolator "FinalBSplineInterpolator")
    (Resampler "DefaultResampler")
    (Interpolator "LinearInterpolator")
    (Optimizer "AdaptiveStochasticGradientDescent")
    (Transform "EulerTransform")
    (Metric "ViolaWellsMutualInformation")
    (NumberOfHistogramBins 16)
    (MaximumNumberOfIterations 100)
    (MaximumStepLength 1.0)  
    (NumberOfSpatialSamples 3000)
    (NewSamplesEveryIteration "true")  
    (ImageSampler "RandomCoordinate")  
    (ErodeMask "false")
    (AutomaticScalesEstimation "true")  
    (AutomaticTransformInitialization "true")  
    (HowToCombineTransforms "Compose")  
    (RequiredRatioOfValidSamples 0.01) 
    (BSplineInterpolationOrder 1)
    (FinalBSplineInterpolationOrder 0)
    (DefaultPixelValue 0)
    (WriteResultImage "true")
    (ResultImagePixelType "short")
    (ResultImageFormat "nrrd" )

**Comment by idhamari** [comment]
Could someone point me to some steps? or what files are involves?

**Comment by mstaring** [comment]
Please use the Mattes version instead. This component is obsolete
