### ISSUE TITLE
Elastix output folder cannot contain spaces

### ISSUE THREAD

**Issue by fieres** [SuperElastix/elastix#201]
In Linux, call elastix with an output folder containing spaces (windows: not tested).
$ elastix -f blabla -m blabla -p blabla -out ’some directory with spaces/output’ 

=> Elastix issues an error saying that the directory "some\ directory\ with\ spaces/output/" cannot be found (note the escape-style backslashes in the error message). 

The root cause seems to be that in Core/Main/elastix.cxx, the commandline option for "-out" is processed via itksys::SystemTools::ConvertToOutputPath. According to the docs, this function escapes spaces "for use in makefiles". In fact, the escaping corrupts the path for accessing it via the file system.

A fix is appreciated because we need to use application-provided temporary folders as working directory (which can contain spaces). We don't have control over the naming of those folders.

**Comment by idhamari** [comment]
Some workaround can be done by a script e.g. python. The idea is to copy your files to a temporary valid path:

    input: your  path (with spaces) 
   output: a new path (without spaces).
  
In the script you create the new folder and copy the contents of the input folder then use this new folder with elastix.

**Comment by oliwe** [comment]
I am using elastix (precompiled version) on windows 10.
I hat no issues with version 4.8.
But after upgrading to  elastix 5.0 I had also problems with the output folder defined via -out parameter in the elastix call.
Spaces work but special characters like 'ü' do not work.
e.g. "E:\ImageData\München\Baseline\exp 1.0 b60
fails but
"E:\ImageData\Berlin\Baseline\exp 1.0 b60"
Also transformix has problems with special characters now.
We have elastix integrated in a fully automated workflow - paths include city names and patient names - so we had to jump back to version 4.8 .

**Comment by idhamari** [comment]
The same workaround above should work with special characters as well.

**Comment by fieres** [comment]
@idhamari: Thanks for proposing a workaround. However, renaming the folders, or copying the files to a temporary folder, is sometimes not possible or  not desired. As I explained in the original post, we are relying on a framework telling us the location of the working directory (the framework ensures that this is a fast, local disk with sufficient space). oliwe is obviously using an automated framework they don't want to (or can not) change.

BTW: I was using v. 4.9.

**Comment by oliwe** [comment]
@idhamari
Thanks for the workaround, but it is not an option for us.

@fieres
We started using elastix with version 4.8 - that was a very good/stable version.
elastix is really a good and easy to use registration package. 
Then we tried 4.9 - but this version suffered from a performance regression (see https://github.com/SuperElastix/elastix/releases/tag/5.0.0, Bug fixes) - so we jumped back to 4.8.
In 4.8 there are not problems with spaces or special characters - at least on win 10.
Maybe you should give 4.8 a try and wait for a bug fix release or you could try to fix the problem by your own?

**Comment by mstaring** [comment]
We rely on ITK and ITK on KWSys to provide this functionality. I would submit a minimal example that works as intended with a previous version of ITK/kwsys and does not work anymore with a new version. 

This example should be send to the ITK people or to kwsys directly. When they accept a patch, this will at some point also flow back to elastix.

**Comment by fieres** [comment]
Hi @mstaring,

maybe I don't understand 'We rely on ITK and ITK on KWSys to provide this functionality', because I don't know what KWSys is.

As far as I read the code, elastix does rely on itk functionality to escape spaces in the file path. (As I wrote in my original post, elastix calls itksys::SystemTools::ConvertToOutputPath). The file path is meant to be passed later to c/c++ functions to open a file stream. You cannot expect this to work with escaped spaces. My point was that the mistake is on the elastix side, not the itk side. elastix must not call the said itk functionality on the file path at all if the file path is later used for opening a file. 

Elastix might have its reasons to escape the file name (which are obscure to me). The only thing I know that only un-escaped file names will work for opening a file.

The problem is for us not relevant at the moment because we are transitioning to using a library integration. If I find some time, I will however prepare a reproducing example.

**Comment by mstaring** [comment]
Yes, the  itksys::SystemTools::ConvertToOutputPath function is provided by the kwsys library integrated in ITK. 

But you say we don't need the function at all. I'm not sure why I thought we needed it, as this was coded many years ago. If you provide some example/testing code, perhaps @N-Dekker could have a look at this?

**Comment by fieres** [comment]
This problem is keeping annoying us. We would be happy if one of @mstaring or @N-Dekker could look into it.

Please see the attached reproducing elastix project (see README.txt in the zip), and the suggested patch.

The problem can be reproduced only under Linux or Mac (you have already windows-specific bug-fixing code in place; see details below).

My suggestion is to remove using the function itksys::SystemTools::ConvertToOutputPath. I cannot imagine why it should be used here.

Note that @mstaring has already added code that explicitly reverts the effect of ConvertToCoutputPath (commit 9274c3f1c). I guess that this was an attempt to fix this bug. Can you remember why you did not delete the call to ConvertToCoutputPath  altogether? However, your fix does not work under Linux. Under windows, ConvertToOutputPath adds quotes around the path name, under Linux, it escapes spaces using backslashes.


[TestProjectAndPatch.zip](https://github.com/SuperElastix/elastix/files/6130960/TestProjectAndPatch.zip)

**Comment by N-Dekker** [comment]
@mstaring My guess is that you called this function `itksys::SystemTools::ConvertToOutputPath`, only just to ensure that the path has the right (OS specific) path separators. I _think_ removal of "double slashes" was not your aim. Right?

If so I guess we need a helper function like Qt's `toNativeSeparators(pathName)`: https://doc.qt.io/qt-5/qdir.html#toNativeSeparators instead.

**Comment by N-Dekker** [comment]
@oliwe
You wrote at https://github.com/SuperElastix/elastix/issues/201#issuecomment-547846116
> I am using elastix (precompiled version) on windows 10.
> I hat no issues with version 4.8.
> But after upgrading to elastix 5.0 I had also problems with the output folder defined via -out parameter in the elastix call.
> Spaces work but special characters like 'ü' do not work.
> e.g. "E:\ImageData\München\Baseline\exp 1.0 b60
> fails but
> "E:\ImageData\Berlin\Baseline\exp 1.0 b60"
> works.
> Also transformix has problems with special characters now.
> We have elastix integrated in a fully automated workflow - paths include city names and patient names - so we had to jump back to version 4.8 .

Thank you for your comments. It seems to me that the problem you describe is a different issue, though. (Unrelated to the issue regarding spaces in folder names.) It could be caused by the fact that elastix only supports 8-bit character strings as directory path names. Which means that it depends on the selected "locale" to decode those path names. When the selected locale does not support umlaut, elastix might not correctly interpret a path name that has an umlaut.

Nowadays, Windows 10 has an option "Beta: Use Unicode UTF-8 for worldwide language support". It seems to me that this option might solve the umlaut problem. Do you have this option enabled?
