### ISSUE TITLE
Elastix 5.0 does not support shared libaray?

### ISSUE THREAD

**Issue by colddie** [SuperElastix/elastix#202]
HI,

I was trying to build the shared library for the latest version. But I found the following lines. Do they mean shared library feature is not supported anymore?

cmake_minimum_required( VERSION 2.8 )
project( elastix )
set(CMAKE_CXX_STANDARD 11)

if( BUILD_SHARED_LIBS )
  message(FATAL_ERROR "Elastix does not support BUILD_SHARED_LIBS")
endif()

**Comment by idhamari** [comment]
Could someone point me to some steps? or what files are involves?

**Comment by N-Dekker** [comment]
@colddie Hi Tao Sun,

Indeed, Elastix 5.0 prevents building a shared Elastix library (DLL). It appeared problematic, see pull request https://github.com/SuperElastix/elastix/pull/184

Is it OK to you to build Elastix 5.0 as a static (non-shared) library?

Kind regards, Niels
