### ISSUE TITLE
Incorrect results using transformix on VTK file

### ISSUE THREAD

**Issue by hbraunDSP** [SuperElastix/elastix#207]
I am using Elastix to transform a 3d model in .vtk format, and it appears to be giving incorrect results when applied on a point set using transformix, relative to the same transform applied to an image. I am using Elastix 5.0.0 compiled from source on RHEL 7. See the following screenshot from Slicer:
![image](https://user-images.githubusercontent.com/7003848/68602935-e436d800-046c-11ea-9d89-08aa17de288e.png)

The red model is in the original un-transformed location; the original image used for segmentation is not shown but is in the same position.  The blue model and the image have both had the same transform applied to them using transformix and should be aligned with each other.  They are clearly not aligned, however. It looks like transformix may have the axes out of order relative to how they are stored in the vtk file.

**Comment by GreateLi** [comment]
@hbraunDSP  Did you solve it? I have the same problem, need to solve

**Comment by hbraunDSP** [comment]
@GreateLi Unfortunately, no.  For my use case I was able to import both the untransformed model and the transform into slicer, and apply the transform there.

**Comment by GreateLi** [comment]
&nbsp;
  

 &nbsp;Thanks for your reply. I've got it. The bottom layer is encapsulated to the itk conversion input parameters, I can give vtk.

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人: "SuperElastix/elastix" <notifications@github.com&gt;;
 发送时间:&nbsp;2020年8月29日(星期六) 凌晨2:51
 收件人:&nbsp;"SuperElastix/elastix"<elastix@noreply.github.com&gt;;
 抄送:&nbsp;"GreateLi"<liguoqing2003@hotmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [SuperElastix/elastix] Incorrect results using transformix on VTK file (#207)

 

 

 
@GreateLi Unfortunately, no. For my use case I was able to import both the untransformed model and the transform into slicer, and apply the transform there.

**Comment by ViktorvdValk** [comment]
Hi @hbraunDSP and @GreateLi, 
Could one of you share code, images and vtk file,  so I could try to reproduce your problem?
And did you use the slicer plugin for transformation or did you only use slicer for visualization?

**Comment by ViktorvdValk** [comment]
Hi @hbraunDSP, thanks for raising the issue, I'm closing it for now. Feel free to reopen it, when you find that this issue is not fixed in the newest release of elastix.
