### ISSUE TITLE
bin folder missing in elastix 5.0.0 for Mac

### ISSUE THREAD

**Issue by juan-d** [SuperElastix/elastix#212]
Hello,

I downloaded elastix 5.0.0 for Mac (elastix-5.0.0-mac.tar.gz) but the release seems to be missing the bin folder. After unzipping, the contents of the elastix folder are the executables elastix and transformix and the lib folder, but there is no bin folder.

Could you please clarify this issue?

Many thanks,

Juan

**Comment by N-Dekker** [comment]
@juan-d Hello Juan,

Thanks for reporting this issue to us! I just uploaded a new "elastix-5.0.0-mac.tar.gz" file. Can you please download it again, and tell us if it fixes the issue? https://github.com/SuperElastix/elastix/releases

**Comment by juan-d** [comment]
Hi Niels,

Apologies for the slow reply. This fixed the issue and it's now working smoothly!

Many thanks.

Juan
