### ISSUE TITLE
Cannot compile on win 32 platform

### ISSUE THREAD

**Issue by fieres** [SuperElastix/elastix#215]
The error is:

`
common\imagesamplers\itkImageToVectorContainerFilter.hxx(231): error C2664: cannot convert argument 1 from 'itk::ITK_THREAD_RETURN_TYPE (__cdecl *)(void *)' to 'itk::ThreadFunctionType'
`

Looking at the code, this error makes sense. The `itk::ThreadFunctionType` is declared as `__stdcall` (see `InsightToolkit-5.0.1/Modules/Core/Common/include/itkThreadSupport.h:62`). This cannot be cast to a `__cdecl` function.

**Comment by albertelonjobs** [comment]
I got the similar error as below. I'm using ITK 5.0.1 and Visual Studio 2017. Does it work on other Windows platform?
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'void itk::MultiThreaderBase::SetSingleMethod(itk::ThreadFunctionType,void *)': cannot convert argument 1 from 'itk::ITK_THREAD_RETURN_TYPE (__cdecl *)(void *)' to 'itk::ThreadFunctionType'	SumSquaredTissueVolumeDifferenceMetric	source\elastix\common\imagesamplers\itkImageToVectorContainerFilter.hxx	231

**Comment by N-Dekker** [comment]
@fieres @albertelonjobs Thanks you for reporting this issue! While we do not actively support 32-bit Windows compilation of Elastix anymore (as I discussed with Marius @mstaring), we do appreciate the fix by Andrey Saenko (@highemhigh); we think Andrey's pull request #216 is fine.
