### ISSUE TITLE
the "Origin" precision in TransformParameters is not high enough

### ISSUE THREAD

**Issue by GouZi2019** [SuperElastix/elastix#217]
I found an interesting problem:

I perform registration using Elastix and get a warped image called "result.0.nrrd"
then I use ITK to read the fixed image and warped image and compare the origins of them. Apparently, the origins are the same.
But, when I call "Transformix" to transform the moving image, the origin of the warped image called "result.nrrd" is not equal to the fixed image's:
origin of the fixed image in x-direction: -192.26322937011719 mm
origin of the "result.nrrd" in x-direction: -192.26322937009999 mm

The reason for this difference is that **the "Origin" precision in TransformParameters is not high enough**:
(Origin -192.2632293701 ...
The difference of origin will cause ITK cannot pass the _VerifyInputInformation_ function: "Inputs do not occupy the same physical space! " So all the inheritance from itkImagetoImageFilter will fail.

My approach is to take a _itkChangeImageInformation_ first. Is there a better way to solve this problem in Elastix?

**Comment by GouZi2019** [comment]
I modified the "elxTransformBase.hxx". The problem was solved.

**Comment by N-Dekker** [comment]
@GouZi2019 Thank you for reporting this issue. Can you please tell us how you modified "elxTransformBase.hxx"? If you still remember  😺 Did you possibly try `std::numeric_limits<double>::max_digits10` as floating point precision?
