### ISSUE TITLE
Error building elastix 5.0 with open cl support on Win 10 (VS 2019)

### ISSUE THREAD

**Issue by MarHHM** [SuperElastix/elastix#219]
Hi all..

after building ITK 5.1 (win 10 - VS 2019 - x64 - nVidia GTX 980 Ti with the SDK installed) with ITK_USE_GPU deselected as advised because elastix replaces it, i tried to build elastix 5.0 with open cl support, but in visual studio it was giving me the following errors (many are the same):

Code | Description | Project | File
-- | -- | -- | --
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineDerivativeKernelFunctionTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkAccumulateDerivativesParallellizationTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineInterpolationDerivativeWeightFunctionTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkAdvanceOneStepParallellizationTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineSODerivativeKernelFunctionTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineInterpolationSODerivativeWeightFunctionTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineTransformPointPerformanceTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineJacobianGradientPerformanceTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkBSplineInterpolationWeightFunctionTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkAdvancedLinearInterpolatorTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkAdvancedRecursiveBSplineTransformTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkOpenCLDeviceTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkOpenCLKernelTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkCompareCompositeTransformsTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkOpenCLProfilingTimeProbeTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkOpenCLStringUtilsTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkThinPlateSplineTransformTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkMevisDicomTiffImageIOTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkThinPlateSplineTransformPerformanceTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\elxOpenCL.lib' | itkAdvancedBSplineDeformableTransformTest | C:\Elastix-build\Testing\LINK
LNK1181 | cannot open input file '..\bin\Release\OpenCLFixedGenericPyramid-5.0.lib' | elastix | C:\Elastix-build\Core\LINK
LNK1181 | cannot open input file '..\bin\Release\OpenCLFixedGenericPyramid-5.0.lib' | transformix | C:\Elastix-build\Core\LINK
C2061 | syntax error: identifier 'PriorityLevelType' | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | OpenCLMovingGenericPyramid | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | OpenCLFixedGenericPyramid | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | OpenCLResampler | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUBSplineDecompositionImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUFactoriesTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUCastImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUGenericMultiResolutionPyramidImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPURecursiveGaussianImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUResampleImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUSmoothingRecursiveGaussianImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkGPUShrinkImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLContextTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLImageTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLEventTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLKernelToImageBridgeTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLKernelManagerTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLPlatformTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLSamplerTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLSimpleTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLSizeTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLVectorTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2061 | syntax error: identifier 'PriorityLevelType' | itkOpenCLBufferTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C2065 | 'PriorityLevelType': undeclared identifier | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.cxx
C2143 | syntax error: missing ';' before '{' | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.cxx
C2146 | syntax error: missing ')' before identifier 'level' | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.cxx
C2447 | '{': missing function header (old-style formal list?) | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.cxx
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | elxOpenCL | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | OpenCLMovingGenericPyramid | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | OpenCLFixedGenericPyramid | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | OpenCLResampler | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUBSplineDecompositionImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUFactoriesTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUCastImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUGenericMultiResolutionPyramidImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPURecursiveGaussianImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUResampleImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUSmoothingRecursiveGaussianImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkGPUShrinkImageFilterTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLContextTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLImageTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLEventTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLKernelToImageBridgeTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLKernelManagerTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLPlatformTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLSamplerTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLSimpleTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLSizeTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLVectorTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h
C3668 | 'itk::OpenCLLogger::Write': method with override specifier 'override' did   not override any base class methods | itkOpenCLBufferTest | C:\Elastix\Common\OpenCL\ITKimprovements\itkOpenCLLogger.h

I think the main issue is complaining about `"PriorityLevelType` being undefined in `itkOpenCLLogger.h`..

these are links for the cmake cache of both configurations ([ITK](https://drive.google.com/file/d/1t_ukWesgdgmJNvwECNVnfk_vqTY78crg/view) & [elastix](https://drive.google.com/file/d/1I1b6U0SYJpMI-NHIsM3ISHLYs7_sd6RF/view))

I would be grateful if anyone could help :)

**Comment by mstaring** [comment]
We currently have no support to fix issues with the OpenCL functionality within elastix.

**Comment by N-Dekker** [comment]
@MarHHM Thanks for reporting this issue, Marwan.

You wrote:
> I think the main issue is complaining about "PriorityLevelType being undefined in itkOpenCLLogger.h..

I think the problem was that elastix 5.0.0 was not yet compatible with ITK 5.1 It should be fixed with elastix version 5.0.1 https://github.com/SuperElastix/elastix/releases/tag/5.0.1 (5 October 2020)

Specifically: "COMP: Fix ITK 5.1 compatibility for OpenCL based functionality" pull request #276 commit cc5aa50e12137f7f845e9e606f603b69afb53714

I'm closing the issue now. Hope it is solved for you!
