### ISSUE TITLE
Incorrect paths to KNN in elxCommon_INCLUDE_DIRECTORIES

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#22]
https://github.com/SuperElastix/elastix/blob/develop/CMakeLists.txt#L208 says:
> set( elxCommon_INCLUDE_DIRECTORIES
...
>   ${elastix_SOURCE_DIR}/Common/KNN
>   ${elastix_SOURCE_DIR}/Common/KNN/ann_1.1/include

These two paths are no longer there. Can they simply be removed from elxCommon_INCLUDE_DIRECTORIES?

The issue was found by CppCheck http://cppcheck.sourceforge.net which says, "Couldn't find path given by -I '...\Elastix\Common\KNN\'.

By the way, KNN is currently located at elastix/Components/Metrics/KNNGraphAlphaMutualInformation

**Comment by mstaring** [comment]
Hi Niels, I think these lines can be simply removed as the directories are properly included at the new location of the KNN files.
Can you create a PR?

**Comment by mstaring** [comment]
fixed by fc13390996881f54d3477d5a035bde74484a34e6
