### ISSUE TITLE
Serious compiler warning for uint8 image data types

### ISSUE THREAD

**Issue by fieres** [SuperElastix/elastix#222]
I am trying to bring the memory consumption to a minimum. Therefore I am compiling elastix with internal image formats “unsigned short” and “unsigned char”. In the Core/Install/CMakeLists.txt they are mentioned as “supported”.

However, I get a worrying warning:

elastix/Components/Transforms/AdvancedAffineTransform/itkCenteredTransformInitializer2.hxx:55:44: warning: implicit conversion
      from 'int' to 'itk::CenteredTransformInitializer2<itk::AdvancedMatrixOffsetTransformBase<double, 3, 3>, itk::Image<unsigned char, 3>, itk::Image<unsigned char, 3>
      >::InputPixelType' (aka 'unsigned char') changes value from 500 to 244 [-Wconstant-conversion]
  this->m_LowerThresholdForCenterGravity = 500;

My questions:
- Will elastix work with data types other than float?
- Would there be any data-type independent way to initialize this variable?

**Comment by mstaring** [comment]
We regularly compile with float and short types on the CI, but not other types. So these are the only actually supported types I'm afraid.
