### ISSUE TITLE
Maintain Docker container Elastix/SimpleElastix Python binding

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#225]
Agah (@agahkarakuzu) did a great job, creating a Dockerfile to run Elastix/SimpleElastix in Python, during the OpenMR Benelux 2020 conference.

Marius @mstaring, Stefan @stefanklein and I agreed that such a Dockerfile should be maintained, preferably on an "elastix" account, to ensure that it remains available and up-to-date.

**Comment by mstaring** [comment]
Since we did not do it yet, and since we now have pypi for ITKElastix, should we simply close this issue?

**Comment by mstaring** [comment]
fixed by https://github.com/SuperElastix/elastix/commit/b65034e96d01eb93b82290058f9d6b44dbe5d9ef
