### ISSUE TITLE
Computing Identity Transform and Exact Metric

### ISSUE THREAD

**Issue by JoshuaHess12** [SuperElastix/elastix#229]
Hi,

I am trying to use command line elastix to compute the exact metric (Mutual information) between two images of equal size by only applying an identity transform to the moving image. I can't seem to find a transformation for the identity transform, so I am posting to ask if there is any easy workaround for this. Any help is appreciated.

Josh

**Comment by mstaring** [comment]
What if you set the number of iterations to 0 or 1 and the sampler to FullSampler?
