### ISSUE TITLE
Some missing figures in documentation

### ISSUE THREAD

**Issue by idhamari** [SuperElastix/elastix#233]
Some images from online documentation are missing as shown here:

![Screenshot from 2020-03-08 10-22-10](https://user-images.githubusercontent.com/28802516/76160135-a2225800-6127-11ea-98d3-1710b1ffbc8c.png)

I tried to build the documentation locally but it didn't work. The build documentation is activated in cmake

      $ make doxygen
       make: *** No rule to make target 'doxygen'.  Stop.

**Comment by idhamari** [comment]
How can I build the documentation?

**Comment by N-Dekker** [comment]
@idhamari Thank you for reporting this issue.

For the record, this specific doxygen output is now located at https://elastix.lumc.nl/doxygen/classelastix_1_1AdaptiveStochasticGradientDescent.html   But I see, it still isn't processed entirely correctly.

**Comment by N-Dekker** [comment]
@idhamari 
> How can I build the documentation?

You start by elastix CMake option `BUILD_DOCUMENTATION` = `ON`.

When you then do CMake configure, it will create a file named "doxyfile.out", in `<elastix-build-directory>/help`.  That's the file that you should pass to the Doxygen executable.

HTH, Niels

**Comment by idhamari** [comment]
@N-Dekker Thanks, it works. It would be nice to add this to the build instructions.

**Comment by N-Dekker** [comment]
@idhamari You're welcome. I'll check where the elastix `BUILD_DOCUMENTATION` option could be documented!

So do you see the LaTeX figures now that you were missing? I haven't yet seen them myself! (I'm still trying to figure out how to install LaTeX with Doxygen, running on Windows 10.) Which OS are you on, if I may ask?

**Comment by idhamari** [comment]
> So do you see the LaTeX figures now that you were missing? I haven't yet seen them myself! (I'm still trying to figure out how to install LaTeX with Doxygen, running on Windows 10.)
Yes, I had to install graphviz to get the png images, check the figures below:

Online documentation:

![Screenshot from 2021-06-09 14-56-42](https://user-images.githubusercontent.com/28802516/121359029-5e725b80-c933-11eb-9f65-dedfd941e1e0.png)

Local documentation:

![Screenshot from 2021-06-09 14-57-07](https://user-images.githubusercontent.com/28802516/121359074-6af6b400-c933-11eb-8a7d-8a2bd525791e.png)


> Which OS are you on, if I may ask?

Linux Ubuntu 18.04

**Comment by N-Dekker** [comment]
I wrote at https://github.com/SuperElastix/elastix/issues/233#issuecomment-857641358
> (I'm still trying to figure out how to install LaTeX with Doxygen, running on Windows 10.)

For the record, I was using MiKTeX, and I ran Doxygen as follows:

    set path=C:\path-to-programs\MiKTeX\miktex\bin\x64
    call "C:\Program Files\doxygen\bin\doxywizard.exe" 

Then Doxygen could not find gswin32c.exe, the Ghostscript executable for Windows. As a quick-fix, it appears that I could just rename the file "mgs.exe" from  miktex\bin\x64 to "gswin32c.exe", and then rerun Doxygen!

As clarified by https://miktex.org/packages/miktex-ghostscript-bin
> Ghostscript is a freely available PostScript interpreter which is available for many platforms. It is a near-essential complement to a TeX installation. The Ghostscript executable of the MiKTeX for Windows distribution has been renamed to mgs.exe and therefore does not interfere with any official Ghostscript installation (gswin32c.exe).

Now I finally got those missing figures back as well 😃
