### ISSUE TITLE
Probably a bug: vnl_math_max in elxPreconditionedGradientDescent

### ISSUE THREAD

**Issue by idhamari** [SuperElastix/elastix#234]
In [elxPreconditionedGradientDescent.hxx](https://github.com/SuperElastix/elastix/blob/develop/Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx). Lines [517](https://github.com/SuperElastix/elastix/blob/633c68425dd3433450938ec54423ef8906b2ce3e/Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx#L517) and [538](https://github.com/SuperElastix/elastix/blob/633c68425dd3433450938ec54423ef8906b2ce3e/Components/Optimizers/PreconditionedGradientDescent/elxPreconditionedGradientDescent.hxx#L538)

In [itkPreconditionedGradientDescentOptimizer](https://github.com/SuperElastix/elastix/blob/develop/Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx). Line [401](https://github.com/SuperElastix/elastix/blob/633c68425dd3433450938ec54423ef8906b2ce3e/Components/Optimizers/PreconditionedGradientDescent/itkPreconditionedGradientDescentOptimizer.cxx#L401)

In [itkAdaptiveStochasticPreconditionedGradientDescentOptimizer_cxx](https://github.com/SuperElastix/elastix/blob/develop/Components/Optimizers/PreconditionedGradientDescent/itkAdaptiveStochasticPreconditionedGradientDescentOptimizer.cxx) Line [70](https://github.com/SuperElastix/elastix/blob/633c68425dd3433450938ec54423ef8906b2ce3e/Components/Optimizers/PreconditionedGradientDescent/itkAdaptiveStochasticPreconditionedGradientDescentOptimizer.cxx#L70)

I got an error when compiling in Linux.I changed the function from

       vnl_math_max

to 
      
       std::max 

this solves the compilation error.

**Comment by mstaring** [comment]
@N-Dekker Hi Niels, there seem to be a few remnants of vnl functions that can quite easily be replaced by their std counterparts.

**Comment by N-Dekker** [comment]
@mstaring Marius, it appears to me that these obsolete `vnl_math_max` calls are all in a component which is switched off by default: `USE_PreconditionedGradientDescent`. It is even switched off when `USE_ALL_COMPONENTS` is ON. Is that intended?

Anyway, I'll try to fix it by replacing those `vnl_math_max` calls, no problem 😃  @idhamari Thanks for reporting this issue, Ibraheem!

**Comment by mstaring** [comment]
THe expected behaviour of USE_ALL_COMPONENTS is that it is switched on.

**Comment by mstaring** [comment]
Ah, I understand now, this component depends on the presence of SUITE_SPARSE

**Comment by N-Dekker** [comment]
Thanks, I'll try to compile the module with the latest release from  https://github.com/DrTimothyAldenDavis/SuiteSparse/releases OK?

**Comment by mstaring** [comment]
or could we just replace them without compilation, as it is so trivial? Would save a lot of time...


________________________________

**Comment by N-Dekker** [comment]
@mstaring @idhamari I would have liked to try to build `PreconditionedGradientDescent` to see if pull request #290 really fixes the problem, but I could not figure out how to get it configures with the SuiteSparse library and its dependencies. Hope you can give it a try!

**Comment by idhamari** [comment]
@N-Dekker thanks for your effort, I rebuild elastix from PR #290 and everything seems to work.
