### ISSUE TITLE
How to use the transform of MultiBSplineTransformWithNormal

### ISSUE THREAD

**Issue by congyang1996** [SuperElastix/elastix#235]
Hi, could anyone help me about the use of (Transform "**MultiBSplineTransformWithNorma**l")?
I try to use transform of (Transform "MultiBSplineTransformWithNormal"), to fix a **sliding motion registration**. At elastix's parameter database, the param0016 example used this transform, which should provide a label image to figure out the two different sliding object in fix image. But the author's label files are unable to get.

I used ITK-snap to segment a 0/1 label image of a sliding object, and the command I use is:
_elastix -f fixImage.nii -fMask fixMask.nii -labels fixBladder.nii -m movingImage.nii -out c:/Users/yc/elastix/output -p param-affine.txt -p param-bspline-multi.txt_

But I got an error when running:
> itk::ERROR: IsoContourDistanceImageFilter(000002004EBFB380): Gradient norm is lower than pixel precision

Someone said that's because you should use float pixel type, not short. But what I used is excatly float. So, what's the problem? I also remove the fixMask image to see if it is because the fix mask and fix label are conflicting, but this error still occur. Could anyone give some advice? Thanks a lot!

**Comment by congyang1996** [comment]
It seems to be a version problem. The implement from paper's author about sliding motion registration use a 4.6 version, but I use 5.0 version. However, when I try to download a 4.6 binaries from [offical website](http://elastix.isi.uu.nl/download_links.php), it just show a thanks page, but download nothing. Could anyone help me to get a 4.6 version? Thanks a lot.

**Comment by mstaring** [comment]
it should be downloadable at the new website

**Comment by mstaring** [comment]
In addition, perhaps the original author may be able to help you on how to use this component: http://dx.doi.org/10.1088/0031-9155/58/5/1303
