### ISSUE TITLE
Is AffineTransform and other Linear Transform matrix elements in (TransformParameters) specified in row-major ordering?

### ISSUE THREAD

**Issue by stevenjwest** [SuperElastix/elastix#237]
I have been trying to figure out whether the 12 (TransformParameters) output values by elastix registration when using AffineTransform (for a 3D image) specifies the 3x3 linear transformation matrix in row-major or column-major order.

For example, does the following output:

`(Transform "AffineTransform")`
`(NumberOfParameters 12)`
`(TransformParameters 1.016269 0.034835 0.018910 -0.034048 0.902209 -0.211435 -0.058102 0.154742 0.949543 -4.378274 -16.865117 11.892792)`

specify a 3x3 transformation matrix in row-major:

` 1.016269  0.034835  0.018910` 
`-0.034048 0.902209 -0.211435`
`-0.058102  0.154742  0.949543`

or column-major:

`1.016269 -0.034048 -0.058102`
`0.034048 0.902209  0.154742`
`0.018910 -0.211435  0.949543`

I am trying to decompose a 3D linear transformation matrix into scaling and x-rotation, y-rotation, z-rotation matrices, but clearly the validity of these results will depend on me reading the linear transformation matrix in the correct order!

I have found documentation on the base class - AdvancedMatrixOffsetTransformBase - http://elastix.isi.uu.nl/doxygen/classitk_1_1AdvancedMatrixOffsetTransformBase.html - and this suggests it might be row-major:

> This class provides several methods for setting the matrix and offset defining the transform. To support the registration framework, the transform parameters can also be set as an Array<double> of size (NInputDimension + 1) * NOutputDimension using method SetParameters(). The first (NOutputDimension x NInputDimension) parameters defines the matrix in **row-major order (where the column index varies the fastest)**. The last NOutputDimension parameters defines the translation in each dimensions.

However, this does not make clear in what order the output given in (TransformParameters) is in the TransformParameters.txt file following elastix registration with an AffineTransform.  The manual (section 2.6) is also vague here, as [i,j] could specify either row-major or column-major.

Any help clarifying this would be greatly appreciated!

**Comment by Bartolomejka** [comment]
Hi!
It is stored there in a strange way. The first 9 parameters is the rotation matrix (3 x 3 rows) and the resting 3 params are the shift, i.e. last column of the matrix in homogeneous coordinates (in case you append the last row to it manually [0 0 0 1]). See this matlab code (and the link):
```
aff_vector= [0.995162 -0.005400 0.000000 0.007553 0.999311 0.000000 0.000000 -0.000000 1.000000 3.061066 5.627383 -0.000000]; % a copy from transform file

transform_lps=[[reshape(aff_vector(1:9),3,3)' aff_vector(10:12)']; 0 0 0 1]; % from Slicer to Matlab bridge: (https://github.com/PerkLab/SlicerMatlabBridge/blob/f7d4511ffe9424e827362942beccb29c7007b526/MatlabCommander/commandserver/cli_lineartransformread.m#L25-L30)
```
transform_lps =

    0.9952   -0.0054         0    3.0611
    0.0076    0.9993         0    5.6274
         0         0        1.0000         0
         0         0                0    1.0000

**Comment by stevenjwest** [comment]
Hi @Bartolomejka - thanks for your reply!

OK so it is specified in row-major order then -  that's great, thanks.  I actually took some time to empirically determine this, so thanks for confirming it for me (and future users!).

All the best, Steve.
