### ISSUE TITLE
Groupwise MI metric - "PCA-based groupwise image registration for quantitative MRI"

### ISSUE THREAD

**Issue by felixvh** [SuperElastix/elastix#242]
I have read the article “PCA-based groupwise image registration for quantitative MRI“. For my project, I am using the groupwise registration approach. For a comparison, I would like to use the groupwise mutual information metric that has been used in the above mentioned article (https://doi.org/10.1016/j.media.2015.12.004). However, it is not implemented in the current elastix version, nor am I able to build it with Cmake. Could anyone tell me where to find it or could somebody provide me the corresponding exe file?

**Comment by mstaring** [comment]
@stefanklein is this implemented in the develop branch?

**Comment by felixvh** [comment]
I am doing my final evaluations ATM, it would be great if I can use this metric aswell!

**Comment by stefanklein** [comment]
Hi, thanks for your interest in this method. It's in the Master actually. It's called PCAMetric. Isn't it available in the release binaries? Cheers, Stefan

**Comment by felixvh** [comment]
I was trying to use "LinearGroupwiseMI" as a metric. This is a different one than the "PCAmetric", isn't it?

So when I try to run it, I get the following error:

Error: 
LinearGroupwiseMI(index 4) - This component is not installed!

**Comment by stefanklein** [comment]
yes LinearGroupwiseMI is a different metric, which was probably developed by @MathiasPolfliet .  Is that right Mathias? @felixvh , so does the PCAMetric work for you?
best, stefan

**Comment by felixvh** [comment]
Yea, the PCAmetric works perfectly fine! For this one I also do have the results.

**Comment by bjeurissen** [comment]
I tried running

```
elastix -f input.nii -m input.nii -p config.txt -out output
```

with ``config.txt`` obtained from https://raw.githubusercontent.com/SuperElastix/ElastixModelZoo/master/models/Par0039/par_groupwise/par_real_data/par_groupwise_DTI-BRAIN.txt

I tried a few different versions (including 4.8 and 5.0.1) of both the Linux and MacOS binaries, but I always get this error:

```
Running elastix with parameter file 0: "config.txt".

Current time: Wed Apr  7 12:05:06 2021.
Reading the elastix parameters from file ...

Installing all components.
InstallingComponents was successful.

ERROR:
  FixedImageType:  4D float
  MovingImageType: 4D float
  elastix was not compiled with this combination of ImageTypes!
  You have two options to solve this:
  1. Add the combination to the CMake parameters ELASTIX_IMAGE_nD_PIXELTYPES and ELASTIX_IMAGE_DIMENSIONS, re-cmake and re-compile.
  2. Change the parameters FixedInternalImagePixelType and/or MovingInternalImagePixelType in the elastix parameter file.

ERROR:
Something went wrong in the ComponentDatabase
Errors occurred!
```

Does this mean I have to build elastix from source in order to be able to use the PCA-based groupwise image registration?

**Comment by stefanklein** [comment]
Hi Ben,
If you change these lines
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
To
(FixedInternalImagePixelType "short")
(MovingInternalImagePixelType "short")
It should work without recompilation. Just make sure that the intensity range of your input images is well represented by a signed 16bit integer. (so don't use floating point images scaled between 0 and 1 for example).
The altnerative is to recompile with the correct settings indeed.
Best, Stefan

**Comment by N-Dekker** [comment]
Thanks for reporting. I assume that this issue is addressed by the reply of @stefanklein at https://github.com/SuperElastix/elastix/issues/242#issuecomment-816665028 so I'll close it. Please reopen if you think otherwise.
