### ISSUE TITLE
Yes it does, if you mean with 2D-3D projection data to volume. Please see the parameter files here: http://elastix.bigr.nl/wiki/index.php/Par0013

### ISSUE THREAD

**Issue by Iamlearn** [SuperElastix/elastix#244]
Yes it does, if you mean with 2D-3D projection data to volume. Please see the parameter files here: http://elastix.bigr.nl/wiki/index.php/Par0013

_Originally posted by @mstaring in https://github.com/SuperElastix/elastix/issues/208#issuecomment-559545223_

Hai, the website you gave cannot be accessed. What should I do?

**Comment by mstaring** [comment]
I think it was a temporary fluke
