### ISSUE TITLE
two x-ray registration with CT

### ISSUE THREAD

**Issue by endlessric** [SuperElastix/elastix#250]
Dear elastix user:
I use the parameter of "Media:par0013Powell_NGC_twoImages.txt",
and find out the example set the parameter (UseDirectionCosines "false"),
which cause the output direction as (Direction 1.0000000000 0.0000000000 0.0000000000 0.0000000000 1.0000000000 0.0000000000 0.0000000000 0.0000000000 1.0000000000).
Looks like two of the x-ray image is in the same direction ?

Is it possible to set two x-ray image in the different direction ?

**Comment by timeanddoctor** [comment]
Did you have the answer?

**Comment by YuchuanQiao** [comment]
you can set it to true: (UseDirectionCosines "true")

**Comment by timeanddoctor** [comment]
> you can set it to true: (UseDirectionCosines "true")
Thank you.
And I have another problem which still confused me.

I want to use the elastix for my surgery registration based on introperation Xray(2D) and preoperation CT scan(3D). I am studing the registration following http://elastix.bigr.nl/wiki/index.php/Par0013. However, the out data by the transformix is 2d xray which is not what I want for my navigation.

Maybe I have a mistake in the method. Would you give me some advice for my goal. Thanks.

**Comment by mstaring** [comment]
I have no personal experience with the 2D-3D functionality and the original developer is doing other things these days. You may try on the mailing list to see if an other user has feedback for you: https://groups.google.com/forum/#!forum/elastix-imageregistration
