### ISSUE TITLE
TransformRigidityPenalty makes registration far slower

### ISSUE THREAD

**Issue by reynoldscem** [SuperElastix/elastix#252]
Hi,

I'm using elastix 5.0 built from source. I have found that if I use `TransformRigidityPenalty` then the registration takes much, much longer. Perhaps around ten times longer. I would really like to figure out if there's anyway to work around or fix this.

**Comment by mstaring** [comment]
Hi @reynoldscem, this metric is indeed slow to execute especially for B-spline transformations with a lot of parameters. Accelerating it would take a good idea and a new (GPU) implementation.
