### ISSUE TITLE
linux command line use occur error: while loading shared libraries: libANNlib.so

### ISSUE THREAD

**Issue by xkxxfyf** [SuperElastix/elastix#253]
hi, i try to use pyelastix in python but can not find elastix, then i find reason because pyelastix test elastix version error.
![image](https://user-images.githubusercontent.com/25799295/83349837-52d87600-a36a-11ea-988c-e26fa516c31e.png)
so t try to test elastix in command line, i find it also occur error:
elastix: error while loading shared libraries: libANNlib.so: cannot open shared object file: No such file or directory
![image](https://user-images.githubusercontent.com/25799295/83349880-992dd500-a36a-11ea-8a98-66c78f94edec.png)
how can i solve this problem?

**Comment by mstaring** [comment]
You can probably solve it through:
https://github.com/SuperElastix/elastix/wiki/FAQ#i-am-getting-the-error-message-library-not-loaded-libannlibdylib-on-mac-or-similar-on-linux
