### ISSUE TITLE
A bug or improper interpretation of outputpoints.txt

### ISSUE THREAD

**Issue by ctorti** [SuperElastix/elastix#254]
Hi all,

I've either encountered a bug or an error in my interpretation of the results.  I would greatly appreciate some insight.

**Some background:**

I've read page 22 of the Elastix manual (Chapter 4, transformix), describing the contents of outputpoints.txt, and I created an input file ("inputpoints.txt") in the required format.  

The points are from ContourData in a DICOM-RTSTRUCT file, and are in the Patient Coordinate System (PCS).  Initially I converted them to the Image Coordinate System (ICS), accounting for the Image Plane attributes (ImagePositionPatient, ImageOrientationPatient, PixelSpacing), but that generated odd Transformix results:  The indices and points in outputpoints.txt exceeded the image dimensions and physical volume of the images themselves.

Someone recently pointed out that Elastix might be performing some coordinate system transformation on the points - which got me wondering that Elastix might be applying the PCS-to-ICS conversion onto the points that have already been converted!

**Current issue:**

I repeated my work but this time feeding Transformix the points in the PCS.  The results look more promising, in that the x and y components of the indices and points no longer exceed the dimensions and physical volume of the images.  But the z components are another issue:  I still get negative z indices and points that lie outside of the image space.  

Have I encountered a bug or am I failing to properly intepret the results?

To pose this in a slighly less abstract way, here is an example:

Let's say that the first point in inputpoints.txt came from a contour that belongs to the 13th slice in the MovingImage stack.  Hence I expect that InputIndex for Point 0 in outputpoints.txt will have 13 for the z-index.  Yet it isn't - it's 3.

And the z-index in OutputIndexFixed is negative, e.g. [126, 143, -8].

I've attached inputpoints.txt, outputpoints.txt with/without PCS-to-ICS conversion in case they are useful.  If helpful I could also provide the code used to generate the input/output files, and even the DICOM files themselves, but I have tried to keep this (already quite long - sorry!) post as short as possible.

[inputpoints_in_ICS.txt](https://github.com/SuperElastix/elastix/files/4752962/inputpoints_in_ICS.txt)
[outputpoints_from_inputpoints_in_ICS.txt](https://github.com/SuperElastix/elastix/files/4752964/outputpoints_from_inputpoints_in_ICS.txt)
[inputpoints_in_PCS.txt](https://github.com/SuperElastix/elastix/files/4752965/inputpoints_in_PCS.txt)
[outputpoints_from_inputpoints_in_PCS.txt](https://github.com/SuperElastix/elastix/files/4752966/outputpoints_from_inputpoints_in_PCS.txt)

Thanks!

**Comment by ViktorvdValk** [comment]
> Let's say that the first point in inputpoints.txt came from a contour that belongs to the 13th slice in the MovingImage stack. Hence I expect that InputIndex for Point 0 in outputpoints.txt will have 13 for the z-index. Yet it isn't - it's 3.

This depends on the voxel spacing, which does not have to be equal to the spatial distance of the images, I think.
Thereby is the InputIndex the voxel index wrt the fixed image domain, not wrt the moving image domain.

> And the z-index in OutputIndexFixed is negative, e.g. [126, 143, -8].

This is can happen, the voxel index of the output points wrt the fixed image domain  can be negative, since these points do not have to be within the fixed image boundaries.
The OutputIndexMoving and the InputIndex on the other hand should not be negative since these give the voxel indices of the output points wrt the moving image domain (OutputIndexMoving)  and the voxel indices of the input points wrt the fixed image domain (InputIndex).
