### ISSUE TITLE
affine and rigid transform problems

### ISSUE THREAD

**Issue by luckyxiaoqi** [SuperElastix/elastix#255]
there are my images ,parameters files and elastix commands.
[1.nii.gz](https://github.com/SuperElastix/elastix/files/4810828/1.nii.gz)
[2.nii.gz](https://github.com/SuperElastix/elastix/files/4810829/2.nii.gz)
[parameters_Rigid1.txt](https://github.com/SuperElastix/elastix/files/4810804/parameters_Rigid1.txt)
[parameters_Affine1.txt](https://github.com/SuperElastix/elastix/files/4810806/parameters_Affine1.txt)
elastix -f 1.nii.gz -m 2.nii.gz -out E:\ -p parameters_Rigid1.txt  -p parameters_Affine1.txt 
then I got some error results--Some images are missing or not fully displayed
![图片](https://user-images.githubusercontent.com/45393819/85242514-d4a35700-b471-11ea-98ac-1f9e939164b4.png)
![图片](https://user-images.githubusercontent.com/45393819/85242559-eedd3500-b471-11ea-89eb-d9d42b336dfc.png)
I changed many parameters but it didn't work.

**Comment by mstaring** [comment]
The affine transformation moves part of the image out of the field of view defined by the fixed image domain, or part of the image was out of view in the moving image.
