### ISSUE TITLE
Link to legal issues not working

### ISSUE THREAD

**Issue by rcorredorj** [SuperElastix/elastix#257]
Hi guys, 

Just for your info .. the link to the legal issues is not working. http://elastix.isi.uu.nl/legal.php 
I think it is an important one :-) 

All the best,

RaC

**Comment by mstaring** [comment]
Thank you RaC. We have moved this page to the GitHub wiki: https://github.com/SuperElastix/elastix/wiki/Legal-stuff
The elastix.isi.uu.nl website is now replaced by elastix.lumc.nl where this page is not to be found anymore.
