### ISSUE TITLE
How to get the 3d data not the 2d Xray after registiration

### ISSUE THREAD

**Issue by timeanddoctor** [SuperElastix/elastix#258]
I want to use the elastix for my surgery registration based on introperation Xray(2D) and preoperation CT scan(3D). I am studing the registration following http://elastix.bigr.nl/wiki/index.php/Par0013. However, the out data is 2d xray which is not what I want for my navigation.

Maybe I have a mistake in the method. Please give me some advice for my goal. Thanks.

**Comment by GreateLi** [comment]
@  @timeanddoctor ,I have the same problem? you solve it ?

**Comment by N-Dekker** [comment]
Thanks for submitting this issue. Did you find a solution? If not, maybe you can get help from https://groups.google.com/g/elastix-imageregistration  For now, we'll close this issue.
