### ISSUE TITLE
Direction/Orientation matrix DICOM vs Nifti 

### ISSUE THREAD

**Issue by rcorredorj** [SuperElastix/elastix#259]
Hi guys,

I already posted a related question in the SimpleITK Discourse (https://discourse.itk.org/t/direction-orientation-matrix-dicom-vs-nifti/3289) and NeuroStars (https://neurostars.org/t/direction-orientation-matrix-dicom-vs-nifti/14382). 

In short, I'm reading a DICOM series using SimpleITK and I save the itkImage as MHD and Nifti. When I read the MHD and Nifti using a itkImageFileReader, I notice that the direction matrix of the MHD is more similar to the DICOM's. Here I'm talking about numerical differences mainly after the 6th decimal. **When I run elastix 4.9 using MHDs and Niftis, I get differences in the results that may affect later steps in our pipelines** (I'm using the same parameters described on https://github.com/SuperElastix/elastix/issues/89#issuecomment-646551070). 

Already the reply in the ITK discourse is:
"_Unfortunately, what you are seeing is a limitation of the nifti file format. You will have to use another format if you require this level of precision._"

**Is there a way to set properly the precision that is used during the registration in a way that make it less sensitive to small variations in the direction matrix?** I already tried to set the DefaultOutputPrecision parameter to a lower value but didn't change.

Thanks in advance!

RaC

**Comment by rcorredorj** [comment]
Maybe this post in the ITK discourse is useful for you guys. ANTs was also perceiving issues with Niftis apparently... 
https://discourse.itk.org/t/direction-orientation-matrix-dicom-vs-nifti/3289/3

**Comment by mstaring** [comment]
Thanks for the report. The ITK is indeed the right place to fix it.

**Comment by rcorredorj** [comment]
Thank you. At the end, part of the answer was on the ITK post and in the Neurostars one. However, we decided to run elastix always with specific image properties:
 - Origin to 0, 0 ,0
 - Rounding spacing to 3-4th decimal
 - Set a fixed image orientation
 - Use the "identity" matrix instead of the original direction matrix.
After the registration procedure is finished we restore the original image properties of the fixed image.
Probably not the ideal, but helpful to preserve reproducibility.
Thanks again for your replies.

Cheers,

RaC
