### ISSUE TITLE
Unavailability of the official website from Russia

### ISSUE THREAD

**Issue by espdev** [SuperElastix/elastix#26]
I have been unsuccessfully trying to open the website of the project (http://elastix.isi.uu.nl) from Russia.
All my efforts to open this website have proved fruitless. Every time I try to open this website, the “ERR_CONNECTION_TIMED_OUT” error occurs. I have tried to open this website with IP address in St. Petersburg and Samara without any results. However, at the same time, I can easily open this website using American VPN. Could you kindly explain me why it is impossible to open this website from Russia?

**Comment by RuslanKosarev** [comment]
Let Elastix connects people!

**Comment by mstaring** [comment]
I have no idea. Does Russia block this website?
Anyway it is completely out of our hands, so I'm closing this issue.

**Comment by espdev** [comment]
@mstaring thank you for your reply

I have checked Russian "Roskomnadzor" black lists and registers. There are no any records about your domains. This is strange.
