### ISSUE TITLE
Interface discrepancy with parameter AutomaticScalesEstimationStackTransform

### ISSUE THREAD

**Issue by ntatsisk** [SuperElastix/elastix#260]
Hello,

Maybe a minor issue, but I noticed that switching between pairwise and groupwise registration requires that I also change the name of the parameter `AutomaticScalesEstimation `to `AutomaticScalesEstimationStackTransform`.

Is there a particular reason for this discrepancy from other parameters or could the name be unified to `AutomaticScalesEstimation`? I assume that for backwards comparability the name `AutomaticScalesEstimationStackTransform `could still be read but in case it is absent then the `AutomaticScalesEstimation ` is used instead. Thanks!

**Comment by mstaring** [comment]
@stefanklein could this be renamed?

**Comment by stefanklein** [comment]
Yes it would be better to rename it to AutomaticScalesEstimation, since that’s what it is doing, just like in other transforms. Since the parameter is used in several example parameter files, it would be nice to have some backward compatibility, and check for the existence of AutomaticScalesEstimationStackTransform, and if it exist use that instead of AutomaticScalesEstimation
Stefan

**Comment by mstaring** [comment]
@ntatsisk would you be able to submit a PR?

**Comment by ntatsisk** [comment]
Sorry for the really late reply @mstaring , I will give it a try at the end of this week and get back to you!

**Comment by ntatsisk** [comment]
I noticed that there are two functions to calculate scales automatically: `AutomaticScalesEstimation` and `AutomaticScalesEstimationStackTransform`. So, I kept those the same under the hood and I changed only the parameter `AutomaticScalesEstimationStackTransform`  to `AutomaticScalesEstimation` for the user (including backwards compatibility). Let me know if that is what everyone was thinking of. 

You can review the pull request here: #363

**Comment by N-Dekker** [comment]
Fixed by Konstantinos Ntatsis (@ntatsisk), pull request #363.
