### ISSUE TITLE
The meaning of parameters in transformer.log as output

### ISSUE THREAD

**Issue by wendy127green** [SuperElastix/elastix#261]
Hello! I have made 2D affine transform and got the transformer.log file and target.csv, target.pts, source.png file etc as output. In transformer.log I found the ‘TransformParameters’, the ‘Spacing’ and the ‘CenterOfRotationPoint’. I apply T(x) = A(x-c)+c to the original target.csv, but I cannot get the result in output target.csv. I have checked the documentation but cannot find the reasons. Can you give me some help? Thank you very much!
Lin

**Comment by Bartolomejka** [comment]
See this to check you are reading the parameters in a proper way:
[https://github.com/SuperElastix/elastix/issues/237](url)
and the way you are doing with "center of rotation" seems OK.
Bartolomejka

**Comment by wendy127green** [comment]
> See this to check you are reading the parameters in a proper way:
> [https://github.com/SuperElastix/elastix/issues/237](url)
> and the way you are doing with "center of rotation" seems OK.
> Bartolomejka

Thank you , my problem has been solved
