### ISSUE TITLE
To register images from confocal

### ISSUE THREAD

**Issue by Animeshbhu** [SuperElastix/elastix#286]
Hello,
I am trying to register the fly brain confocal images (will be used as moving image) to the fly brain atlas (will be used as a fixed image) which is in  .nrrd format. However, unable to convert these .nrrd images to .ext, so that they can be run in Elastix 4.9. command window.
(Command I am using: elastix -f fixedImage.ext -m movingImage.ext -out outputDirectory -p parameterFile.txt ) 

Great if someone can help me with this. Using it for the first time, so a detailed answer would be really helpful.

**Comment by mstaring** [comment]
elastix can run on many file formats and .nrrd is supported through the ITK mechanisms. As far as I know .ext is not a real file format, I think it was used as an example somewhere and you should replace it with the file format you are using (nrrd in your case). So:

elastix -f fixedImage.nrrd -m movingImage.nrrd -out outputDirectory -p parameterFile.txt
