### ISSUE TITLE
https://elastix.lumc.nl/download/elastix-5.0.1-manual.pdf is missing

### ISSUE THREAD

**Issue by bcdarwin** [SuperElastix/elastix#304]

**Comment by N-Dekker** [comment]
@bcdarwin Hi Ben, Thank you for reporting this issue. The latest version of the manual is at https://github.com/SuperElastix/elastix/releases/download/5.0.1/elastix-5.0.1-manual.pdf

@mstaring Marius, do you think the manual should also still be at https://elastix.lumc.nl/download ?  If so, can you please take care of it?

**Comment by bcdarwin** [comment]
Note that https://elastix.lumc.nl/doxygen/index.html links to the old location, and possibly other places do as well.

**Comment by mstaring** [comment]
Fixed
