### ISSUE TITLE
Add GitHub CI (azure pipelines) results to my.cdash.org

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#315]
@thewtex Matt, do you possibly have a suggestion?

So far I tried the following:

    - script: |
        pushd "$(ELASTIX_BINARY_DIR)"
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        MSBuild.exe Experimental.vcxproj -p:Configuration=Release

At Testing/CI/Azure/ci.yml 
https://github.com/SuperElastix/elastix/commit/44e0d40986afbd0e43896662c22a26a82066b94d 

It did work: https://my.cdash.org/index.php?project=elastix&date=2020-10-08

But it's not really nice, as it requires an extra elastix build, which is quite time consuming! And that YML code is only for MSVC. 

Note that our CTestConfig.cmake is already there: https://github.com/SuperElastix/elastix/blob/5.0.1/CTestConfig.cmake

**Comment by thewtex** [comment]
@N-Dekker instead of calling `MSBuild.exe`, drive the build with `ctest.exe`, e.g.

```
ctest -DExperimental -CRelease
```

**Comment by N-Dekker** [comment]
For the record, this issue is almost solved now, by @ViktorvdValk  😃
