### ISSUE TITLE
Cache ITK binaries at the CI (azure pipelines)

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#316]
ITK should not be rebuilt with each push and each pull request. It typically takes 25 to 30 minutes (total elastix build time 1h20 to 1h40).

Our Azure Pipelines: https://github.com/SuperElastix/elastix/blob/5.0.1/Testing/CI/Azure/ci.yml

Would Azure "Pipeline caching" work for elastix? https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops

Or VCPKG (once upgraded to ITK 5.1.1)? https://github.com/microsoft/vcpkg/blob/master/ports/itk/vcpkg.json

Or Conan (once ITK 5.1.1 is available)? https://conan.io/center/itk

@thewtex Matt, what do you think?

**Comment by N-Dekker** [comment]
Another option could be GitHub Actions, as we just discussed at our last Zoom meeting.

**Comment by ViktorvdValk** [comment]
Elastix is now build on GitHub Actions, which includes caching of the ITK binaries.
