### ISSUE TITLE
Remove requirement for disk IO for non-default TransformixFilter outputs

### ISSUE THREAD

**Issue by thewtex** [SuperElastix/elastix#326]
Suggested by the comments here:

https://github.com/SuperElastix/elastix/blob/75f52c644a1b84b3ba266aa11e161512c50291a9/Core/Main/itkTransformixFilter.hxx#L117-L124

Disk IO is currently required for computing the spatial jacobian, determinant of the spatial jacobian, deformation field, fixed point set transformations. It would be excellent if we can avoid that in the Python interface.

**Comment by mstaring** [comment]
@N-Dekker This one is done right?

**Comment by N-Dekker** [comment]
@mstaring The Jacobian Matrix images, the Jacobian determinant images, and the transformed point sets can now be retrieved without disk IO, using the new (upcoming release) TransformixFilter member functions `ComputeSpatialJacobianMatrixImage()`, `ComputeSpatialJacobianDeterminantImage()`, and `SetInputMesh`/`GetOutputMesh`, respectively.

And as far as I can see, disk IO was never needed when retrieving a deformation field image from the library interface.

So although the code is still there... https://github.com/SuperElastix/elastix/blob/78ba7e17a2dc40cb172a7ec1cf7aa98f57ed585e/Core/Main/itkTransformixFilter.hxx#L110-L117

...the code does not do any harm. The requirement for disk IO for those TransformixFilter outputs is removed.
