### ISSUE TITLE
Automate C++ source code formatting

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#329]
Discussed with Marius @mstaring

**Comment by N-Dekker** [comment]
This is what it looks like if elastix uses the clang-format configuration file from ITK: https://github.com/SuperElastix/elastix/tree/ITK-clang-format

**Comment by N-Dekker** [comment]
Partially addressed by pull request  #336 (Reformat source code, using ITK clang-format file): The automation now depends on the IDE (e.g., Visual Studio) being configured to use clang-format. Or otherwise run clang-format directly, as in commit https://github.com/SuperElastix/elastix/commit/c3a254562d6801f1a34a2de0ec324c10632b5884

    find . -regex '.*\.\(hxx\|h\|cxx\)' -exec /path/to/clang-format.exe -style=file -i {} \; 

Another automation step could be by applying clang-format to a PR, as ITK does at https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/.github/workflows/apply-clang-format.yml

**Comment by mstaring** [comment]
Yes, let us also do it automatically for PRs. Is that easy to setup?

**Comment by N-Dekker** [comment]
Hans Johnson suggested me to have a look at https://github.com/InsightSoftwareConsortium/ITK/blob/v5.1.1/CMake/ITKClangFormatConfig.cmake.in (Thanks, @hjmjohnson !) To be continued!

**Comment by ViktorvdValk** [comment]
This [PR](https://github.com/SuperElastix/elastix/pull/372) should close this issue @N-Dekker 
Or do we want further clang formatting such as the automated formatting instead of comments in GitHub actions?

**Comment by N-Dekker** [comment]
Honestly, I think it would still be useful to have a pre-commit hook to do the formatting, especially to make life easier for elastix users who want to contribute. (For contributors it might be frustrating to see GitHub Actions reject their pull request because of formatting... even though its great that we have such a GitHub Action now  😃 )
