### ISSUE TITLE
Build pxtools with elastix

### ISSUE THREAD

**Issue by kaspermarstal** [SuperElastix/elastix#33]
Tests currently depends on pxtools which have to be installed separately. This is a problem for CI, where some tests always fail, and for users who want to run tests.

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/ca2db47cde44c228f06f07add465cb0535be3c74

should fix this dependency

**Comment by mstaring** [comment]
@kaspermarstal can you check if CI now works properly?

**Comment by kaspermarstal** [comment]
I am afraid it doesn't. It fails with [`AttributeError: 'module' object has no attribute 'replace'`](https://ci.appveyor.com/project/kaspermarstal/elastix/build/1.0.35/job/2h0g23a15lfput5a). Closer though! Looks like the overlap exe is working.

**Comment by mstaring** [comment]
this function is available since python 3.3
What version is on CI?

**Comment by kaspermarstal** [comment]
Looks like python 2.7.

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/d34e7f9efa43e3915599f9b8f371ed4c30f8c7cf

**Comment by mstaring** [comment]
lets wait and see if appveyor is green

**Comment by mstaring** [comment]
fixed
