### ISSUE TITLE
ElastixMain LoadComponents - Clang warning "dangling-gsl"

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#355]
Matt McCormick (@thewtex) reported the following warning at https://github.com/InsightSoftwareConsortium/ITKElastix/pull/82#pullrequestreview-527455152

> _deps/elx-src/Core/Kernel/elxElastixMain.cxx:791:7: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]

    = this->m_Configuration->GetCommandLineArgument( "-argv0" ).c_str();
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

https://open.cdash.org/viewBuildError.php?type=1&buildid=6869971

The latest elastix release also uses this dangling pointer:
https://github.com/SuperElastix/elastix/blob/5.0.1/Core/Kernel/elxElastixMain.cxx#L761-L762

It looks like the bug was already there for a while (April 23, 2009): https://github.com/SuperElastix/elastix/blob/4b6e66759d632885bb6b489abf525367f25037b9/src/Core/Kernel/elxElastixMain.cxx#L502-L503

**Comment by N-Dekker** [comment]
FYI, I'm preparing a fix  😃

**Comment by N-Dekker** [comment]
Update: Removed my claim that the code has "undefined behavior", as it appears that the dangling pointer (`argv0`) is in practice never dereferenced.

**Comment by N-Dekker** [comment]
Fix is underway: https://github.com/SuperElastix/elastix/tree/Fix-clang-dangling-gsl-LoadComponents

**Comment by thewtex** [comment]
@N-Dekker nice, thanks!
