### ISSUE TITLE
Problems in 5.0.1 with masks w/ only 1 slice with true values

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SuperElastix/elastix#368]
I have a fixed multi-slice volume and a corresponding moving multi-slice volume which I would like to register, constrained by a mask. If I use the mask to constrain sampling from the fixed image to only _one_ slice I get the error:
```
Description: itk::ERROR: itk::ERROR: ComputeJacobianTerms(0000021CB73A0E50): No valid voxels (0/1000) found to estimate the AdaptiveStochasticGradientDescent parameters.

Error occurred during actual registration.
```
In elastix 4.9 i don't get this error.

I dug a little deeper, and I can get the same error in 4.9 if I have an image TransformMatrix (mhd files) with many decimals, (e.g. TransformMatrix = 0.99897443 -0.03381213 0.03011357 0.03703501 0.99280887 -0.11383744 -0.02604794 0.11483595 0.9930429) in both the fixed image and the mask. If I set TransformMatrix = 1 0 0 0 1 0 0 0 1 for the fixed image and mask it works. It will not work in 5.0.1 even if I set the TransformMatrix to the identity matrix. 

What can be the cause of this?

parameter file:
```
(FixedInternalImagePixelType "float")
(FixedImageDimension 3 )
(MovingInternalImagePixelType "float")
(MovingImageDimension 3 )
(Registration "MultiResolutionRegistration")
(FixedImagePyramid "FixedRecursiveImagePyramid")
(MovingImagePyramid "MovingRecursiveImagePyramid")
(Interpolator "BSplineInterpolator")
(Optimizer "AdaptiveStochasticGradientDescent")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(Transform "AffineDTITransform")
(Metric "AdvancedMattesMutualInformation")
(ErodeMask "false")
(HowToCombineTransforms "Compose")
(AutomaticTransformInitialization "false")
(AutomaticScalesEstimation "true")
(DefaultPixelValue 0 )
(WriteResultImage "true")
(ResultImagePixelType "float")
(ResultImageFormat "nii")
(CompressResultImage "false")
(NumberOfResolutions 1 )
(MaximumNumberOfIterations 70 )
(NumberOfHistogramBins 32 )
(ImagePyramicSchedule 1.000000 1.000000 1.000000 )
(ImageSampler "RandomCoordinate")
(NewSamplesEveryIteration "true")
(NumberOfSpatialSamples 8192 )
(BSplineInterpolationOrder 1 )
(FinalBSplineInterpolationOrder 3 )
```

**Comment by ViktorvdValk** [comment]
Could you share the masks and the images you used?

**Comment by mstaring** [comment]
@N-Dekker is this related to the spatialobject changes that were introduced back then?

**Comment by N-Dekker** [comment]
So far I haven't been able to reproduce this issue. I just wrote a very simple 3D registration test, with a mask that has only non-zero in one slice. It seems to work fine! At https://github.com/SuperElastix/elastix/tree/Test-SingleSliceTranslation3D

https://github.com/SuperElastix/elastix/commit/7f45afac9a0bc29efcf75b51ae9760d2b1acdfd2

The images have a size of 5x6x8 The fixed image has just a single 2x2x1 object, at start index (1,3,4). The moving image just has the very same 2x2x1 object, but at (2,1,4). The mask only has non-zero at z = 4.

Would it be possible to reproduce this issue by such a simple pair of images?

**Comment by N-Dekker** [comment]
@PatrikBrynolfsson I'm sorry we aren't able to reproduce this issue so far. Can you please reopen the issue if it still bothers you? And can you then possibly provide some extra data, or a minimum example...? 

So I just close the issue for now, for the time being... hope it's OK to you!
