### ISSUE TITLE
GPU memory leak from direct elastix call with OpenCL on

### ISSUE THREAD

**Issue by liu3xing3long** [SuperElastix/elastix#37]
I have extended the ElastixImageFilter with OpenCLResampler included in the original Elastix repo. When using itkGPUImage, the GPU memory will not be released since the reference counter is always set to at least 2. One ref is from the GPUImage itself, but the other ref is coming from the internal GPUImageDataManager inside the class (with SetImagePointer call ), which leads to a recurrent smart pointer counter. And the itkGPUImage allocated will never be released until the whole programme exits.

I have simply altered the SetImagePointer signature to allow this method accept normal pointers but not smart pointer to avoid reference increment. Not sure if this is the best solution, but it surely is the simplest.

I believe this should be some bug to the original Elastix package, however I do not find any issue reporting for this package on Github, therefore I place it here to someone who may encounter the same problem.

P.S.

The usual CPU image (itk::Image) works well, this can be observed by the Print function after image allocation. Typically, when you allocate a new itk::Image the default reference count is 1, and the image would be releases out of function scope. Meanwhile, when you allocate a new itk::GPUImage, the ref count is exactly the same 1, but after graft data using methods like GraftITK from CPU itk Images, the ref count is set as 2, in which the 2nd ref is set by GPUImageDataManager, making the GPU image not properly released.

**Comment by kaspermarstal** [comment]
@dpshamonin?

**Comment by dpshamonin** [comment]
Hi Xinglong,
Thanks for pointing this. The original version of the GPUImageDataManager was based on ITK 4.1.0. And I did not really change anything to keep maximum compatibility with ITK. But I was not sure it is correctly designed, it was to sketchy. In mean while the GPUImageDataManager has been changed see (ITK-git\src\Modules\Core\GPUCommon\include\itkGPUImageDataManager.h/hxx). In particular the call SetImagePointer that you are referring to. Could you post me the way it looks now in your code? I will try to see if your and recent ITK implementation could be merged.
Thanks, Denis

**Comment by liu3xing3long** [comment]
According to the superbuild External_ITK.cmake, the
` ITK_TAG_COMMAND GIT_TAG v4.12.2`. 
It seems that the repo automatically is using ITK 4.12.2. 

Meanwhile, there are two files called itkGPUImageDataManager.h/hxx where one in ITK standard directory and one in Elastix\Common\OpenCL\ITKImprovements. I have changed the latter one looking like:
```
// void SetImagePointer( typename ImageType::Pointer img );
  void SetImagePointer( ImageType* img );
```
This is just expedient but works for me. 

As what I have mentioned before, the smart pointer causes a cycle reference 
```
  typename GPUImageDataManager< GPUImage >::Pointer m_DataManager;
```
in itkGPUImage.h declares the m_DataManager is a member of itkGPUImage, meanwhile 
the 
```
template< typename TPixel, unsigned int VImageDimension >
void
GPUImage< TPixel, VImageDimension >
::AllocateGPU( void )
{
  if( !m_Graft )
  {
    // allocate GPU memory
    this->ComputeOffsetTable();
    const unsigned long numPixel = this->GetOffsetTable()[ VImageDimension ];
    m_DataManager->SetBufferSize( sizeof( TPixel ) * numPixel );
    m_DataManager->SetImagePointer( this ); // adding reference here
    m_DataManager->SetCPUBufferPointer( Superclass::GetBufferPointer() );
    m_DataManager->Allocate();

    /* prevent unnecessary copy from CPU to GPU at the beginning */
    m_DataManager->SetTimeStamp( this->GetTimeStamp() );
  }
}
```
is referred by m_DataManager, making the GPUImage memory not released. 

Although I have been using ITK for years, I am still new to elastix as well as OpenCL, feel free to tell me if I have wrong understanding of the code. Thanks.

**Comment by kaspermarstal** [comment]
FYI @dpshamonin the External_ITK.cmake is from SimpleElastix

**Comment by liu3xing3long** [comment]
Yep, I am using the superbuild system from the SimpleElastix

**Comment by liu3xing3long** [comment]
Please refer to itkGPUImageDataManager that the m_Image is changed from ImageType::Pointer to WeakPointer to tackle smart pointer loop. I suppose someone else should have reported this GPU mem leak bug on ITK repo.

**Comment by liu3xing3long** [comment]
This definitely solves the problem. Feel free to close the issue now. Thanks.

**Comment by GuanrongYing** [comment]
@liu3xing3long I have followed your method to change the code to "void SetImagePointer( ImageType* img );" in itkGPUImageDataManager.h/hxx, but there was still GPU memory leak happened. Thanks for your help!

I use ITK 5.2.1 
Module_ITKReview: ON
ITK_USE_64BITS_IDS: ON
ITK_LEGACY_REMOVE: ON
ITK_USE_GPU: OFF

I compiled elastix 5.0.1  with:
ELASTIX_USE_OPENCL: ON
USE_OpenCLFixedGenericPyramid: ON
USE_OpenCLMovingGenericPyramid: ON
USE_OpenCLResampler: ON
OPENCL_C_VERSION_1_2: ON
OPENCL_OPTIMIZATION_MAD_ENABLE: ON
OPENCL_USENVIDIA_SDK: ON
USE_ALL_COMPONENTS:ON

I tested on GTX 1080Ti with cuda 11.3

**Comment by adrian-ai-medical** [comment]
This issue should be re-opened, the memory leak will continue to be there until these changes are merged.
I am having the same memory leak issues (Elastix 5.1.0 and ITK 5.3.0).

**Comment by N-Dekker** [comment]
> This issue should be re-opened

Thanks for your comment @adrian-ai-medical but regardless of the topic (because I'm not sure if I can help), aren't you able to re-open the issue yourself?
