### ISSUE TITLE
transformix output options

### ISSUE THREAD

**Issue by cnzqy1** [SuperElastix/elastix#375]
Currently when one call transformix with a list of points, an outputpoints.txt with all the information is generated (InputIndex, InputPoint, OutputIndexFixed, etc.). This can be somewhat problematic when one gives transformix a large input file, as the output file is going to be huge. Oftentimes however we only need one of the output fields, such as OutputPoint. Would it be possible to implement an argument to transformix so that it only outputs the desired field?

**Comment by ViktorvdValk** [comment]
I'm looking into this now, but in the mean time I want to suggest a workaround.
Giving the list of points as a .vtk file to transformix will output another .vtk file which only contains the OutputPoints.
This means that you do have to convert your current point set file to a .vtk file with either vtk or itk.

**Comment by cnzqy1** [comment]
Thanks for the reply! Sorry I forgot to reply earlier. At this moment I simply modified the source code and recompiled the program to only output the field I'm interested in, but I would love to see this implemented natively by allowing an additional argument when running transformix.
