### ISSUE TITLE
Problem on running GPU accelerate

### ISSUE THREAD

**Issue by endlessric** [SuperElastix/elastix#378]
Dear all :
I'm using the elastix5.0.1, ITK 5.1.1, MSVS 2019,CMake 3.18.3.
I finish all the compile with no error,but couldn't use the GPU on my registration algorithm.
The error is like the following:

Applying final transform ...
ERROR: Exception during making GPU copy of the interpolator:
itk::ExceptionObject (00000015984FEA20)
Location: "unknown"
File: D:\Program_Files\compile2019\elastix-5.0.1\Common\OpenCL\Filters\itkGPUInterpolatorCopier.hxx
Line: 169
Description: itk::ERROR: itk::ERROR: GPUInterpolatorCopier(0000013332FE96E0): GPUInterpolatorCopier was unable to copy interpolator from: RayCastResampleInterpolator (0000013341F6B800)
  RTTI typeinfo:   class elastix::RayCastResampleInterpolator<class elastix::ElastixTemplate<class itk::Image<float,3>,class itk::Image<float,3> > >
  Reference Count: 4
  Modified Time: 1424
  Debug: Off
  Object Name:
  Observers:
    none
  InputImage: 00000133427D28C0
  StartIndex: [0, 0, 0]
  EndIndex: [511, 388, 317]
  StartContinuousIndex: [-0.5, -0.5, -0.5]
  EndContinuousIndex: [511.5, 388.5, 317.5]
  Threshold: 0
  FocalPoint: [-780, 0, 0]
  Transform: 0000013341F6B3B0
  Interpolator: 0000000000000000

WARNING: Unable to configure the GPU.
  The OpenCLResampler is switching back to CPU mode.
  Applying final transform took 0.10s

By the way, I could find the file "itkGPUInterpolatorCopier.hxx" in that direction.
Wish someone could help,thanks!

**Comment by steark300** [comment]
I think the problem is the "RayCastResampleInterpolator" is currently not support GPU acceleration. Only Bspline, Nearleast, and Linear interpolator support GPU acceleration now. But I am curious is it possible to add this GPU acceleration support in the future version.

**Comment by 1989HD** [comment]
Hi! Sorry, do not have an answer to your question. However I was wondering if you could point me to some documentation on the compiling and use of GPU acceleration? The elastix manual does not seem to cover it? Thanks in advance!

**Comment by endlessric** [comment]
@1989HD You could find the compile step in elastix manual P.23. (Elastix 5.0.1)

**Comment by mstaring** [comment]
Indeed, the RayCastResampleInterpolator is not implemented on the GPU.
