### ISSUE TITLE
elastixlib: monitoring of progress using ITK observers mechanism

### ISSUE THREAD

**Issue by Bartolomejka** [SuperElastix/elastix#4]
Is somehow possible to monitor ELASTIX progress from outside, if it is used as a library? I mean something like ITK observers mechanism. Not std::cout output. Can somebody prepare it or write some hints?

**Comment by kaspermarstal** [comment]
Having talked this over with @mstaring, it is possible by exposing observers through the interface somehow.  For capturing an iteration event in elastix we do have ITK observers that creates a signal after every iteration, which is caught somewhere else in elastix, and then used to print a new iteration line in elastix.log. You can check how it's done for the printing to elastix.log and implement the same for the library, and then expose the observer through the library interface. 

One thing to note though is that typically optimization routines can stop whenever they want, which we cannot predict. Only for the stochastic GD routines do we currently have the number of iterations as the only stopping condition. 

Hope this helps!

**Comment by mstaring** [comment]
This is not something we will allocate resources to ourselves.
I am closing this issue for that reason. Feel free to reopen when you want to work on it.
