### ISSUE TITLE
elastix::TransformBase itk::Object casting

### ISSUE THREAD

**Issue by thewtex** [SuperElastix/elastix#411]
Building on the work of @ViktorvdValk to address the macOS ITKElastix Python package, using

https://github.com/ViktorvdValk/elastix/tree/ITK_TEMPLATE_EXPORT

https://github.com/ViktorvdValk/ITKElastix/tree/UseForkITK

with the script:

```
import itk
import faulthandler

faulthandler.enable()
fixed_image = itk.imread('data/CT_2D_head_fixed.mha', itk.F)
moving_image = itk.imread('data/CT_2D_head_moving.mha', itk.F)

parameter_object = itk.ParameterObject.New()
default_rigid_parameter_map = parameter_object.GetDefaultParameterMap('rigid')
parameter_object.AddParameterMap(default_rigid_parameter_map)

result_image, result_transform_parameters = itk.elastix_registration_method(
    fixed_image, moving_image,
    parameter_object=parameter_object,
    log_to_console=False)
```

a debug build with lldb, identifies the issue:

```
Process 40949 stopped
* thread #2, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001616575f1 _ElastixPython.so`elastix::TransformBase<elastix::ElastixTemplate<itk::Image<float, 2u>, itk::Image<float, 2u> > >::SetTransformParametersFileName(this=0x000000016ccacfd0, filename="output_path_not_set/TransformParameters.0.txt") at elxTransformBase.hxx:1694:17
   1691	    this->m_TransformParametersFileName = "";
   1692	  }
   1693	  ObjectType * thisAsObject = dynamic_cast<ObjectType *>(this);
-> 1694	  thisAsObject->Modified();
   1695	
   1696	} // end SetTransformParametersFileName()
   1697	
Target 0: (Python) stopped.
(lldb) p this
(elastix::TransformBase<elastix::ElastixTemplate<itk::Image<float, 2>, itk::Image<float, 2> > > *) $0 = 0x000000016ccacfd0
(lldb) p thisAsObject
(ObjectType *) $1 = 0x0000000000000000
```

https://github.com/ViktorvdValk/elastix/blob/8ef128fedc26023df0799ff2d4fe965c184b2151/Core/ComponentBaseClasses/elxTransformBase.hxx#L1676-L1696

where `ObjectType` [is `itk::Object`](https://github.com/SuperElastix/elastix/blob/9d971ef82c7d34cbc53f544d9a276fd7daf32bf8/Core/ComponentBaseClasses/elxTransformBase.h#L171). But `elastix::TransformBase` does not inherit from `itk::Object`, but `elastix::BaseComponent`:

https://github.com/SuperElastix/elastix/blob/9d971ef82c7d34cbc53f544d9a276fd7daf32bf8/Core/Install/elxBaseComponent.h#L53

@N-Dekker @mstaring @stefanklein passing to you for the elastix architecture-appropriate change to address this.

**Comment by N-Dekker** [comment]
> ObjectType is itk::Object. But elastix::TransformBase does not inherit from itk::Object

Thanks for investigating this issue, @thewtex!

Honestly it took me a while to understand this part of the architecture, but in practice it appears that _every_ `elastix::TransformBase` derived object is _also_ derived from `itk::Transform`, via another inheritance branch (using multiple inheritance). So I think this particular `dynamic_cast<ObjectType *>` should have worked!

Of course, that does not explain the crash. Sorry!

**Comment by thewtex** [comment]
@N-Dekker thanks for the pointers. In liu of better solutions, this branch prevents the crash on macOS:

https://github.com/SuperElastix/elastix/pull/412
