### ISSUE TITLE
OpenCLResampler build error: 'ParameterMapType does not name a type' 

### ISSUE THREAD

**Issue by 1989HD** [SuperElastix/elastix#414]
Dear all, 

For some time I've been trying to build Elastix with UseOpenCL, but it keeps giving me errors when building the OpenCLResampler is set to ON. When I set it to OFF, the build is succesfull. I've attached a screenshot if the error. Does anyone know what causes this and how I can fix it? 

Some info:
- Trying on RHEL8
- NVidia Quadro RTX6000
- Cmake version 3.11.4
- GCC version 8.3.1 
- Installed OpenCL using CUDA toolkit 11.2
- Succesfully compiled ITK V.5.1.1 with appropriate flags

I'm trying to build Elastix 5.0.1 with:
-CMAKE_BUILD_TYPE=Release
-ELASTIX_USE_OPENCL=ON
-OPENCL_INCLUDE_DIRS=/usr/local/cuda/include
-OPENCL_LIBRARIES=/usr/local/cuda/lib64/libOpenCL.so
-USE_OpenCLFixedGenericPyramid=ON
-USE_OpenCLMovingGenericPyramid=ON
-USE_OpenCLResampler=ON
-OPENCL_USENVIDIA_SDK=ON

Thanks in advance for your help. 

![image](https://user-images.githubusercontent.com/41747965/107667406-d5525d00-6c8f-11eb-9914-6216b404ef87.png)

**Comment by N-Dekker** [comment]
@1989HD Thank you very much for your bug report! Can you please check it it would be fixed by pull request #421 ?

I must have introduced the bug with pull request https://github.com/SuperElastix/elastix/pull/395 commit ebaad19f5fbce6ef471f9740054c45b35b3234d1 "ENH: Sync Resamplers, ResampleInterpolators WriteToFile w/ ParameterMap" (27 January 2021)

**Comment by 1989HD** [comment]
@N-Dekker Thanks for your swift response and your solution! This fixes the bug, the build is now successful. I've not been able to test if it works though, will report to you asap. 

Thanks again, this is going to save me a huge amount of time.
