### ISSUE TITLE
Installation failed due to non-existing files

### ISSUE THREAD

**Issue by F462** [SuperElastix/elastix#43]
When trying to install I get the following error:
> CMake Error at Core/cmake_install.cmake:88 (file):
  file INSTALL cannot find
  "[PATH TO ELASTIX]/build/ITKIOFactoryRegistration/itkImageIOFactoryRegisterManager.h".
Call Stack (most recent call first):
  cmake_install.cmake:39 (include)

Changing the line 245 in Core/CMakeLists.txt:
`${elastix_BINARY_DIR}/ITKIOFactoryRegistration/itkImageIOFactoryRegisterManager.h`
to
`${elastix_BINARY_DIR}/ITKFactoryRegistration/itkImageIOFactoryRegisterManager.h`

and the line below accordingly, solves the problem for me.

**Comment by mstaring** [comment]
what version of ITK are you using?

**Comment by F462** [comment]
I'm using ITK 4.13.0

**Comment by mstaring** [comment]
I was indeed able to reproduce using ITK 4.13.0. I will approve PR https://github.com/SuperElastix/elastix/pull/47
Thank you for reporting!

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/058253a1e7804e2e0d704dae372b97d853defbe5

done

**Comment by kaspermarstal** [comment]
This merge means elastix only supports ITK >=v4.13.0 as per 058253a (which is fine, but important to note)
