### ISSUE TITLE
Point based image registration

### ISSUE THREAD

**Issue by maz369** [SuperElastix/elastix#435]
Hi,

I am working on a multi-modal affine registration task which is too difficult. To help the registration, I am defining corresponding points between moving and fix image.
The images are Nifti format volume and from each one I am selecting 90 corresponding points using BrainSuite. The format of text file for points is similar to following:
point
90
137 141 564
137 141 563
137 141 562
...

I have 2 separate .txt for to represent points in moving and fixed image volume. These points are mostly samples from a small central region of the fixed and moving image. However, including fixed and moving points seems to give unexpected result. I tried adjusting weights but still it does not work.
(Metric0Weight 0.2)
(Metric1Weight 0.8)

Since these points are coordinates from BrainSuite, I even tried "index" instead  of "point" in the point text file and that even did not help.

I am using Elastix framework on Windows 10. Can you please let me know how to solve this issue? Also please let me know if there is any example for point-based affine registration. I was able to find example for SimpleElastix but not for Elastix. Also, the manual section for point based selection was informative but very short.
Is there any way to do affine registration in Elastix only based on selected corresponding points without using any similarity matrix? (I tried achieving this but setting Metric0Weight=0 and Metric1Weight=1 but did not seem to work!).

Thank you for your help!

**Comment by ViktorvdValk** [comment]
Hi @maz369,

Could you share you command line call and your point sets and images, so I could try to reproduce your problem?
If you're using point sets to aid your registration, be aware that the point sets should be in world coordinates if you use "point" in your point set file. If you use "index" in the point set file, elastix uses the coordinates relative to the fixed image origin.

And setting " Metric0Weight=0 and Metric1Weight=1 ", should be the correct way of doing registration without using any similarity matrix in elastix.

**Comment by ViktorvdValk** [comment]
Hi @maz369 , thanks for raising the issue, I'm closing it for now. Feel free to reopen it, when you find that this issue is not fixed in the newest release of elastix.
