### ISSUE TITLE
question about the "not enough sample" error.

### ISSUE THREAD

**Issue by orange676** [SuperElastix/elastix#478]
I have a question about the "not enough sample" error. I had this problem in the very begining, after I provide the intial transform, this problem seems solved. But it still appears from time to time, I have check my initial transforamtion, it looks not bad. I have also noticed that it fails more often when the initial rotation is large, or sometimes I need 180 degree. Can elastix handle such case or what is the proper way to handle it?

**Comment by mstaring** [comment]
Dear @orange676 , at the FAQ we explain this in some detail, see 
https://github.com/SuperElastix/elastix/wiki/FAQ
the fourth question.

Most elastix optimizers do rely on proper initialization. You could specify this initial rotation in an InitialTransform via the -t0 commandline argument. You could also try to use the full search optimizer to loop over a number of rotations and find a reasonable starting point.

**Comment by orange676** [comment]
Hi Marius, 
thank you for your reply:-) 
The problem is that I have already put a inital transform, and the visual inspect looks good,
The only reason I guess that too much samples in the corners when rotation is large (as below), is that the case?
![afbeelding](https://user-images.githubusercontent.com/74063000/122014269-45e4c400-cdbf-11eb-98a9-1b65fdf89ca0.png)

**Comment by mstaring** [comment]
Then, I would think your initial transform should solve it, unless some of the other items from the FAQ occurs.
