### ISSUE TITLE
Document how to generate Doxygen documentation

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#479]
Ibraheem Al-Dhamari (@idhamari) commented at https://github.com/SuperElastix/elastix/issues/233#issuecomment-857572543 that it would be nice to add documentation on how to how to generate Doxygen documentation.

I described it as at https://github.com/SuperElastix/elastix/issues/233#issuecomment-856928162 as follows:
> You start by elastix CMake option BUILD_DOCUMENTATION = ON.
>
> When you then do CMake configure, it will create a file named "doxyfile.out", in `<elastix-build-directory>/help`. That's the file that you should pass to the Doxygen executable.

But then I noted that the ITK approach seems somewhat more convenient, as it should add a "Documentation" build target when the user enables `ITK_BUILD_DOCUMENTATION`:

https://github.com/InsightSoftwareConsortium/ITK/blob/v5.2.0/Utilities/Doxygen/CMakeLists.txt#L126-L180

To be discussed...

Furthermore I experienced difficulties, trying to generate embedded LaTeX figures in HTML on Windows 10, using Doxygen + MiKTeX. But that might be because of my lack of experience.

**Comment by idhamari** [comment]
> But then I noted that the ITK approach seems somewhat more convenient, as it should add a "Documentation" build target when the user enables ITK_BUILD_DOCUMENTATION:

In ITK, VTK, ..etc, usually, after building e.g. using make, the documentation is generated by running:

`
                  make doxygen
`

In visual studio, there should be a project called doxygen which can be built to generate the documentation.

**Comment by N-Dekker** [comment]
@idhamari FYI Some small doxygen fixes are already underway, inspired by your pull request 😃 Now still at branch https://github.com/SuperElastix/elastix/tree/Fix-doxygen-warnings

**Comment by N-Dekker** [comment]
@idhamari 
> If you like I can upload the documentation as a compressed file somewhere so you can use it temporarily for your online documentation until the problem of the images is fixed.

Thanks for your offer, Ibraheem, but I think I finally got Doxygen running properly on Windows, including MiKTeX LaTeX and GraphViz "dot". 😄 Can you please have another look at https://elastix.lumc.nl/doxygen/ (which I just uploaded)? Does it look the same as the documentation you already generated on your Ubuntu?

**Comment by mstaring** [comment]
It would be good to add a description to the github wiki as well

**Comment by N-Dekker** [comment]
> It would be good to add a description to the github wiki as well

I can certainly describe what I did, on Windows:

- Install CMake (https://cmake.org), Doxygen (https://www.doxygen.nl), GraphViz (https://graphviz.org), MiKTeX (https://miktex.org)
- CMake configure elastix having `BUILD_DOCUMENTATION=ON`. (It should create a file named "doxyfile.out", in `<elastix-build-directory>`/help)
- If your MiKTeX  installation does not have a file named "gswin32c.exe", rename the file "mgs.exe" to "gswin32c.exe", as I described at https://github.com/SuperElastix/elastix/issues/233#issuecomment-859675707
- Ensure that "gswin32c.exe", as well as GraphViz dot.exe can be found at the current path and start Doxywizard (Doxygen GUI frontend).
- Within Doxywizard, open the "doxyfile.out" file from `<elastix-build-directory>/help`, get to the Run tab page and click "Run doxygen". Wait until it is finished. Warnings may be ignored.
- The doxygen generated HTML should be at `<elastix-build-directory>/help`

Is it OK like that? Or do you have another suggestion?

**Comment by mstaring** [comment]
Yes, than at least you have yourself some guidance when we need it in the future.

Maybe put it under miscellaneous, but feel free to pick a better place.

**Comment by N-Dekker** [comment]
@mstaring @idhamari Just added documentation to the wiki, please check:

https://github.com/SuperElastix/elastix/wiki/How-to-build-Doxygen-documentation-from-elastix-source-code

**Comment by mstaring** [comment]
excellent
