### ISSUE TITLE
 2d-3d registiration Parameter settings?

### ISSUE THREAD

**Issue by GreateLi** [SuperElastix/elastix#491]
http://elastix.bigr.nl/wiki/index.php/Par0013

(Interpolator0PreParameters -0.009475 -0.006807 -0.030067 0.0 0.0 0.0)
(ResampleInterpolator0PreParameters -0.009475 -0.006807 -0.030067 0.0 0.0 0.0)
(Interpolator0FocalPoint 0.54 -0.85 -813.234)
(ResampleInterpolator0FocalPoint 0.54 -0.85 -813.234)

How are the above parameters set? Where to come from?

I 'm study leg bones registiration, but don't Known parameters ;
I do not know how to set the parameters, according to the actual data, and the principle of setting the parameters.

**Comment by amberhappy** [comment]
Hello, I have same question. Do you know the parameters' meaning now? It's that about X-ray imaging paramters like focal spot and distance source to patient?

**Comment by mdhe1248** [comment]
Did you successfully made a 2d - 3d registration? Could you share the parameter file with me? I cannot open the link.

**Comment by mdhe1248** [comment]
Oh, I found the link. 
https://elastix.lumc.nl/modelzoo/par0013/

Thanks.

**Comment by N-Dekker** [comment]
Thanks for submitting and discussing this issue. I'm closing now, assuming it is solved.
