### ISSUE TITLE
GPUCompositeTransformCopier bug

### ISSUE THREAD

**Issue by mstaring** [SuperElastix/elastix#5]
copied from mstaring/elastix clone, mys007:

GPUCompositeTransformType should be typedefed as GPUCompositeTransform< GPUScalarType, SpaceDimension > instead of CompositeTransform< GPUScalarType, SpaceDimension > in itkGPUCompositeTransformCopier.h.

**Comment by kaspermarstal** [comment]
@mys007 Thank you for reporting the issue. What was the original error message? And is it trivially fixed by this change? Can you give some background before we incorporate your changes?

**Comment by mys007** [comment]
I'm really sorry, I can not go back so far in time to answer the questions.

**Comment by kaspermarstal** [comment]
OK, thanks!

**Comment by mstaring** [comment]
closing without a change as we cannot reproduce it here
