### ISSUE TITLE
Bug in TransformixFilter ProcessObject behavior

### ISSUE THREAD

**Issue by FBerendsen** [SuperElastix/elastix#53]
I think I found a bug in the transformixfilter that is causing SuperElastix to fail generating a displacement field or warped image if Fixed and Moving images have different sizes. 
The root of the problem lies in the fact that the primary input of the TransformixFilter-ProcessObject is defined as the MovingImage. A call to UpdateOutputInformation() will make all TransformixFilter copy the MovingImage information to all its outputs (results image and displacement field). This is incorrect behaviour, since the information should be from the Fixed domain which is defined in the ParameterMap.

A correct implementation would be to make the ParameterMap the primary input, and to override all relevant ProcessObject methods. However this may lead to side effects I do not oversee? What do you think?

**Comment by kaspermarstal** [comment]
Good catch floris! What if we also gave it the fixed image and made this the primary input?

**Comment by FBerendsen** [comment]
Transformix does not take a fixed image

**Comment by kaspermarstal** [comment]
No but the filter could, even if we don't give to transformix, if only to fix the ITK pipeline mechanism.

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/81b498e32688e2dac34ed1fbd84d576ceac1cfb3 fixes this
