### ISSUE TITLE
 Installing new components with SimpleITK Elastix #457 

### ISSUE THREAD

**Issue by zwep** [SuperElastix/elastix#586]
Hi,
Ive done the SuperBuild for SimpleITK - Elastix and want to play around with different parameters. For example, I want to use the FullSampler as ImageSampler. However, when running I get the following error in the error log

Error:
FullSampler(index 1) - This component is not installed!
ERROR: error occurred while creating ImageSampler 0.

itk::ExceptionObject (0x85addb0)
Location: "unknown"
File: /home/bugger/bin/build_simpleelastix/Elastix/Core/Kernel/elxElastixMain.cxx
Line: 827
Description: itk::ERROR: ElastixMain(0x8338ad0): The following component could not be created: FullSampler

ERROR:
One or more components could not be created.

How can I install this (and other) components?

EDIT: Just installed and used Elastix without SimpleITK inbetween. Even there I get the same error message. Not unusual behaviour of course. But even more curious now how to install additional components

**Comment by poretga99** [comment]
SimpleelElastix by default doesn't use the FullSampler component. You can manually enable the desired sampler by changing the CMake flag in SimpleElastix/SuperBuild/External_Elastix.cmake by changing the line `-DUSE_FullSampler:BOOL=OFF` to `-DUSE_FullSampler:BOOL=ON`.
I'd expect the same result for Elastix compilation.
