### ISSUE TITLE
Setup CDash dashboards

### ISSUE THREAD

**Issue by kaspermarstal** [SuperElastix/elastix#6]

**Comment by mstaring** [comment]
first attempts:
3dc5bb723d165b39bc5f7b0c81f69e5cb27c2876
1c9b5e959b52314a47a51bb72715ebeb5147f152
bd8958c0ec25797cf779ea593aa04fa933a649a2

**Comment by mstaring** [comment]
just pushed a general script that worksforme (TM)
81fce8fc4abec54c310c35f2b051a25fc3e948b4

**Comment by mstaring** [comment]
http://my.cdash.org/index.php?project=elastix&date=20170606
Dashboards are getting back online.
Next step is to get BIGR dashboards running

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/blob/develop/Testing/elx_nightly_dashboard.py

**Comment by fedorov** [comment]
As an alternative, you could consider integration with the commercially supported free CI platforms (TravisCI, Appveyor and CircleCI). They are available for all three operating systems, and as long as your build+test is within 40 minutes or so, you get those resources for free.

I've been working with CDash as a user for very long time as a Slicer developer, and in my view commercial CIs are a lot more user friendly, are nicely integrated with GitHub, have much better notification mechanisms, and have a lot more useful features (for example, they can be used to generate and publish packages). As an example, we run tests on CIs on every pull request and for every new commit in this repo, and also use CIs for making binary packages for all 3 platforms: https://github.com/qiicr/dcmqi

**Comment by kaspermarstal** [comment]
Thanks for the suggestion @fedorov! We are currently building Linux and Mac versions on TravisCI, but lack a Windows build. Do you have experience with AppVeyor? If so, would you be interested in contributing an AppVeyor build?

**Comment by fedorov** [comment]
I do have some experience with AppVeyor, I can take a look!

**Comment by kaspermarstal** [comment]
That's great! Let us know how it goes!

**Comment by mstaring** [comment]
Hi @fedorov, @kaspermarstal,
Thanks for contributing the appveyor patch Andrey! Do we need to change a setting somewhere as well, in order to get builds?
Best, Marius

**Comment by fedorov** [comment]
@mstaring yes, you need to

1. set up an account on [Appveyor](appveyor.com)
2. create a new project and point Appveyor to this repository

Also see "Getting started" here: https://www.appveyor.com/docs/

I could set this up under my account, but I think it would be best if one of the project maintainers does it.

Let me know if you have any questions along the way!

**Comment by mstaring** [comment]
ok, thx. kasper will take care of it

**Comment by kaspermarstal** [comment]
It is up and running now https://ci.appveyor.com/project/kaspermarstal/elastix/build/1.0.1

**Comment by kaspermarstal** [comment]
Thanks for your contribution @fedorov!

**Comment by fedorov** [comment]
👍 

In case you didn't know, you can also add badges to the project front page to quickly see what is the dashboard status, as an example see here: https://github.com/qiicr/dcmqi
