### ISSUE TITLE
The input of Masks seems invalid. (version--4.8.0)

### ISSUE THREAD

**Issue by Li-chunming** [SuperElastix/elastix#612]
This is an issue with the [version_4.8.0](https://elastix.lumc.nl/download.php). When I use masks assisted registration, they seem to be invalidated (the result does not change).
Here is the codes I call the **elastix** registration, which is provided by the **manual.pdf**. 
 ```
movingreader->SetFileName("D:\\Project\\ElastixRegistration\\datasets\\exampleinput\\moving.mhd");
	movingreader->Update();
	fixedreader->SetFileName("D:\\Project\\ElastixRegistration\\datasets\\exampleinput\\fixed.mhd");
	fixedreader->Update();
	movingMaskreader->SetFileName("D:\\Project\\ElastixRegistration\\datasets\\exampleinput\\mask_moving.mhd");
	movingMaskreader->Update();
	fixedMaskreader->SetFileName("D:\\Project\\ElastixRegistration\\datasets\\exampleinput\\mask_fixed.mhd");
	fixedMaskreader->Update();
        file_parser->SetParameterFileName("D:\\Project\\ElastixRegistration\\datasets\\exampleinput\\parameters_BSpline.txt");
       RegistrationParametersType parameters = file_parser->GetParameterMap();
       ELASTIX * elastix = new ELASTIX();
	int error = 0;
	itk::DataObject::Pointer fixed_image = fixedreader->GetOutput();
	itk::DataObject::Pointer moving_image = movingreader->GetOutput();
	itk::DataObject::Pointer fixed_mask = fixedMaskreader->GetOutput();
	itk::DataObject::Pointer moving_mask = movingMaskreader->GetOutput();
```
        error = elastix->RegisterImages(
		fixed_image,
		moving_image,
		parameters, // Parameter map read in previous code
		output_directory, // Directory where output is written, if enabled
			true, // Enable/disable writing of elastix.log
			true,// Enable/disable output to console
		fixed_mask, // Provide fixed image mask (optional, nullptr = no mask)
		moving_mask // Provide moving image mask (optional, nullptr = no mask)
		);

All data and configuration files are provided on the [official website](https://elastix.lumc.nl/download.php) ，including the APIs in the code. I haven't made any changes. Please help me analyze the reason~

Here are some information in the **elastix.log**，it indicates that mask has not been entered:
![image](https://user-images.githubusercontent.com/59553759/153746212-175dee73-4b8f-4c95-bbb6-35302457b23d.png)

**Comment by Li-chunming** [comment]
The problem has been solved. The type of mask needs to be forced to UINT8.

**Comment by N-Dekker** [comment]
@Li-chunming  Thank you for sharing this issue, as well as your solution! Hereby I'll close the issue.

Kind regards, Niels
