### ISSUE TITLE
applying 2D transform on RGB image

### ISSUE THREAD

**Issue by adizhol** [SuperElastix/elastix#62]
Hi,

Is there a faster way to apply a 2D transformation on an RGB image without applying it on each channel separately?

Thanks,
Adi

**Comment by mstaring** [comment]
Hi Adizhol,

Please use the mailing list for these kind of questions. We intend to use the issue tracker for real issues :-)
https://groups.google.com/forum/#!categories/elastix-imageregistration/elastix

transformix probably won't work correctly on an RGB image, so a per-channel operation would be the easiest workaround. Note that although it would be possible to create a small ITK program that resamples RGB images, the challenge would be to read in the elastix transformation parameters.
https://itk.org/Wiki/ITK/Examples/ImageProcessing/RGBResampleImageFilter

HTH, Marius
