### ISSUE TITLE
Building SimpleElastix

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SuperElastix/elastix#623]
Hello!

I realize this might not be the correct forum, but the support for SimpleElastix is dead since quite a few months. When I build SimpleElastix, I want to set the version of SimpleITK that is used since I want to use the latest features from there.  How can I control that?

Also, what is the status of SimpleElastix now?

Thank you in advance!

**Comment by NHPatterson** [comment]
[Not an elastix dev but this might be informative on the state of SimpleITK-elastix.](https://groups.google.com/g/elastix-imageregistration/c/LUWEm0I5OFY)

**Comment by PatrikBrynolfsson** [comment]
Thank you for the information, this is very good news! I am using SimpleElastix in C#, so I think ITKElastix will not be a solution for me at the moment. Looking forward to the merge between SimpleITK and SimpleElastix.
