### ISSUE TITLE
Elastix results differ depending on the input image format (.nrrd and .mha)

### ISSUE THREAD

**Issue by Kmacneil0102** [SuperElastix/elastix#63]
We have been trying to use SlicerElastix for our project and ran some tests to compare the differences between command line Elastix and Elastix via SlicerElastix in 3D Slicer. During these tests, we came across differences in results based on the image format of the input volumes and masking labels. SlicerElastix converts inputs to .mha whereas we were using .nrrd when running from command line.

Linked is an example dataset and outputs (as well as parameter files used) that demonstrate this issue. There is a text file included that describes what is contained, and how Elastix was run. The results are that running Elastix with BSpline registration succeeds and produces satisfactory results when using .nrrd format for the inputs. However, when running BSpline registration with inputs that are .mha format, the registration fails (with an “Description: itk::ERROR: AdvancedMattesMutualInformationMetric(0000026EE53C48A0): Too many samples map outside moving image buffer: 500 / 2048” error).

Link to dataset and test results: https://www.dropbox.com/sh/9pdmhsoka8l4rw6/AAC7HLIhF78q6_X8YAlx0szFa?dl=0

**Comment by mstaring** [comment]
We rely on itk image io functionality for reading the images.
Do you know how the conversion within slicer works (from nrrd to mha)?

I checked and the header as well as the content of the nrrd and mha images appear the same. 
Can you check if directly calling elastix, so not through slicer, gives the same problem?

**Comment by Kmacneil0102** [comment]
The calls were made directly to elastix, just using the 4.8 binaries packaged with SlicerElastix. However, I did just try using the updated 4.9 Elastix binaries and the result is the same.

As for the conversion in Slicer, I am not sure how it works!

**Comment by mstaring** [comment]
I found the problem, it is in the conversion from nrrd to mha. In the latest release of ITK they increased the resolution of the mhd reader and writer, going from float to double. Recompiling my own conversion tool with this latest version of ITK, made the registration differences go away.

Can you upgrade your ITK version and try again?

**Comment by fedorov** [comment]
@mstaring thank you for investigating this!

We are using elastix within 3D Slicer, and have to basically follow the update plans of that project. It [looks like](https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_ITKv4.cmake#L36) Slicer is using ITK v4.13 from December 2017, but I think there are discussions to update it sometime soon. Hopefully we will remember to check and let you know if it is working as expected after that update happens.

**Comment by mstaring** [comment]
Great, I will close this issue, but you can reopen if problems persists.
