### ISSUE TITLE
Build error when using ITK thirdparty modules

### ISSUE THREAD

**Issue by YuchuanQiao** [SuperElastix/elastix#64]
When ITK_BUILD_DEFAULT_MODULES off, ITKGroup_ThirdParty ON, elastix build will meet this build error
\elastix\src\common\itkMeshFileReaderBase.h(23) : fatal error C1083: Cannot open include file: 'itkMeshFileReader.h': No such file or directory
#include "itkMeshFileReader.h" // for MeshFileReaderException
When using ITK_BUILD_DEFAULT_MODULES ON, everything is ok.
Maybe this is a small problem, however, I should report it if someone also meets it.

**Comment by kaspermarstal** [comment]
Thank you for reporting this issue. Now people can find via searching!
