### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by fernand-f** [SuperElastix/elastix#648]
Hello everyone,

I'm new to Elastix and I try to perform SimilarityTransform on my images. Though, a problem accures when I call Elastix :   

Reading the elastix parameters from file ...

Installing all components.
InstallingComponents was successful.

Error: 
AdvancedKappaStatistic(index 3) - This component is not installed!
ERROR: error occurred while creating Metric 0.

itk::ExceptionObject (0x229bb50)
Location: "unknown" 
File: /home/fort/elastix/elastix-5.0.1/Core/Kernel/elxElastixMain.cxx
Line: 828
Description: ITK ERROR: ElastixMain(0x228c380): The following component could not be created: AdvancedKappaStatistic

Error: 
SimilarityTransform(index 3) - This component is not installed!
ERROR: error occurred while creating Transform 0.

itk::ExceptionObject (0x22ad920)
Location: "unknown" 
File: /home/fort/elastix/elastix-5.0.1/Core/Kernel/elxElastixMain.cxx
Line: 828
Description: ITK ERROR: ElastixMain(0x228c380): The following component could not be created: SimilarityTransform

Seems like some components of Elastix are missing, but I downloaded and compiled the software successfully. I don't understand what to do.

**Comment by N-Dekker** [comment]
Thank you for your question @fernand-f  Can you tell us the pixel type (number of bits, integer or floating point) of your images? Also can you please share the content of the parameter file that you may have passed to elastix?

**Comment by fernand-f** [comment]
Hello @N-Dekker , the pixel type that I use is are either uint8 or float types, depends if I use binary labelmap or if I use the signed distance transform.

I've checked in the CMakeCache.txt file, and indeed  `USE_AdvancedKappaStatisticMetric` and `USE_SimilarityTransformElastix` are set to `OFF`. 

Here's the parameter file that I use : 

// Main settings

(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")

(UseDirectionCosines "true")

// **************** Main Components **************************

(Registration "MultiResolutionRegistration")
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")

(FixedImagePyramid "FixedRecursiveImagePyramid")
(MovingImagePyramid "MovingRecursiveImagePyramid")

(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "SimilarityTransform")
(Metric "AdvancedKappaStatistic")

// ***************** Transformation **************************

(AutomaticScalesEstimation "true")

(AutomaticTransformInitialization "true")

(HowToCombineTransforms "Compose")

// ******************* Similarity measure *********************

(NumberOfHistogramBins 128)

(ErodeMask "false")

// ******************** Multiresolution **********************

(NumberOfResolutions 4)

(ImagePyramidSchedule 8 8  4 4  2 2  1 1 )



// ******************* Optimizer ****************************

(MaximumNumberOfIterations 250)

// **************** Image sampling **********************

(NumberOfSpatialSamples 2048)

(NewSamplesEveryIteration "true")
(ImageSampler "Random")


// ************* Interpolation and Re-sampling ****************

(BSplineInterpolationOrder 1)

(FinalBSplineInterpolationOrder 3)

(DefaultPixelValue 0)

(WriteResultImage "true")

(ResultImagePixelType "short")
(ResultImageFormat "nii")

**Comment by N-Dekker** [comment]
Thanks for the extra information, @fernand-f 

> I've checked in the CMakeCache.txt file, and indeed `USE_AdvancedKappaStatisticMetric` and `USE_SimilarityTransformElastix` are set to `OFF`.

Please set them both to `ON`, do another CMake configure, generate, and build elastix again. Does that solve the issue?

**Comment by N-Dekker** [comment]
@fernand-f I'm glad to hear my comment was helpful to you!

I will close this issue for now, but if you encounter another problem, feel free to submit another issue to our GitHub page, or post a question to  https://groups.google.com/g/elastix-imageregistration
