### ISSUE TITLE
MacOS GitHub Actions, Azure Pipelines fatal error: ‘omp.h’ file not found

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#650]
Recently, MacOS/clang started producing errors on the elastix CI (both GitHub Actions and Azure Pipelines), saying:

> fatal error: 'omp.h' file not found

Discussed at ITK [MacOS GitHub Actions, Azure Pipelines: itkeigen/Eigen/Core: fatal error: ‘omp.h’ file not found]( https://discourse.itk.org/t/macos-github-actions-azure-pipelines-itkeigen-eigen-core-fatal-error-omp-h-file-not-found/4986), including suggestions by Pablo Hernandez-Cerdan (@phcerdan). 

GitHub Actions log: https://my.cdash.org/build/2165559 and https://my.cdash.org/viewBuildError.php?buildid=2165559

Azure Pipelines: https://dev.azure.com/kaspermarstal/Elastix/_build/results?buildId=3173&view=logs&j=d9d370b1-18a3-5231-ee95-54c0a379145c

**Comment by N-Dekker** [comment]
@tbirdso For your information, this issue is fixed now, with elastix pull request https://github.com/SuperElastix/elastix/pull/732 merged to the elastix main branch with commit 9cdca6df6cd2649fd4b69a43e1e4d56b91bb4a8c

**Comment by tbirdso** [comment]
Great work, thank you @N-Dekker !
