### ISSUE TITLE
The composition formula (2.19) in the manual is a bit odd...

### ISSUE THREAD

**Issue by GouZi2019** [SuperElastix/elastix#661]
If we perform a rigid transformation T1 and an nonrigid transformation T2 on the image one after another, then the transformation should be composited as T1◦T2, right?

Please refer to the link: https://www.javatpoint.com/computer-graphics-composite-transformation

However, the order of transformations in the composition formula (2.19) in the manual is reversed.

**Comment by mzukovec** [comment]
The order of operations should be read from the right to the left side, since we're transforming points as `x' = T * x`. `T2 * T1` should be interpreted as:
1. Apply transform T1
2. Apply transform T2
