### ISSUE TITLE
Call elastix libs from C++ code but get empty result from GetResultImage（）

### ISSUE THREAD

**Issue by suntraveler** [SuperElastix/elastix#669]
Hi guys,
I had compiled elastix lib and call it by c++. The registration succeeded but I cannot get the result image.I Get it from elastix.GetResultImage().GetPointer() and cast it to ImageType Pointer,and want to save the result as nii format .But I got an Exception "Largest possible region does not fully contain requested paste IO region" in the itkImageFileWriter.hxx when I save it, and I traced the Exception and found that the result pointer seems to be empty. I print the image pointer and got the info like this:

![image](https://user-images.githubusercontent.com/17895788/175295475-ac22f2c6-8725-4711-925d-9ee69db1f86a.png)

![image](https://user-images.githubusercontent.com/17895788/175292452-7e82bc46-7e1f-44cf-b721-a3545b63f359.png)

The code is this:
`ParserType::Pointer file_parser = ParserType::New();
	// Try parsing transform parameters text file.
	file_parser->SetParameterFileName("D:\\parameters_Affine1.txt");
	try
	{
		file_parser->ReadParameterFile();
	}
	catch (itk::ExceptionObject & e)
	{
		std::cout << e.what() << std::endl;
		// Do some error handling!
	}
	// Retrieve parameter settings as map.
	RegistrationParametersType parameters = file_parser->GetParameterMap();

	ELASTIX elastix;

	std::string sElastixOut = "D:\\ElastixLibOut";
	int error = 0;
	try
	{
		error = elastix.RegisterImages(
			static_cast<typename itk::DataObject::Pointer>(FixedData),
			static_cast<typename itk::DataObject::Pointer>(MovingData),
			parameters, // Parameter map read in previous code
			sElastixOut, // Directory where output is written, if enabled
			true, // Enable/disable writing of elastix.log
			true, // Enable/disable output to console
			nullptr, // Provide fixed image mask (optional, nullptr = no mask)
			nullptr // Provide moving image mask (optional, nullptr = no mask)
		);
	}
	catch (itk::ExceptionObject &err)
	{
		// Do some error handling.
	}
	if (error == 0)
	{
		if (elastix.GetResultImage().IsNotNull())
		{
			using OutPutPixelType = short;
			using OutPutImageType = itk::Image<OutPutPixelType, Dimension>;
			
			OutPutImageType* output_image = static_cast<OutPutImageType *>(elastix.GetResultImage().GetPointer());

                        OutPutImageType::Pointer ImageCout = output_image;
			std::cout << ImageCout << std::endl;
			
                        itk::NiftiImageIOFactory::RegisterOneFactory();
			using WriterType = itk::ImageFileWriter<OutPutImageType>;
			WriterType::Pointer NIIImageWriter;
			NIIImageWriter = WriterType::New();

			NIIImageWriter->SetFileName("OutPutData.nii");

			NIIImageWriter->SetInput(output_image);
			NIIImageWriter->Update();
		}
	}`

**Comment by Kunyadav** [comment]
Hi suntraveler,
  i am new to elastix and trying to compile the elastix 5.1.0 using cmake for my c++ application for both 32-bit and 64-bit. i can able to compiled and it create static libraries but while running sample program it giving linking errors
can you guide me how did you compile and share some sample c++ code?
Regards
Kunal
