### ISSUE TITLE
Version numbering of develop branch

### ISSUE THREAD

**Issue by Svdvoort** [SuperElastix/elastix#671]
Currently when compiling the code from the develop branch the version number of Elastix is still "5.0.1". 
This can be a bit confusing, especially when multiple instances of Elastix have been compiled and it is unclear which one is the actual stable "5.0.1" or which one is just the latest development version (and which version that is). 

Would it be possible to set the version number as something like "dev", or once a stable release has taken place to create a new temporary version number (like ITK)? The most favorable would be to use the GitHub hash of a commit for the version number, so it is instantly clear which exact version of the code has been used. 

In regards to this, is there a stable release coming up soon? The 5.0.1 release is quite old, and there have definitely been a lot of improvements in the development branch. Especially for publications, it is nice to be able to use a stable release version number.

**Comment by N-Dekker** [comment]
Thank you for submitting the issue, Sebastian. Our plan is to make a new stable release soon after the final release of ITK 5.3. I like your suggestion to use the GitHub hash, but have to check if it's feasible to implement. If so, would it be helpful to you to just have it displayed at the command-line, by `elastix --extended-version` ?

**Comment by Svdvoort** [comment]
Thanks for the implementation, the pull request looks great!
