### ISSUE TITLE
Failed to allocate memory for image

### ISSUE THREAD

**Issue by Kodemannen** [SuperElastix/elastix#680]
Trying to run a registration on a pair of scans:

`elastix -f Aperio/R27-0523_2_B_L1-3/R27-0523_2_B_L1-3.svs -m XR/R27-0523_2_B_L1-3.ndpi -out output  -p parameterFile.txt`

but it gives the following error:

```
elastix is started at Wed Jul  6 16:33:24 2022.

which elastix:   elastix
elastix runs at: samuelpc
  Linux 5.15.0-39-generic (x64), #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022
  with 31790 MB memory, and 4 cores @ 1412 MHz.
-------------------------------------------------------------------------

Running elastix with parameter file 0: "parameterFile.txt".

Current time: Wed Jul  6 16:33:24 2022.
Reading the elastix parameters from file ...

WARNING: The parameter "FixedInternalImagePixelType", requested at entry number 0, does not exist
 at all.
  The default value "float" is used instead.
WARNING: The parameter "MovingInternalImagePixelType", requested at entry number 0, does not exis
t at all.
  The default value "float" is used instead.
TIFFReadDirectory: Warning, Unknown field with tag 65420 (0xff8c) encountered.
(Lots of these warnings)
TIFFReadDirectory: Warning, Unknown field with tag 65458 (0xffb2) encountered.
Installing all components.
InstallingComponents was successful.

ELASTIX version: 5.0.1
Command line options from ElastixBase:
-f        Aperio/R27-0523_2_B_L1-3/R27-0523_2_B_L1-3.svs
-m        XR/R27-0523_2_B_L1-3.ndpi
-fMask    unspecified, so no fixed mask used
-mMask    unspecified, so no moving mask used
-out      output/
-p        parameterFile.txt
-threads  unspecified, so all available threads are used
WARNING: The parameter "UseDirectionCosines", requested at entry number 0, does not exist at all.
  The default value "true" is used instead.

WARNING: The option "UseDirectionCosines" was not found in your parameter file.
  From elastix 4.8 it defaults to true!
This may change the behavior of your registrations considerably.

Command line options from TransformBase:
-t0       unspecified, so no initial transform used

Reading images...

itk::ExceptionObject (0x7f83a4000b90)
Location: "unknown"
File: /home/niels_dekker/dev/src/ITK/Modules/Core/Common/include/itkImportImageContainer.hxx
Line: 192
Description: Failed to allocate memory for image.
Error occurred while reading the image described as Fixed Image, with file name Aperio/R27-0523_2
_B_L1-3/R27-0523_2_B_L1-3.svs


Errors occurred!

```
**Note that:**
- Elastix successfully produces an output image with transformation parameters etc. when running with two randomly chosen (small) .jpeg images.
- I saw that there is an issue for SimpleElastix for the same error (https://github.com/SuperElastix/SimpleElastix/issues/248), but it seems to conclude that the error was caused by the .ndpi format. But if I try running with the .svs as both the moving and the fixed image, it still gives the same error, so I don't think the issue is with the .ndpi. (Running registration with the same image as both the fixed and the moving image also works fine with a random .jpeg, so I don't think that should be a problem.)
- Running on Ubuntu 22.04 LTS
- Both images are about 1gb in size

My parameter file looks like this (I doubt it's relevant, but just in case):

```
(Metric "AdvancedNormalizedCorrelation")
(Transform "AffineDTITransform")
(Registration "MultiResolutionRegistration")
(ImageSampler "RandomCoordinate")
(Interpolator "LinearInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(Optimizer "AdaptiveStochasticGradientDescent")
(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")
(ResultImageFormat "nii")

```

**Comment by N-Dekker** [comment]
@Kodemannen Thank you for reporting this issue to us, Samuel, and thanks for all the details!

The exception appears to be thrown here: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc03/Modules/Core/Common/include/itkImportImageContainer.hxx#L191 causing a failure of the `ReadImage` call at https://github.com/SuperElastix/elastix/blob/5c493d358bc273cf8a568a4db11ad12d4f8ebe40/Core/Kernel/elxElastixBase.h#L460

Did you build elastix yourself, or did you use a pre-built binary?

It seems to me that the fixed image (R27-0523_2_B_L1-3.svs) just cannot be read, because of its size. Are you able to read the image outside of elastix, just by using an ITK based image reader?  Specifically, could you do something like `itk::ReadImage<itk::Image<float>>("R27-0523_2_B_L1-3.svs")` without getting out of memory?

**Comment by Kodemannen** [comment]
@N-Dekker Thanks for your quick reply!

I used a pre-built binary.

It looks like I am getting the same error when using ITK for Python:

`itktest.py`:
```
import itk
import os

# input_fln = os.path.expanduser("~/data/image-registration/XR/R27-0523_2_B_L1-3.ndpi")
input_fln = os.path.expanduser("~/data/image-registration/Aperio/R27-0523_2_B_L1-3/R27-0523_2_B_L1-3.svs")
image = itk.imread(input_fln)
```

Output:
(image-registration) samuel@samuelpc:~/repos/ImageRegistration$ python itktest.py
Traceback (most recent call last):
  File "/home/samuel/repos/ImageRegistration/itktest.py", line 8, in <module>
    image = itk.imread(input_fln)
  File "/home/samuel/anaconda3/envs/image-registration/lib/python3.9/site-packages/itk/support/extras.py", line 958, in imread
    reader.Update()
RuntimeError: /work/ITK-source/ITK/Modules/Core/Common/include/itkImportImageContainer.hxx:192:
Failed to allocate memory for image.
```

Occurs for both images, but with some extra warnings for the .ndpi.

**Comment by N-Dekker** [comment]
> Thanks for your quick reply!

You're welcome, @Kodemannen Thanks for trying out my suggestion! So now I think this issue should be solved in ITK, rather than in elastix! Unless it's just a limitation of your Ubuntu machine!

Do you have another (non-ITK) image reader or application available on your platform that is actually able to read in those two files successfully?

Maybe it's worth for you to submit the issue to ITK: https://github.com/InsightSoftwareConsortium/ITK/issues

**Comment by Kodemannen** [comment]
@N-Dekker I agree, I will take this to the ITK administration instead

By your suggestion I tried reading the image with [Slideio](https://pypi.org/project/slideio/), and it seems to work, so I will mention that to them.

Thanks again!
