### ISSUE TITLE
Double-check limitations of vtk file support

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#698]
According to the manual https://elastix.lumc.nl/download/elastix-5.0.1-manual.pdf 

> The support for .vtk files is still a bit limited. Currently, only ASCII files are supported, with triangular meshes.

It seems to me that non-triangular point lists are also supported, right?

I did encounter another limitation though: it appears that VTK only supports 3-D points. Should we adjust the manual accordingly?

**Comment by stefanklein** [comment]
Hi Niels, we use this implementation: https://itk.org/Doxygen/html/classitk_1_1VTKPolyDataReader.html . Not sure if it was update recently, but the documentation seems to mention the same limitations, but they also point to an alternative solution, so maybe that is useful?
Best, Stefan

From: Niels Dekker ***@***.***>
Sent: Monday, August 1, 2022 12:34 PM
To: SuperElastix/elastix ***@***.***>
Cc: Stefan Klein ***@***.***>; Assign ***@***.***>
Subject: [SuperElastix/elastix] Double-check limitations of vtk file support (Issue #698)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


According to the manual https://elastix.lumc.nl/download/elastix-5.0.1-manual.pdf<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Felastix.lumc.nl%2Fdownload%2Felastix-5.0.1-manual.pdf&data=05%7C01%7Cs.klein%40erasmusmc.nl%7C6d44361e21064b44b5c708da73a9647e%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637949469177412049%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I8GaJl4ag1k%2BDlkubbj267PUTrZPmUZdjMEU6qpLU%2BI%3D&reserved=0>

The support for .vtk files is still a bit limited. Currently, only ASCII files are supported, with triangular meshes.

It seems to me that non-triangular point lists are also supported, right?

I did encounter another limitation though: it appears that VTK only supports 3-D points. Should we adjust the manual accordingly?

-

**Comment by N-Dekker** [comment]
> we use this implementation: https://itk.org/Doxygen/html/classitk_1_1VTKPolyDataReader.html

Thanks @stefanklein, I see now, it says:

> Caveat1: itkVTKPolyDataReader can only read triangle meshes. Use vtkTriangleFilter to convert your mesh to a triangle mesh. Caviet2: itkVTKPolyDataReader can only read vtk legacy files. Caveat3: itkVTKPolyDataReader cannot read binary vtk files.

Interestingly, it also says about VTKPolyDataReader:
> This class may be deprecated in the future. The [MeshFileReader](https://itk.org/Doxygen/html/classitk_1_1MeshFileReader.html) is preferred

Only elxStatisticalShapePenalty still uses VTKPolyDataReader: https://github.com/SuperElastix/elastix/blob/4.9.0/Components/Metrics/StatisticalShapePenalty/elxStatisticalShapePenalty.hxx#L380

Other metrics components already use `itk::MeshFileReader`. `elastix::TransformBase` was upgraded from   `itk::VTKPolyDataReader` to  `itk::MeshFileReader` with ebcb511b02b2c555ffa8e7f2e0a89b3b74839ec5 ("ENH: switching elastix to ITK4 !", Marius, 13 Jan 2012.) Hopefully, `itk::MeshFileReader` has dropped the triangle-only limitation...

**Comment by stefanklein** [comment]
Hi Niels,
https://itk.org/Doxygen/html/classitk_1_1MeshFileReader.html
uses:
https://itk.org/Doxygen/html/classitk_1_1MeshIOBase.html
and specifically for VTK:
https://itk.org/Doxygen/html/classitk_1_1VTKPolyDataMeshIO.html
perhaps you can check the code of that class. Any easy way of testing the triangle limitation.
Probably would be good to also use this implementation in the statisticalshapepenalty. In any case, this is the recommended way to read/write vtk meshes.
Best, Stefan

**Comment by N-Dekker** [comment]
> perhaps you can check the code of that class. Any easy way of testing the triangle limitation.
Probably would be good to also use this implementation in the statisticalshapepenalty. In any case, this is the recommended way to read/write vtk meshes.

@stefanklein I double-checked: it is specifically the itkVTKPolyDataReader that requires POLYGONS in the vtk file. Otherwise it will throw an exception: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc04/Modules/Core/Mesh/include/itkVTKPolyDataReader.hxx#L177 

On the other hand, itk::MeshFileReader does accept vtk files without POLYGONS Which should be fine, as https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf says:

> None of the keywords VERTICES, LINES, POLYGONS, or TRIANGLE_STRIPS is required.  

So a vtk file may just contain a list of points, without triangles or other connections between them.

So yes, I replaced itkVTKPolyDataReader with itk::MeshFileReader in elxStatisticalShapePenalty, pull request https://github.com/SuperElastix/elastix/pull/699

**Comment by stefanklein** [comment]
Excellent, thanks!

**Comment by N-Dekker** [comment]
> Excellent, thanks!

You're welcome. BTW, it appears to me now that `itk::MeshFileReader<MeshType>` and `itk::MeshFileWriter<MeshType>` do support both 2D and 3D points. I mean, I tested with either a 2D or a 3D MeshType, and they both just appear to work fine. It's just the ITK/Python `itk.meshread` that assumes 3D (producing seemingly arbitrary values for the 3rd coordinate of each read point).

https://github.com/InsightSoftwareConsortium/ITK/blob/585b8f991d7c8fb2d84b51571c3c91f7ae79706e/Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx#L287 says:

>       this->m_PointDimension = 3; // vtk only support 3 dimensional points

But I guess it isn't so strict!  😃  With MeshFileReader and MeshFileWriter, 2D just works, using vtk files.

I think it's good to know, because otherwise our own specific elastix/transformix input and output point file formats would have been the _only_ file formats for 2D points, supported by elastix/transformix.

**Comment by stefanklein** [comment]
OK great, maybe bring that to the attention of the ITK-guys

**Comment by N-Dekker** [comment]
> OK great, maybe bring that to the attention of the ITK-guys

Good idea @stefanklein, it appears that there was an issue already, "Add 2D mesh support", I just added my comment: https://github.com/slicersalt/ITKShape/issues/8#issuecomment-1204999459

**Comment by stefanklein** [comment]
Ok, great, thanks Niels
