### ISSUE TITLE
Request: improve ElastixConfig for downstream packaging

### ISSUE THREAD

**Issue by hmaarrfk** [SuperElastix/elastix#71]
Hi, it seems that ElastixConfig.cmake is generated using the buildtime location of the source, and not with the install time locations of the directories.

It would be good if you could help generate the output of the files such that they point to their install locations.

**Comment by kaspermarstal** [comment]
The config files were recently improved in elastix but I am not sure if this is reflected on the SimpleElastix master branch yet. Have you tried the develop branch?

**Comment by mstaring** [comment]
should this not be optional? People will also choose not to install but link against the build dir, right?

**Comment by thewtex** [comment]
Two different *ElastixConfig.cmake*'s can be provided -- one that specifies how to build against the build tree, and one that specifies how to build against the install tree. The latter is installed.

Here is how it is done in ITK:

https://github.com/InsightSoftwareConsortium/ITK/blob/95a973c835bec1f66da30eebaaae59d5eee42053/CMakeLists.txt#L438-L474

**Comment by N-Dekker** [comment]
Thanks for reporting. As far as I can see, it is fixed by now, by https://github.com/SuperElastix/elastix/pull/655 (by @blowekamp).

Please reopen, if you think otherwise.
