### ISSUE TITLE
Exact metric not returning value

### ISSUE THREAD

**Issue by thatguy14** [SuperElastix/elastix#74]
Hello, I am trying to determine if the current registration I am preforming is converging. I turned on the exact metric to true but it is just returning "-nan(ind)" Here is the code of my parameter file thanks for your time!

```
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(FixedImageDimension 3)
(MovingImageDimension 3)
(UseDirectionCosines "true")

// **************** Main Components **************************

(Registration "MultiMetricMultiResolutionRegistration")
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")

(FixedImagePyramid "FixedSmoothingImagePyramid")
(MovingImagePyramid "MovingSmoothingImagePyramid")

(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "RecursiveBSplineTransform")
(Metric "AdvancedMattesMutualInformation" "TransformBendingEnergyPenalty")
//(Metric "PCAMetric2" "TransformBendingEnergyPenalty")
(Metric0Weight 1)
(Metric1Weight 50) // OPTIMIZED BY QUANTITATIVE MEASURES

// ***************** Transformation **************************

(GridSpacingSchedule 4 2 1)
(FinalGridSpacingInPhysicalUnits 10 10 10)
(HowToCombineTransforms "Compose")

// ******************* Similarity measure *********************

(NumberOfHistogramBins 100) // OPTIMIZED BY QUANTITATIVE MEASURES

// ******************** Multiresolution **********************

(NumberOfResolutions 3)
(ImagePyramidSchedule 8 8 8  4 4 4  1 1 1 1 1 1) // ACCOUNTING FOR ANISOTROPIC RESOLUTION

// ******************* Optimizer ****************************

(MaximumNumberOfIterations 3000) // COULD PROBABLY BE LOWERED, ESPECIALLY FOR THE FIRST LEVELS OF THE IMAGE PYRAMID

// **************** Image sampling **********************

(NumberOfSpatialSamples 10000) // COULD PROBABLY BE LOWERED, ESPECIALLY FOR THE FIRST LEVELS OF THE IMAGE PYRAMID
(NewSamplesEveryIteration "true")
(ImageSampler "MultiInputRandomCoordinate")
(SampleRegionSize 40)  // OPTIMIZED BY QUANTITATIVE MEASURES
(UseRandomSampleRegion "true")
(MaximumNumberOfSamplingAttempts 10)
(RequiredRatioOfValidSamples 0.05)

// ************* Interpolation and Resampling ****************

(BSplineInterpolationOrder 1)
(FinalBSplineInterpolationOrder 3)

(ShowExactMetricValue "false" "false" "true") 
(WriteTransformParametersEachResolution "true")
(WriteResultImageAfterEachResolution "true")
//(WritePyramidImagesAfterEachResolution "true")

(DefaultPixelValue 0)
(WriteResultImage "true")
(ResultImagePixelType "short")
(ResultImageFormat "nrrd")
```

**Comment by YuchuanQiao** [comment]
Could you please also provide your elastix.log file?

**Comment by YuchuanQiao** [comment]
It looks like TransformBendingEnergyPenalty metric did not return a valid exact metric value. I checked the code and found that m_NumberOfPixelsCounted is zero, which is related to the parameter setting (UseRandomSampleRegion "true") . You should set this one to false, and then the value will be not -nan(ind).

However, there is still another bug when using MultiMetricMultiResolutionRegistration (I suspect), because even you change the setting to false, you can only get 0.0 exact metric value. You can add one line to src/Core/ComponentBaseClasses/elxMetricBase.hxx, (line number 293)  this->m_ExactMetricSampler->Update(); before this->SetAdvancedMetricImageSampler( this->m_ExactMetricSampler ); Then build your solution again, you could get your desired exact metric value.

@mstaring Hi Marius, could you please double-check this?

**Comment by thatguy14** [comment]
Concerning your first point, you mean it's because I used a sample region rather than the full image? Can you only get the exact metric value when using the full image rather than a sampling? 

Thanks for your help!

**Comment by YuchuanQiao** [comment]
Yes. Now the exact metric value is calculated with a grid sampler with grid spacing 1, which is almost equivalent to a full sampler.  You could use (ExactMetricSampleGridSpacing 2)
(ExactMetricEveryXIterations 5) to control your calculation speed.

**Comment by mstaring** [comment]
https://github.com/SuperElastix/elastix/commit/447a8e4022b68a5cb4d6ad2a39c7fc67f80718cb

fixes this.  It was due to the exact sampler not being updated in this corner case.

Thanks for the report! Feel free to re-open when problems persist.
