### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skn123** [SuperElastix/elastix#75]
/home/naths/srcs/elastix/Common/CostFunctions/itkAdvancedImageToImageMetric.hxx:90:21: error: 
      no member named 'SetUseThreadPool' in 'itk::MultiThreaderBase'
  this->m_Threader->SetUseThreadPool( false ); // setting to true makes ...
  ~~~~~~~~~~~~~~~~  ^

ITK (master branch from Github)
elastix (master branch from Github)

**Comment by mstaring** [comment]
elastix does not yet support newer versions of ITK yet, where they changed/removed this function. If you compile with an earlier version of ITK, all should be fine.
