### ISSUE TITLE
about c++

### ISSUE THREAD

**Issue by sunyi970505** [SuperElastix/elastix#76]
how to use it in c++？I want to include it in my c++ application,

**Comment by abenchaaben** [comment]
Hi,

did you build the library. If you did, look at the documentation, thye are an example on how to use it inside an application without the use of the command line : 

#include "elastixlib.h"
#include "itkParameterFileParser.h"
using namespace elastix;
typedef ELASTIX::ParameterMapType RegistrationParametersType;
typedef itk::ParameterFileParser ParserType;
// Create parser for transform parameters text file.
ParserType::Pointer file_parser = ParserType::New();
// Try parsing transform parameters text file.
file_parser->SetParameterFileName( "par_registration.txt" );
try
{
file_parser->ReadParameterFile();
}
catch( itk::ExceptionObject & e )
{
std::cout << e.what() << std::endl;
// Do some error handling!
}
// Retrieve parameter settings as map.
RegistrationParametersType parameters = file_parser->GetParameterMap();

**Comment by sunyi970505** [comment]
Thank you , but I have a problem .

error = elastix->RegisterImages(
static_cast<typename itk::DataObject::Pointer>( fixed_image.GetPointer() ),
static_cast<typename itk::DataObject::Pointer>( moving_image.GetPointer() ),
parameters, // Parameter map read in previous code
43
output_directory, // Directory where output is written, if enabled
write_log_file, // Enable/disable writing of elastix.log
output_to_console, // Enable/disable output to console
0, // Provide fixed image mask (optional, 0 = no mask)
0 // Provide moving image mask (optional, 0 = no mask)
);

How to get fixed_image and moving_image?
This is my code. But it is error.

ELASTIX* elastix = new ELASTIX(); // 定义Elastix
    typedef itk::RGBPixel< unsigned char >   PixelType;
    typedef itk::Image< PixelType, 2 >       ImageType;
    typedef itk::ImageFileReader<ImageType> ReaderType;
    ReaderType::Pointer fixed_image = ReaderType::New();
    fixed_image->SetFileName("DealImageTempFile/CutImageDirectory/0.png");
    fixed_image->Update();
    ReaderType::Pointer moving_image = ReaderType::New();
    moving_image->SetFileName("DealImageTempFile/CutImageDirectory/1.png");
    moving_image->Update();
    elastix->RegisterImages(fixed_image->GetOutput(), moving_image->GetOutput(),     (*parametersPointer),"OutputDirectory",true,true, 0,0);

**Comment by sunyi970505** [comment]
@abenchaaben

**Comment by abenchaaben** [comment]
I think that because you use RGBpixel type. The pixel type for your image should be the same as your pixel type in the parameters file.

**Comment by sunyi970505** [comment]
I change my code . But it is still error. How to solve? where is the parameters file.

ELASTIX* elastix = new ELASTIX();
	typedef itk::Image<unsigned short, 2> ImageType;
	typedef itk::ImageFileReader<ImageType> ReaderType;  
	ReaderType::Pointer fixed_image = ReaderType::New();
	fixed_image->SetFileName("DealImageTempFile/CutImageDirectory/0.png");
	fixed_image->Update();
	ReaderType::Pointer moving_image = ReaderType::New();
	moving_image->SetFileName("DealImageTempFile/CutImageDirectory/1.png");
	moving_image->Update();
	elastix->RegisterImages(fixed_image->GetOutput(), moving_image->GetOutput(),(*parametersPointer),"OutputDirectory",true,true, 0,0);

**Comment by sunyi970505** [comment]
@abenchaaben

**Comment by sunyi970505** [comment]
Have you ever use it? Can you give me see your code ? Thand you

**Comment by abenchaaben** [comment]
I used the same code in the documentation of elastix. The parameters file is a txt file with the information about the regsitration. You can find some example here : 
http://elastix.bigr.nl/wiki/index.php/Parameter_file_database

**Comment by sunyi970505** [comment]
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(FixedImageDimension 2)
(MovingImageDimension 2)
(UseDirectionCosines "true")
(Registration "MultiResolutionRegistration")
(Interpolator "BSplineInterpolator")
(ResampleInterpolator "FinalBSplineInterpolator")
(Resampler "DefaultResampler")
(FixedImagePyramid "FixedRecursiveImagePyramid")
(MovingImagePyramid "MovingRecursiveImagePyramid")
(Optimizer "AdaptiveStochasticGradientDescent")
(Transform "BSplineTransform")
(Metric "AdvancedNormalizedCorrelation")
(AutomaticScalesEstimation "true")
(AutomaticTransformInitialization "true")
(HowToCombineTransforms "Compose")
(NumberOfHistogramBins 32)
(ErodeMask "false")
(NumberOfResolutions 1)
(ImagePyramidSchedule 3 3)
(FinalGridSpacingInVoxels 16 16)
(MaximumNumberOfIterations 6)
(NumberOfSpatialSamples 7)
(NewSamplesEveryIteration "true")
(ImageSampler "Random")
(BSplineInterpolationOrder 3)
(FinalBSplineInterpolationOrder 2)
(DefaultPixelValue 0)
(WriteResultImage "true")
(ResultImagePixelType "float")
(ResultImageFormat "vtk")

This is my parameter. I don't know the problem

**Comment by sunyi970505** [comment]
My problem is how to get fixed_image and moving_image

elastix->RegisterImages(
static_cast<typename itk::DataObject::Pointer>( fixed_image.GetPointer() ),
static_cast<typename itk::DataObject::Pointer>( moving_image.GetPointer() ),

**Comment by mstaring** [comment]
This is more a question for the mailing list:
https://groups.google.com/forum/#!categories/elastix-imageregistration/elastix

But I hope you were able to fix your code in the meantime!
