### ISSUE TITLE
Apply transformix on very large image speed up

### ISSUE THREAD

**Issue by abenchaaben** [SuperElastix/elastix#77]
Hi,

I'm using elastix to perform registration on high resolution images (100000x51000). I'm performing the registration on low resolution image and applying it on the full resolution image. Evry thing work fine, but the transformix part take very much time (20 minutes). I tried to use OpenCL resampling but i'm getting buffer size error. Is there any way to speed up the resampling part of the process.

Thank you in advance.

**Comment by mstaring** [comment]
answered on the mailing list:
https://groups.google.com/forum/#!category-topic/elastix-imageregistration/elastix/dwNiDYmr9NQ
