### ISSUE TITLE
Missing cmake package config files

### ISSUE THREAD

**Issue by osemmler** [SuperElastix/elastix#78]
When building Elastix as library
```
cmake .. -DELASTIX_BUILD_EXECUTABLE:BOOL=OFF
```

CMake sucessfully generate files
```
ElastixConfig.cmake
ElastixConfigVersion.cmake
ElastixTargets.cmake
```
__________________________________________

But when I try to install Elastix to install directory with 
```
make install
```
 these 3 files is not installed to CMAKE_INSTALL_PREFIX path.

**Comment by N-Dekker** [comment]
Thanks for reporting. As far as I can see, it is fixed by now, by https://github.com/SuperElastix/elastix/pull/655 (by @blowekamp).

Please reopen, if you think otherwise.
