### ISSUE TITLE
How to use elastix in C++ application？

### ISSUE THREAD

**Issue by sunyi970505** [SuperElastix/elastix#80]
How to use transformix to create .vtk file? 

TRANSFORMIX* transformix = new TRANSFORMIX();
	int errorTransformix = transformix->TransformImage(elastix->GetResultImage().GetPointer() , transform_parameters, "OutputDirectory/", true, true);

By this , I only get imageType

**Comment by mstaring** [comment]
Please see chapter 7 of the manual.
