### ISSUE TITLE
transformix can't be built as shared library

### ISSUE THREAD

**Issue by Nekto89** [SuperElastix/elastix#81]
It uses the same macro as elastix target. This macro is converted to __declspec(dllimport) instead of export during build.
It should use another macro for exporting.

https://github.com/SuperElastix/elastix/blob/582876b698c58a0b54ef9e3cf2f0733aeb53b71c/Core/Install/elxMacro.h#L289
https://github.com/SuperElastix/elastix/blob/582876b698c58a0b54ef9e3cf2f0733aeb53b71c/Core/Main/transformixlib.h#L36

**Comment by ssonuri** [comment]
It is error of the preprocessor definitions (/D).
You need to change **transformix_EXPORTS** to **elastix_EXPORTS**.

**Comment by mstaring** [comment]
@N-Dekker could you have a look?

**Comment by N-Dekker** [comment]
@mstaring I never tried to build a transformix DLL. Should it work, just by adding CMake flags BUILD_SHARED_LIBS=ON and ELASTIX_BUILD_EXECUTABLE=OFF to an elastix CMake configuration?

**Comment by haampie** [comment]
It does not build shared libraries on the mac, I just checked this; a month ago I compiled it with `BUILD_SHARED_LIBS=ON` and `ELASTIX_BUILD_EXECUTABLE=ON` and never bothered checking the actual output -- but I'm just seeing a bunch of static libs (`*.a`) except for `ibANNlib-4.9.dylib`.

**Comment by haampie** [comment]
Hm, well, there's a couple places where `STATIC` / `SHARED` are fixed in `add_library`, that's probably the issue.

**Comment by mstaring** [comment]
@N-Dekker did we decide to not support shared libraries?

**Comment by N-Dekker** [comment]
@mstaring Marius, indeed as elastix and transformix no longer support shared libraries, this issue should be closed.

@Nekto89 Marian, thank you for reporting this issue! I hope it was still feasible to you to switch to using transformix as static library, or as executable, instead of as a shared library!
