### ISSUE TITLE
Unable to run/compile elastix for CentOS6

### ISSUE THREAD

**Issue by Drigomaniac** [SuperElastix/elastix#82]
Hi all, 
I am trying to run elastix in a CentOS6 linux Virtual Machine but I believe I run into compiler issues (I believe) due to the outdated libraries that aren't supported. I was wondering if somebody has dealt with this issue or how I can fix it. Below is what I tried (w/ version 4.8):

`~/sw/elastix/v4.8/bin/elastix
/home/rperea1/sw/elastix/v4.8/bin/elastix: error while loading shared libraries: libANNlib.so: cannot open shared object file: No such file or directory`

`rperea1@camhpcvc24:~$ export LD_LIBRARY_PATH=~/sw/elastix/v4.8/lib`

`rperea1@camhpcvc24:~$ ~/sw/elastix/v4.8/bin/elastix 
/home/rperea1/sw/elastix/v4.8/bin/elastix: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.15' not found (required by /home/rperea1/sw/elastix/v4.8/bin/elastix)`
`/home/rperea1/sw/elastix/v4.8/bin/elastix: /lib64/libc.so.6: version 'GLIBC_2.15' not found (required by /home/rperea1/sw/elastix/v4.8/bin/elastix) /home/rperea1/sw/elastix/v4.8/bin/elastix: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /home/rperea1/sw/elastix/v4.8/bin/elastix)`

I feel it may be related to [this](https://stackoverflow.com/questions/31525271/usr-lib64-libstdc-so-6-version-glibcxx-3-4-15-not-found) but none of the solutions have worked for me. Any other suggestions??

Thanks in advance, 
Rodrigo

**Comment by mstaring** [comment]
Great that you found an answer!

**Comment by kaizen89** [comment]
@Drigomaniac I got a similar error on ubuntu 18.04, unable to find a solution, link is broken.

**Comment by Drigomaniac** [comment]
Hi @kaizen89 unfortunately I cannot recall the resolution and you are right, the link is broken 👎 
My best suggestion is to google a solution (as I did)  and hopefully identify the similar broken link that I presume changed domain. 
Sorry I cannot be of greater help
