### ISSUE TITLE
Build with ITK_FUTURE_LEGACY_REMOVE=ON

### ISSUE THREAD

**Issue by dzenanz** [SuperElastix/elastix#85]
If ITK 4.13.1 is built with option `ITK_FUTURE_LEGACY_REMOVE` set to `ON`, _elastix_ fails to build. The first error, and many others are related to `purposeful_error("itkGetObjectMacro should be replaced with itkGetModifiableObjectMacro.")`. I suspect that it would not take a lot of effort to accomplish this.

**Comment by mstaring** [comment]
Can this be closed @N-Dekker ?

**Comment by N-Dekker** [comment]
@mstaring Yes, this can be closed! Hereby!
