### ISSUE TITLE
MovingImagePyramidBase, FixedImagePyramidBase have different defaults for "NumberOfResolutions"

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#858]
`MovingImagePyramidBase::SetMovingSchedule()` uses zero as default value for "NumberOfResolutions", and then produces an error message when it is indeed zero! Looking at commit ab62f3deca0c4782de2cb5c8abd0c6d040f893f3 (September 6, 2004)

https://github.com/SuperElastix/elastix/blob/ab62f3deca0c4782de2cb5c8abd0c6d040f893f3/src/Core/ComponentBaseClasses/elxMovingImagePyramidBase.hxx#L38-L43

On the other hand, commit f84ac0d1094ebdb13e456b1b8cf1f6f9bfcd0a38 (ENH: First checkin of a generic pyramid..., Feb 2, 2012) has changed the default for "NumberOfResolutions" in `FixedImagePyramidBase` to `3`, and silently accepts zero as well, assuming it should be one:

https://github.com/SuperElastix/elastix/blob/f84ac0d1094ebdb13e456b1b8cf1f6f9bfcd0a38/src/Core/ComponentBaseClasses/elxFixedImagePyramidBase.hxx#L104-L107

Other places (MultiMetricMultiResolutionRegistration, MultiResolutionRegistration) also use `3` as default value. 

Should `MovingImagePyramidBase::SetMovingSchedule()` also use `3` as default value?

**Comment by mstaring** [comment]
let's use 3 everywhere as a default
