### ISSUE TITLE
What are the settings for the generic (all) registration algorithm?

### ISSUE THREAD

**Issue by stevenagl12** [SuperElastix/elastix#88]
What are the default parameters for this registration option? Also, what types of transforms are used in this, are they just rigid and affine, or are there more transforms in this method? Finally, is the registration cost function mutual information for this?

**Comment by kaspermarstal** [comment]
The default strategy is translation -> affine -> bspline. You can see the parameters using sitk.PrintParameterMap(elastixImageFilter.GetParameterMap()).

**Comment by stevenagl12** [comment]
I'm using 3D Slicer for my research, and am very new to Python. I got your message, but besides importing sitk I am not sure how to access the elastxImageFilter to get the parameters. Also, you never mentioned in the email what the registration cost function for the process is?

**Comment by mstaring** [comment]
This seems like a good question for the mailing list. Could you post here:

https://groups.google.com/forum/#!forum/elastix-imageregistration
Your question seems related to simpleelastix?
