### ISSUE TITLE
ParameterObject::WriteParameterFiles does not write the first map!

### ISSUE THREAD

**Issue by N-Dekker** [SuperElastix/elastix#904]
It appears that `ParameterObject::WriteParameterFiles` skips the first map from the specified `parameterMapVector`: https://github.com/SuperElastix/elastix/blob/81324cf0158256ae48a14762514ce60e786ac485/Core/Main/elxParameterObject.cxx#L379-L401

The bug appears introduced with pull request #50 commit 9ba16836e1a0642ecd2006a70ce3886b1fa4720e "ENH: Add convenience methods for writing parameter files", merged on March 20, 2018, when the member function became as follows: https://github.com/SuperElastix/elastix/blob/9ba16836e1a0642ecd2006a70ce3886b1fa4720e/Core/Main/elxParameterObject.cxx#L256-L280

FYI @kaspermarstal

**Comment by thewtex** [comment]
I also encountered this issue:

https://github.com/InsightSoftwareConsortium/ITKElastix/blob/29ce6866414070136bb5bc2f70129eafcdde7040/wasm/write-parameter-files.cxx#L74-L76

**Comment by N-Dekker** [comment]
@dzenanz @thewtex Please check:

- https://github.com/SuperElastix/elastix/pull/967

**Comment by N-Dekker** [comment]
> I also encountered this issue:
> https://github.com/InsightSoftwareConsortium/ITKElastix/blob/29ce6866414070136bb5bc2f70129eafcdde7040/wasm/write-parameter-files.cxx#L74-L76

@thewtex Thanks Matt! Please remember that these two lines should be removed, once ITKElastix has been updated to include elastix PR #967 (commit a57470b0ccfcab925e101f6e6577abaf2074574a):

    // The initial is not written by WriteParameterFiles
    ITK_WASM_CATCH_EXCEPTION(pipeline, elastix::ParameterObject::WriteParameterFile(parameterMaps[0], parameterFiles[0]));
