### ISSUE TITLE
Elastix sometimes hangs when SampleRegionSize smaller than 20

### ISSUE THREAD

**Issue by nwschurink** [SuperElastix/elastix#93]
I am trying to registering 2 images of size 256x256x35 and am currently optimizing the hyperparameters for non-rigid registration. For registration I am using a mask to focus the registration on the area of interest.

During hyperoptimization I noticed that for some images Elastix will hang when SampleRegionSize is smaller than 20. 
I have attached the log file (elastix_hangs.log) for a case where it hangs using (SampleRegionSize 15), 
a log file (elastix_doesnt_hang1.log) for the same case where it doesn't hang using (SampleRegionSize 20), 
a log file (elastix_doesnt_hang2.log) for a different image pair where it doesn't hang using (SampleRegionSize 15).

[elastix_hangs.log](https://github.com/SuperElastix/elastix/files/2724218/elastix_hangs.log)
[elastix_doesnt_hang1.log](https://github.com/SuperElastix/elastix/files/2724233/elastix_doesnt_hang1.log)
[elastix_doesnt_hang2.log](https://github.com/SuperElastix/elastix/files/2724296/elastix_doesnt_hang2.log)

I was wondering, is this expected behaviour? Also, the log's don't report any errors I'm curious what the underlying reason for this hang could be?

**Comment by nwschurink** [comment]
Any insights on the issue? Or perhaps a way to get a more meaningful description in the log of why exactly Elastix hangs?

**Comment by mstaring** [comment]
I guess that elastix was not able to get a sufficient number of samples from such a small region.
elastix should never hang though, so this is a bug.

But note that this sample region should not be too small anyway, since it is meant to battle inhomogeneities on a bit larger scale.

**Comment by nwschurink** [comment]
Interestingly my registrations get better at somewhat smaller sample region sizes, so this would be interesting to investigate further. Lowering the number of samples to be drawn doesn't seem to fix the problem of hanging though. Do you have any other suggestions on how to circumvent this bug?

**Comment by mstaring** [comment]
That would be debugging the source code
